deploy/code.yml, deploy/dependencies.yml, deploy/playbook_lxde.yml, deploy/xForge.yml
- Fix permissions (shell from Vagrantfile leaves root.root permissions)
- Make code operations separate and non sudo
=> deploy: Change permissions in src folder to vagrant/vagrant

deploy/code.yml, deploy/playbook_mint.yml, deploy/vars_mint.yml
Added configuration files for mint.  Changed variables to suit, removed redundant chown.  Commented out scriptureforge setup in code.yml.  YMMV.
=> deploy: Added mint configuration

README.md
These changes to the README are mainly relating to issues I ran into while setting up a development environment. There are more issues I ran into, but those need some discussion first.
The one place I'm not sure I interpreted correctly is [line 167](https://github.com/sillsdev/web-languageforge/commit/f5480f5c71f4de7c09da4237fb6c7d097a964f15#diff-04c6e90faac2675aa89e2176d2eec7d8R167):
``` diff
- Modify `/usr/local/lib/node_modules/jscs/presets/airbnb.json` and set the line 
+ Modify `/usr/local/lib/node_modules/jscs/presets/airbnb.json` and change `"requireTrailingComma"` to
`"disallowTrailingComma": true,`
```
=> Edit README to clarify setup instructions where I ran into issues

src/angular-app/bellows/apps/userprofile/bootstrap4/userprofile.html, src/angular-app/bellows/apps/userprofile/userprofile.js
Also no longer reloads the page to update the avatar.
=> Fix missing notices on user profile page

src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/reset_password/languageforge_reset_password.scss, src/angular-app/bellows/apps/public/forgot_password/bootstrap4/forgot_password.html, src/angular-app/bellows/apps/public/reset_password/bootstrap4/languageforge_reset_password.css, src/angular-app/bellows/apps/public/reset_password/bootstrap4/reset_password.html, src/angular-app/bellows/apps/public/reset_password/reset_password.js, src/angular-app/bellows/apps/public/signup/bootstrap4/languageforge_signup.css, src/angular-app/bellows/apps/userprofile/bootstrap4/languageforge_userprofile.css, src/angular-app/languageforge/lexicon/new-project/bootstrap4/languageforge_new-project.css, test/app/bellows/pages/util.js, test/app/languageforge/lexicon/editor/e2e/editor-entry.spec.js, test/app/languageforge/lexicon/pages/configurationPage.js, test/app/languageforge/lexicon/pages/editorPage.js
Fix up forgot password page and port reset password page to Bootstrap 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/73)
=> Fix forgot password and BS4ify reset password page

src/Site/Controller/Auth.php
Previously the error div appeared, but no message was shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/74)
=> Show error message on login with bad credentials

gulpfile.js, src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/base/_global.scss, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/base/_variables.scss, src/angular-app/bellows/directive/bootstrap4/listview.html, src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html, src/angular-app/languageforge/lexicon/bootstrap4/languageforge_lexicon.css, src/angular-app/languageforge/lexicon/views/editor.scss, test/app/protractorConf.js
The commit messages sum it up pretty well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/77)
=> Changes to gulpfile, mobile, e2e, and more

.gitignore, README.md, gulpfile.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/80)
=> Refactor SASS compilation in gulpfile

src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/projects/languageforge_projects.scss, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/signup/languageforge_signup.scss, src/angular-app/bellows/apps/projects/bootstrap4/projects.html
- Clean up the mobile header for logged-out users
- Fix mobile layout (lack of left margin) on projects page, as well as increasing the display density in the list of projects
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/82)
=> Improvements on mobile

src/Site/Controller/App.php, src/angular-app/bellows/apps/public/registration/bootstrap4/registration.html, src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-identify.html, src/angular-app/bellows/apps/public/signup/views/bootstrap4/form-register.html, src/angular-app/bellows/apps/public/signup/views/bootstrap4/validate.html
This brings registration to Bootstrap 4 and tells users to sign in right away without verifying their email address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/83)
=> Don't tell users they need to verify their email

src/Site/views/languageforge/theme/default/cssBootstrap4/sass/base/_global.scss, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/lexicon/_configuration.scss, src/Site/views/languageforge/theme/default/cssBootstrap4/sass/lexicon/_project_settings.scss, src/angular-app/bellows/directive/bootstrap4/picklist-editor.html, src/angular-app/bellows/directive/bootstrap4/pui-delete-project.html, src/angular-app/languageforge/lexicon/views/configuration-input-systems.html, src/angular-app/languageforge/lexicon/views/configuration.html, src/angular-app/languageforge/lexicon/views/new-custom-field.html, test/app/bellows/pages/util.js, test/app/languageforge/lexicon/configuration/e2e/inputSystems.spec.js, test/app/languageforge/lexicon/pages/configurationPage.js
It's still not mobile responsive, but it's a big improvement on desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/88)
=> Bootstrapify project settings and config pages

src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.comments-right-panel.html, src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.dc-comment.html, src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.dc-comment.scss, src/angular-app/bellows/directive/bootstrap4/palaso.ui.comments.regarding-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/89)
=> Fix layout in lexicon comment view

.gitignore, src/Api/Model/Scriptureforge/Sfchecks/Dto/ProjectPageDto.php, src/Site/Controller/App.php, src/Site/views/languageforge/theme/default/sass/_global.scss, src/Site/views/scriptureforge/container/scriptureforgeBootstrap4.html.twig, src/Site/views/scriptureforge/theme/default/sass/_global.scss, src/Site/views/scriptureforge/theme/default/sass/scriptureforge_default.scss, src/angular-app/bellows/apps/activity/bootstrap4/activity.html, src/angular-app/bellows/apps/projects/bootstrap4/projects.scss, src/angular-app/bellows/cssBootstrap4/palaso-ui.scss, src/angular-app/bellows/directive/bootstrap4/picklist-editor.html, src/angular-app/bellows/directive/bootstrap4/pui-run-report.html, src/angular-app/bellows/directive/soundmanager2-ng.js, src/angular-app/bellows/directive/tagging.js, src/angular-app/languageforge/lexicon/views/view-settings.html, src/angular-app/scriptureforge/sfchecks/partials/project.html, src/angular-app/scriptureforge/sfchecks/partials/projectSettings.html, src/angular-app/scriptureforge/sfchecks/partials/projectSettings.js, src/angular-app/scriptureforge/sfchecks/partials/question.html, src/angular-app/scriptureforge/sfchecks/partials/question.js, src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html, src/angular-app/scriptureforge/sfchecks/partials/questions.html, src/angular-app/scriptureforge/sfchecks/partials/questions.js, src/angular-app/scriptureforge/sfchecks/sfchecks.html, src/angular-app/scriptureforge/sfchecks/sfchecks.scss, test/app/bellows/pages/util.js, test/app/scriptureforge/sfchecks/pages/projectPage.js, test/app/scriptureforge/sfchecks/pages/projectSettingsPage.js, test/app/scriptureforge/sfchecks/pages/questionPage.js, test/app/scriptureforge/sfchecks/pages/textPage.js
There are still some rough edges, the homepage remains unchanged, and the header and footer are basically Language Forge clones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/95)
=> Port Scripture Forge to Bootstrap 4

README.md, src/angular-app/scriptureforge/sfchecks/partials/projectSettings.html, test/app/languageforge/lexicon/pages/editorPage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/99)
=> Fix e2e tests and update documentation

src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html, src/angular-app/scriptureforge/sfchecks/new-project/views/new-project-name.html
I missed this one in the initial port to Bootstrap 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/98)
=> Bootstrap SF new project wizard

src/Api/Model/Shared/Command/UserCommands.php, src/Api/Model/Shared/UserModel.php, src/Api/Service/Sf.php, src/Site/Handler/LogoutSuccessHandler.php, src/angular-app/bellows/apps/userprofile/bootstrap4/userprofile.html, src/angular-app/bellows/apps/userprofile/bootstrap4/userprofile.scss, src/angular-app/bellows/apps/userprofile/userprofile.js, test/app/bellows/pages/userProfilePage.js, test/app/bellows/userProfile/e2e/userprofile.spec.js, test/php/model/shared/commands/UserCommandsTest.php
-check unique username/email before updating user profile
-successfully changing username/email notifies client to logout/login
-regrouped fields on profile tabs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/97)
=> Allow user to change username/email on user profile

src/Site/views/languageforge/theme/default/sass/_global.scss, src/angular-app/bellows/directive/bootstrap4/pui-language.html, src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.js, src/angular-app/languageforge/lexicon/new-project/views/new-project-sr-clone.html, src/angular-app/languageforge/lexicon/views/configuration.js, src/angular-app/languageforge/lexicon/views/select-new-language.html
Several fixes, mostly mobile related, for the new project wizard. Fixes the backwards typing on Android issue, making the language select modal mostly usable (it's still not a good experience on mobile, but it works now).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/103)
=> Misc. fixes, mainly for mobile

src/Api/Model/Shared/Dto/ManageUsersDto.php, src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig, src/Site/views/scriptureforge/container/scriptureforgeBootstrap4.html.twig, src/Site/views/scriptureforge/theme/default/sass/_global.scss, src/angular-app/bellows/cssBootstrap4/palaso-ui.scss, src/angular-app/bellows/directive/bootstrap4/listview.html, src/angular-app/scriptureforge/sfchecks/partials/projectSettings.html, src/angular-app/scriptureforge/sfchecks/partials/projectSettings.js, src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html, src/angular-app/scriptureforge/sfchecks/sfchecks.scss
Fixes the issues @irahopkinson put on Trello for the BS4 upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/104)
=> Fix Scripture Forge BS4 styling issues

src/Site/views/scriptureforge/theme/default/page/home/index.html.twig
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/109)
=> Add sign in and sign up buttons to Scripture Forge

src/Site/views/shared/container/container.html.twig, src/Site/views/shared/page/cache.manifest.html.twig, src/angular-app/bellows/apps/projects/projects.js, src/angular-app/bellows/js/bellows.services.editorData.js, src/angular-app/bellows/js/bellows.services.offlineCache.js, src/angular-app/bellows/js/bellows.services.offlineCacheUtils.js, src/angular-app/bellows/js/bellows.services.project.js, src/offline.html
Offline mode partially works, but 151 tests fail. Therefore it is disabled (see `container.html.twig` to re-enable it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/107)
=> Offline mode using app cache manifest

deploy/dependencies.yml, src/Api/Library/Shared/Palaso/InternationalUtility.php, src/Api/Library/Shared/Palaso/JsonRpcServer.php, src/Api/Service/Sf.php, src/Site/Controller/Upload.php, test/php/library/shared/InternationalUtilityTest.php
- remove SF::checkPermissions second argument
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/129)
=> Normalize to NFC at API border

src/angular-app/languageforge/lexicon/views/editor.js
Prioritizes search results with the following priority:
- word begins with query
- word contains query
- meaning begins with query
- meaning contains query
- everything else
This interacts well with sort and filter options.
This fixes sillsdev/web-languageforge#139,
fixes sillsdev/web-languageforge#115,
fixes sillsdev/web-languageforge#15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/147)
=> prioritize search results for exact matches first

src/angular-app/languageforge/lexicon/views/configuration.ts
This is a bugfix for #28.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/162)
=> Fix blank writing system in new custom field

src/angular-app/languageforge/lexicon/views/configuration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/171)
=> Check if currentField is defined before we use it

.gitattributes, installer/xenialBashWindows10.sh, test/app/chromeDirectHeadlessLFProtractorConf.js
-Force unix line endings
-Changed the install script to cancel selenium on install. and install php
-Added install of protractor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/172)
=> Install, line ending, protractor changes

src/angular-app/languageforge/lexicon/lexicon.html, src/angular-app/languageforge/lexicon/lexicon.js, src/angular-app/languageforge/lexicon/settings/rapid-word-collection.html, src/angular-app/languageforge/lexicon/settings/rapid-word-collection.js
* Added menu item Rapid Words
* Added dummy page for Rapid Words
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/178)
=> Fix: LT-18841 Add Rapid Words link to settings menu

src/Site/OAuth/OAuthBase.php
Now if we get a connection timed out on getting user details, we'll retry once. If that fails, or if anything else goes wrong, we'll redirect to the login page (with an error message that basically says "Try again, but if the problem persists, try username & password").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/182)
=> Better handling of OAuth errors including timeouts

src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.js
Latest fixes to the new comments panel
- Setup watch for to wait for a promise to resolve on the input system
- Force an new entry to save prior to adding any comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/188)
=> Latest fixes to the new comments panel

src/Api/Model/Languageforge/Lexicon/Command/LexProjectCommands.php, src/Api/Model/Shared/Mapper/JsonDecoder.php, src/Api/Model/Shared/Mapper/MongoDecoder.php, test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php
- add unit test
- fix by adding 'clone' to JsonDecoder::decodeMapOf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/202)
=> fix not persisting lexicon roleViews config

package-lock.json, package.json, src/angular-app/bellows/apps/translate/core/machine.service.ts, src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts, src/netcore-api/SIL.XForge.WebApi.Server/Services/DeltaUsxExtensions.cs, src/netcore-api/SIL.XForge.WebApi.Server/Services/DeltaUsxMapper.cs, src/netcore-api/SIL.XForge.WebApi.Server/appsettings.Development.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/214)
=> Abort long polling connections

src/netcore-api/SIL.XForge.WebApi.Server/appsettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/218)
=> Fix ShareDB URL setting for C# backend

src/Api/Library/Shared/JWTToken.php, src/Api/Model/Shared/Command/SessionCommands.php, src/Site/Listener/JWTListener.php, src/Site/OAuth/JWTSilexToken.php, src/Site/OAuth/JWTTokenAuthenticator.php, src/Site/OAuth/OAuthBase.php, src/Site/OAuth/OAuthJWTToken.php, src/Site/Provider/JWTAuthenticationProvider.php, src/index.php
This should be what's needed for the Android app, as far as I can tell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/213)
=> JWT tokens for Android app OAuth

src/netcore-api/NuGet.config, src/netcore-api/SIL.XForge.WebApi.Server/SIL.XForge.WebApi.Server.csproj, src/netcore-api/SIL.XForge.WebApi.Server/Services/ParatextService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/219)
=> Use SIL.WritingSystems to get language names from codes in PT projects

src/angular-app/bellows/apps/translate/core/machine.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/222)
=> Fix bug where translation suggestions incorrectly disappear

src/angular-app/bellows/apps/translate/new-project/views/new-project-chooser.html, src/angular-app/bellows/apps/translate/new-project/views/new-project-name.html, src/angular-app/bellows/apps/translate/new-project/views/new-project-sr-credentials.html
- deemphasize creating non-Scripture projects
- make "project name" page consistent with LF
- make width of "PT credentials" page consistent with rest of wizard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/223)
=> Fix various issues in new translation project wizard

src/releasenotes/scriptureforge.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/229)
=> Update SF release notes for 1.5

src/releasenotes/languageforge.md
Merging lf-live back into will allow the lf-live branch to be fast-forwarded again next time we release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/232)
=> Merge lf-live back into master

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/235)
=> Update Machine node module to latest

src/Api/Model/Languageforge/Lexicon/Command/SendReceiveCommands.php
- cleaned-up while investigating JIRA issue LF-77 (I posted comments on JIRA)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/233)
=> Cleanup SR commands

src/angular-app/bellows/apps/translate/core/machine.service.ts, src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/236)
=> Navigate to the selected segment when switching back from another document

deploy/dependencies.yml, deploy/developer_dependencies.yml, scripts/server/mongodb/upgrade-to-mongo-36.sh
Also includes Ansible script changes for the new Mongo 3.6 PPA. Note that the Bash script has been tested, but the Ansible script has not; the intent here is to run the Bash script, not the Ansible script, on the dev, QA and live servers for this upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/238)
=> Bash script to upgrade Mongo to 3.6

gulpfile.js, package-lock.json, package.json, src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php, src/Api/Library/Shared/Palaso/JsonRpcServer.php, src/Api/Model/Shared/Command/SessionCommands.php, src/Site/Controller/Api.php, src/Site/Controller/Base.php, src/Site/Handler/ErrorHandler.php, src/angular-app/bellows/core/api/json-rpc.service.ts, src/angular-app/bellows/core/core.module.ts, src/angular-app/bellows/core/error.service.ts, src/angular-app/bellows/core/exception-handling.service.ts, src/angular-app/bellows/core/session.service.ts, src/composer.json, src/composer.lock, src/config.php, src/index.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/227)
=> Integrate with Bugsnag

README.md, src/angular-app/bellows/core/exception-handling.service.ts, src/angular-app/bellows/core/session.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/245)
=> Fix E2E tests

src/config.php.fortest, src/config.php.live
Even I forgot this in reviewing @ermshiperete bugsnag PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/246)
=> fix E2E test files after bugsnag config.php change

src/angular-app/bellows/core/notice/notice.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/250)
=> Fix missing SF dependency

src/angular-app/bellows/apps/translate/core/translate-core.module.ts, src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts, src/angular-app/bellows/apps/translate/editor/editor.module.ts, src/angular-app/bellows/apps/translate/editor/realtime.service.ts, src/node/package-lock.json, src/node/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/253)
=> Merge sf-qa into master

src/angular-app/bellows/apps/translate/core/translate-send-receive.service.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts, src/netcore-api/SIL.XForge.WebApi.Server/SIL.XForge.WebApi.Server.csproj, src/netcore-api/SIL.XForge.WebApi.Server/Services/ParatextSendReceiveRunner.cs, src/netcore-api/SIL.XForge.WebApi.Server/Services/ParatextService.cs
- update user document order if documents are inserted or deleted
- delete ShareDB document when book deleted
- throw exceptions in `ParatextService`
- update NuGet packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/262)
=> Properly delete books during PT S/R

package-lock.json, package.json, src/angular-app/bellows/apps/translate/core/machine.service.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/264)
=> Update to latest version of Machine

package-lock.json, package.json, src/angular-app/bellows/apps/translate/core/machine.service.ts, src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/269)
=> Report error when training the translation engine

package-lock.json, package.json, src/angular-app/bellows/apps/translate/editor/editor.component.ts, src/angular-app/bellows/apps/translate/new-project/translate-new-project.controller.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/272)
=> Merge sf-live into master

README.md, deploy/playbook_xenial_server_vagrant.yml, deploy/xenial/Vagrantfile
Yesterday's changes did not fully fix everything. Today's changes:
- Install SF too, not just LF
- Fix a README typo
- Make minor improvements to the Vagrant provisioning script
- Fix two symlink issues experienced by Windows users
The hope is to have this merged in time for the developers in India to use it on Monday. Reviewers who see something that needs to be changed, feel free to make the change directly if that allows it to be merged in time for them to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/276)
=> Make corrections to the Vagrant install method

gulpfile.js, package-lock.json, src/netcore-api/.editorconfig, src/netcore-api/SIL.XForge.WebApi.Server/ExceptionLogging/BugsnagConfigurator.cs, src/netcore-api/SIL.XForge.WebApi.Server/ExceptionLogging/ExtensionMethods.cs, src/netcore-api/SIL.XForge.WebApi.Server/SIL.XForge.WebApi.Server.csproj, src/netcore-api/SIL.XForge.WebApi.Server/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/279)
=> Integrate Bugsnag to C# part of xforge

src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/286)
=> Train previous segment before translating current segment

src/Api/Model/Shared/Dto/ActivityListDto.php
Sorry for missing these problems in my PR review.
Also tidy-up on file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/290)
=> fix server 500 error on LF E2E

src/Site/views/languageforge/theme/default/sass/_global.scss, src/Site/views/languageforge/theme/default/sass/_variables.scss, src/Site/views/scriptureforge/theme/default/sass/_global.scss, src/Site/views/scriptureforge/theme/default/sass/_variables.scss, src/Site/views/shared/_global.scss, src/Site/views/shared/_variables.scss, src/angular-app/bellows/apps/public/signup/signup.scss, src/angular-app/languageforge/lexicon/editor/_editor.scss, src/angular-app/languageforge/lexicon/editor/comment/_dc-comment.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-audio.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-multioptionlist.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-picture.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-semanticdomain.scss, src/angular-app/languageforge/lexicon/new-project/new-project.scss
LF and SF both have a `_global.scss` file. There is also a default `_global.scss` file. Unfortunately there is a lot of code that is repeated verbatim. What I've tried to do is move the repeated code to the default `_global.scss`.
I suggest viewing the commits one at a time or the diff my be difficult to follow.
I've also changed some variable names and moved them around in order to reduce the amount of duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/304)
=> Merge LF and SF Sass

upload-include.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/313)
=> Ensure semantic domains data is uploaded to server

src/angular-app/languageforge/lexicon/lexicon-app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/314)
=> fix Transifex language picker

src/angular-app/languageforge/lexicon/lexicon-app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/315)
=> fix Transifex language picker again

src/Api/Model/Shared/Command/UserCommands.php, src/Api/Model/Shared/UserModel.php, src/angular-app/bellows/apps/userprofile/user-profile-app.component.html, test/php/model/shared/commands/UserCommandsTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/319)
=> Hotfix: fix writing to project user profile

src/angular-app/bellows/shared/interface-language.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/325)
=> fix interface language picker values being populated from Transifex

src/Site/views/languageforge/container/languageforge.html.twig, src/angular-app/bellows/core/navbar.controller.ts, src/angular-app/bellows/core/offline/offline-cache-utils.service.ts, src/angular-app/bellows/shared/interface-language.component.ts, test/app/languageforge/lexicon/settings/interface-language.e2e-spec.ts, test/app/languageforge/lexicon/settings/semantic-domains.e2e-spec.ts
- this improves behaviour when no project is in scope, eg login
LF E2E tests passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/327)
=> Locally store and use interface language code

src/angular-app/bellows/shared/model/send-receive-errorcodes.model.ts, src/angular-app/bellows/shared/model/send-receive-state.model.ts, src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts
Also deal with new state `SendReceiveState.Error`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/336)
=> Improve error message trying to s/r empty project

src/Api/Library/Shared/Palaso/JsonRpcServer.php, src/Site/Handler/ErrorHandler.php, src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts, test/common/MongoTestEnvironment.php, test/php/model/languageforge/lexicon/LexProjectModelTest.php, test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/341)
=>  Deal with too old or new projects when cloning 

test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php
The test in question waited a certain amount of time. However, if the
load on the build machine was too high this test failed. The previous
commit increased the wait time, but that slows down the test even
on a fast machine. This change waits for the creation of the file,
so it is as fast as possible while still waiting as long as necessary
with a timeout of 30s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/343)
=> Improve reliability and speed of a test

package-lock.json, src/Api/Model/Shared/DbIntegrityHelper.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/346)
=> Fix checkDB.php to correctly fix 'contextGuid'

src/Api/Library/Shared/Script/Migration/FixActivityUserRelated.php, src/angular-app/bellows/apps/activity/activity-container.component.ts, src/angular-app/languageforge/lexicon/core/lexicon-utility.service.ts
- reworded activity summary when a user is added to project
- add project name to activity migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/349)
=> Fix activity feed

src/Api/Model/Shared/Command/ActivityCommands.php, src/angular-app/bellows/apps/activity/activity-container.component.ts
- show activity when changes array is empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/352)
=> Fix activity feed again

src/Api/Library/Shared/Script/Migration/FixPublishInViews.php, src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts
- fix problem with `FixPublishInViews.php` migration
- mitigated in code also
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/353)
=> Fix no configuration showing

src/angular-app/languageforge/lexicon/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/354)
=> Fix updating of open activity feed on entry save

src/Site/views/languageforge/container/languageforge.html.twig, src/angular-app/languageforge/lexicon/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/355)
=> Add link to activity app into My Projects dropdown

src/Api/Library/Shared/Script/Utility/EnsureDBIndexes.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/356)
=> Add maximum php execution time to EnsureDBIndexes.php

.gitignore, src/releasenotes/languageforge.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/357)
=> Release notes for Language Forge v1.6 release

src/angular-app/languageforge/lexicon/editor/field/dc-example.component.ts, src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/361)
=> Fix deleting of Examples and Senses

src/Api/Library/Shared/Script/Migration/FixCommentGuid.php, src/angular-app/languageforge/lexicon/editor/comment/comment-bubble.component.html, src/angular-app/languageforge/lexicon/editor/comment/comment-bubble.component.ts
- abbreviation is set by the user, use the language tag
- also fix logic to match name of function 'isCommentingAvailable'
- migration script to fix existing data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/362)
=> Fix 'contextGuid' to use input system tag (not abbreviation)

test/app/scriptureforge/sfchecks/sf-checks-project-settings.e2e-spec.ts
- see PR#350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/363)
=> Fix SF E2E after allowing managers to use Communication Settings

package-lock.json, package.json, src/angular-app/bellows/apps/translate/editor/document-cache.worker.ts, src/angular-app/bellows/apps/translate/editor/editor.component.ts, src/angular-app/bellows/apps/translate/editor/realtime.service.ts, src/angular-app/bellows/core/offline/documents-offline-cache.service.ts, src/angular-app/bellows/core/offline/offline-cache.service.ts, src/angular-app/bellows/core/offline/offline.module.ts, typings/rich-text.d.ts, typings/sharedb.d.ts, typings/worker-loader.d.ts, webpack.config.js
- spawn a web worker that caches documents when project is opened
- use cache when loading documents
- update cache when documents are updated
- create typings for ShareDB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/364)
=> Pre-cache translate app documents

src/angular-app/bellows/apps/translate/core/paratext.service.ts, src/angular-app/bellows/apps/translate/core/translate-core.module.ts, src/angular-app/bellows/apps/translate/new-project/translate-new-project.controller.ts, src/angular-app/bellows/apps/translate/settings/sync.component.html, src/angular-app/bellows/apps/translate/settings/sync.component.ts
- refactor Paratext login code to a service
- add Paratext login to sync component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/365)
=> Allow user to re-enter Paratext credentials

src/angular-app/bellows/apps/translate/editor/_editor.scss, src/angular-app/bellows/apps/translate/editor/document-editor.ts, src/angular-app/bellows/apps/translate/editor/editor.component.html, src/angular-app/bellows/apps/translate/editor/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/366)
=> Indicate that a document is loading

LICENSE.txt, README.md, package-lock.json, package.json, src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.html, src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts, src/angular-app/bellows/shared/audio-recorder/audio-recorder.module.ts, src/angular-app/bellows/shared/audio-recorder/audio-recorder.scss, src/angular-app/bellows/shared/mock-upload.component.html, src/angular-app/bellows/shared/sound-player.component.html, src/angular-app/languageforge/lexicon/editor/_editor.scss, src/angular-app/languageforge/lexicon/editor/comment/_dc-comment.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-audio.scss, src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.html, src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts, src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts, src/angular-app/languageforge/lexicon/editor/field/field.module.ts, src/node/package-lock.json, test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts, test/app/languageforge/lexicon/shared/editor.page.ts, tsconfig.json, typings/lamejs.d.ts
Tested to work in Firefox and Chromium.
About 9 to 11 e2e tests failing, but they're also failing on master.
Screen shots of the UI:
&nbsp;![screenshot from 2018-07-26 15-25-23](https://user-images.githubusercontent.com/6140710/43283904-36769730-90e8-11e8-8ab0-22db1466a780.png)
&nbsp;![screenshot from 2018-07-26 15-25-33](https://user-images.githubusercontent.com/6140710/43283908-3a4bf1f2-90e8-11e8-8e5c-f4590867c0e8.png)
&nbsp;![screenshot from 2018-07-26 15-25-45](https://user-images.githubusercontent.com/6140710/43283909-3edcc278-90e8-11e8-96dd-8bc690254985.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/347)
=> Add audio recorder

src/angular-app/languageforge/lexicon/editor/editor.component.ts, src/angular-app/languageforge/lexicon/lexicon-app.module.ts
since we are unable to push our changes in existing pull request (#335) , we are creating new pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/367)
=> Fix browser back button on Language Forge lexicon page NEW

README.md
- general update of file
- fix broken links
- update submodule head
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/369)
=> Update Vagrant GUI Setup instructions

src/SIL.XForge.Scripture/ClientApp/e2e/src/app.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts
we have fixed the timeout error using "implicitly wait" and "browser wait" function.
=> fixed the timeout error for angular page

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, src/SIL.XForge.Identity/Controllers/Account/ForgotPasswordViewModel.cs, src/SIL.XForge.Identity/Controllers/Account/LoginViewModel.cs, src/SIL.XForge.Identity/SIL.XForge.Identity.csproj, src/SIL.XForge.Identity/Views/Account/ForgotPassword.cshtml, src/SIL.XForge.Identity/Views/Account/Login.cshtml, src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/SiteOptions.cs, src/SIL.XForge/SIL.XForge.csproj, src/SIL.XForge/Services/EmailService.cs, src/SIL.XForge/Services/IEmailService.cs, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
Uma and I completed following points
* Disigned ForgotPassword Page
* Added get and post methods
* Verified username/email
* Added logic for ResetPasswordKey generation
* Saved ResetPasswordKey and ResetPasswordExpirationDate
* Added method for email sending
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/375)
=> SF-42 Forgot Password

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/home/home.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/home/home.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/tslint.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/377)
=> Fix: SF-39 Change Password feature included

deploy/vagrant_xenial_gui/Vagrantfile, deploy/virtualbox_xenial_gui_creation/Vagrantfile, deploy/virtualbox_xenial_gui_creation/instructions.md
* More RAM
* Updated system packages
* Additional desktop and development settings
* Development tools
* Fix permissions.
* Additional cleanup, to ssh host keys and blanking disk.
* Add some instructions.
* Try to avoid accidentally using a slow mirror.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/378)
=> Revise vagrant

src/SIL.XForge.Scripture/appsettings.Development.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/384)
=> Correct appsettings file to allow login on development machines

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/utility.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/utility.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
* Work in progress for the notice component.
* Tests need to be added.
* Implements SF-40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/380)
=> Add Notice component and service

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/appsettings.Development.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/386)
=> Fix incorrect redirect URL when logging in with PT

src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/appsettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/387)
=> Fix name of sync jobs collection and jobs database

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, src/SIL.XForge.Identity/Controllers/Account/ResetPasswordViewModel.cs, src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
* Page disigned
* Added validation
* Saved password
* Added unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/382)
=> Fix: SF-41 Reset Password

src/SIL.XForge/Services/EmailService.cs
* Added site options in testing environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/389)
=> Fix: SF-63 Forgot password throws an error with test data Credentials

deploy/vagrant_xenial_gui/Vagrantfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/396)
=> vagrant: Add paratext 8, fix for vscode, another permission

src/SIL.XForge.Scripture/Program.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/398)
=> SF-65: Login to Paratext is throwing an error

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/399)
=> Add code docs for JSONAPIService

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.ts
* Implemented the Angular Material in the Change Password Screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/390)
=> Fix: SF-50 Use Material in Change Password component

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/notice/detail-snack-bar.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/notice/detail-snack-bar.html, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/notice/notice.component.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
* Implements a custom snack bar notice for notices with details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/393)
=> SF-57 Use Material for Notice Component

scripts/build-and-upload-beta.sh, src/SIL.XForge.Scripture/Program.cs, src/SIL.XForge/ExceptionLogging/BugsnagConfigurator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/400)
=> Add secrets config file

src/SIL.XForge.Scripture/ClientApp/src/app/core/sync-job.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/401)
=> Add type safety for model property name strings

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
To cut down on the amount of conflicts created as several developers
edit this list at once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/407)
=>  List material imports on separate lines

src/SIL.XForge.Scripture/Services/ParatextService.cs
- The PT data access API can return projects that a user is not a member of
- Get the user's role in the project from the data access API project metadata
instead of the registry API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/408)
=> Workaround for bug in PT data access API

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
* Retrive from EmailPending (mismatch the column Email and EmailPending)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/410)
=> Fix: SF-72 Email has not been sent and got an error on Sign up page

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, src/SIL.XForge.Identity/Controllers/Account/ForgotPasswordViewModel.cs, src/SIL.XForge.Identity/Controllers/Account/LoginInputModel.cs, src/SIL.XForge.Identity/Controllers/Account/RegisterViewModel.cs, src/SIL.XForge.Identity/Controllers/ValidateRecaptchaFilter.cs, src/SIL.XForge.Identity/Services/UserResourceOwnerPasswordValidator.cs, src/SIL.XForge.Identity/Views/Account/ForgotPassword.cshtml, src/SIL.XForge.Identity/Views/Account/Login.cshtml, src/SIL.XForge.Identity/Views/Account/Register.cshtml, src/SIL.XForge.Identity/wwwroot/css/site.css, src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.Testing.json, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/SiteOptions.cs, src/SIL.XForge/Models/UserEntity.cs, src/SIL.XForge/Services/EmailService.cs, src/SIL.XForge/Services/IEmailService.cs, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
- disable sending emails in development environment
- remove EmailPending and use EmailVerified instead
- fix layout of sign up page
- allow login using email address or username
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/411)
=> Fix various issues with sign up

src/SIL.XForge.Scripture/ClientApp/src/app/core/core.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject-user.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfuser.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sync-job.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project-user.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs, src/SIL.XForge/Services/XForgeDocumentBuilder.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/413)
=> Add support for including related resources in query

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
- make ResetPasswordExpirationDate self-documenting
- set ResetPasswordExpirationDate to the past on a successful reset  to prevent reuse of the emailed link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/412)
=> SF-67: Reset Password link should work only once

src/SIL.XForge/DataAccess/DataAccessExtensions.cs, src/SIL.XForge/Services/ManyToOneRelationship.cs, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs, test/SIL.XForge.Tests/Services/ResourceServiceBaseTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/422)
=> Add support for removing attributes and relationships in JSONAPI

src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml, src/SIL.XForge.Identity/wwwroot/css/site.css
Fixed the UI design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/416)
=> SF78 - UI is not properly available for "Reset Password" page

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/434)
=> Fix: SF-86 Use case insensitive check for duplicate emails

src/SIL.XForge.Scripture/Startup.cs
- fixes a problem with LetsEncrypt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/437)
=> Serve static files without extensions

src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.e2e-spec.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.po.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts
We are added 2 unit test for change password. Thank you.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/426)
=> Added 2 unit test for change password

src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml, src/SIL.XForge.Identity/wwwroot/css/site.css
Fixed: SF-70 -- Validate password strength been done
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/420)
=> SF-70 Password strength indication is not displayed on Reset Password page.

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- do not perform silent refresh in the middle of implicit flow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/445)
=> Fix exception during implicit flow log-in

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs, src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Identity/XFIdentityServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.Staging.json, src/SIL.XForge.Scripture/appsettings.Testing.json, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/SiteOptions.cs, src/SIL.XForge/Services/EmailService.cs, test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityControllerTests.cs
- refactor "log in" in IdentityController
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/446)
=> Configure origin URL instead of domain

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/450)
=> Use router to navigate to "/home" after log in

src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/fetch-data/fetch-data.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/fetch-data/fetch-data.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/custom-filter-specifier.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/get-operators.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/live-query-observable.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/store/query-operators.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/store/xforge-store.ts, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge/Services/ResourceServiceBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/451)
=> Add support for custom filters in JSONAPIService

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.html
* Changed Forgot Password to Angular
* Added unit test to test the code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/452)
=> Fix: SF-92 Convert Forgot Password to Angular

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sync-job.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/fetch-data/fetch-data.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/realtime/realtime.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/realtime/realtime.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/query-operators.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/transform-requests.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/xforge-jsonapi-source.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project-user.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/store/xforge-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/457)
=> Do not cache/persist online methods in JSONAPIService

src/SIL.XForge/DataAccess/DataAccessExtensions.cs, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/458)
=> Change username index to a partial index

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
- start implicit flow immediately when user logs in
- explicitly check for "login_required" error when attempting silent refresh
- cleanup session storage when silent refresh fails
- fix deprecation warnings when running unit tests
- fix websocket URL generation in realtime.service.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/459)
=> Code cleanup

src/SIL.XForge.Scripture/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/460)
=> Do not serve "dist" folder during development

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/464)
=> Workaround for bug when clearing hash fragment after "log in"

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-pull-fail-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-pull-store-purge-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-push-fail-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-store-sync-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/store-backup-sync-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/store-remote-query-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/store-remote-update-strategy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/468)
=> Refactor Orbit strategies into separate files

src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.ts
* Changed code to not redirect page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/469)
=> Fix: SF-99 Forgot Password should not redirect

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Identity/Models/VerifyTokenParams.cs, src/SIL.XForge.Scripture/ClientApp/src/identity/identity-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity.service.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/models/verify-token-params.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
* Changed Reset Password to Angular
* Added unit tests to test the code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/461)
=> Fix: SF-93 Convert Reset Password to Angular

src/SIL.XForge/DataAccess/MongoRepository.cs
- not aggregate exception as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/471)
=> Fix exception on invite existing user

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/query-operators.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-pull-fail-strategy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/472)
=> Fix exception when getting a non-existent resource

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/473)
=> SF-109: Fix responsive design for projects component

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Identity/Models/SignUpParams.cs, src/SIL.XForge.Identity/Models/SignUpResult.cs, src/SIL.XForge.Identity/Models/VerifyRecaptchaParams.cs, src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/identity.service.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/models/sign-up-params.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/models/sign-up-result.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/models/verify-recaptcha-params.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.html, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts, src/SIL.XForge.Scripture/Views/Shared/Index.cshtml, test/SIL.XForge.Identity.Tests/Controllers/IdentityControllerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/463)
=> SF-91 Convert Sign up page to Angular

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Identity/Views/Account/Login.cshtml, src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/476)
=> Copy external login endpoints to IdentityController

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/486)
=> SF-110: Updated role is not displayed correctly when paging

.prettierignore, README.md, src/SIL.XForge.Scripture/ClientApp/.prettierignore, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/forgot-password/forgot-password.component.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.ts, src/SIL.XForge.Scripture/ClientApp/src/styles.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice/detail-snack-bar.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.html, src/SIL.XForge.Scripture/ClientApp/tslint.json
- don't always --write
- also check .yml files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/491)
=> SF-58: Prepare Prettier for CI builds

src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.scss
* Fixed the view port display issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/488)
=> Fix: SF-116 Sign Up page does not display correctly

src/SIL.XForge.Identity/Controllers/IdentityController.cs, src/SIL.XForge.Scripture/ClientApp/angular.json, src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.html, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.html, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.scss, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/504)
=> Update log-in and sign-up components to MDC Web

src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
I am ready for this PR to be merged when approved (and once its parent is approved and merged), although it may need its merge target changed to sf-develop (depending on what happens when the current target is merged).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/503)
=> SF-52 My Account: Validation for presence of username, email

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge.Scripture/Controllers/ParatextController.cs, src/SIL.XForge.Scripture/Services/IParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Tests/Services/TestUserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/490)
=> SF-60 Add delete account option in account details

src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts, src/SIL.XForge/Models/Entity.cs, src/SIL.XForge/Models/Resource.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/508)
=> SF-52 My Account: contactMethod disabling

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
- consistent use of avatar
The `user` attribute should probably take an observable so that its data is updated easily, however this will do for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/510)
=> Add avatar component

deploy/virtualbox_xenial_gui_creation/instructions.md, src/SIL.XForge.Scripture/ClientApp/e2e/protractor.conf.js, src/SIL.XForge.Scripture/ClientApp/e2e/src/app.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, src/SIL.XForge.Scripture/appsettings.Testing.json, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/511)
=> Fix E2E test environment

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
- fix console errors when avatar user null/undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/512)
=> Fix avatar user null/undefined

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
- add implicit paragraphs when there are top-level verses
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/517)
=> SF-89: Scripture not displayed in Realtime component

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.ts
* password only gets updated when user changes it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/522)
=> Fix: SF-62 Add unit tests to User Entry component

src/SIL.XForge.Scripture/ClientApp/src/app/realtime/realtime.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/site.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts, src/SIL.XForge.Scripture/Services/SFJsonApiServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Services/SFUserService.cs, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, src/SIL.XForge/DataAccess/SiteDomainSerializer.cs, src/SIL.XForge/Models/Site.cs, src/SIL.XForge/Models/UserEntity.cs, src/SIL.XForge/Models/UserResource.cs, src/SIL.XForge/Services/JsonApiServiceCollectionExtensions.cs, src/SIL.XForge/Services/ServicesExtensions.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectUserServiceTests.cs, test/SIL.XForge.Scripture.Tests/Services/SFUserServiceTests.cs, test/SIL.XForge.Tests/Services/ResourceServiceBaseTests.cs, test/SIL.XForge.Tests/Services/ResourceServiceTestEnvironmentBase.cs, test/SIL.XForge.Tests/Services/TestUserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
- realtime: save and read current project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/524)
=> SF-103 Add site (project context) to user

src/SIL.XForge.Identity/Controllers/IdentityRpcController.cs, src/SIL.XForge.Identity/Services/UserResourceOwnerPasswordValidator.cs, src/SIL.XForge/DataAccess/DataAccessExtensions.cs, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, src/SIL.XForge/DataAccess/DictionaryKeySerializer.cs, src/SIL.XForge/DataAccess/IUpdateBuilder.cs, src/SIL.XForge/DataAccess/MongoUpdateBuilder.cs, src/SIL.XForge/Models/UserEntity.cs, src/SIL.XForge/Models/UserResource.cs, src/SIL.XForge/Services/JsonApiServiceCollectionExtensions.cs, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs, src/SIL.XForge/Services/ServicesExtensions.cs, src/SIL.XForge/Services/UserProfile.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs, test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilder.cs, test/SIL.XForge.Tests/Services/ResourceServiceTestEnvironmentBase.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/525)
=> SF-170: Add support for updating dictionaries on entities

src/SIL.XForge.Scripture/ClientApp/e2e/src/app.e2e-spec.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.html
* Update the E2E tests to use the new Angular Login page.
* Add a test that checks that a user can login by pressing the Enter key (rather than the Login button)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/513)
=> WIP: e2e-test for login page.

src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/verify-email/verify-email.component.ts
I'm not sure about how I pulled IdentityService into app.component.ts. But without that I get an injection error saying that IdentityService can't be provided.
It may be difficult to see right away in the diff, but I changed the emailPattern regex slightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/527)
=> SF-52 My Account: Validate email

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
- add Avatar component unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/529)
=> Fix avatar console errors

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/528)
=> SF-128 Get user administration to display correctly

src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/delete-account-dialog/delete-account-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts
This will be easier to review here, and in history, if kept in separate commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/531)
=> My Account + Delete: Layout, Cancel button, Tests, Labels, Hide username

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-api.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/533)
=> SF-175: Pessimistic operations stop working after offline execution

src/SIL.XForge.Scripture/ClientApp/src/identity/identity-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/redirect-home.guard.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/534)
=> SF-162 Get identity pages to logout or redirect home

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-api.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge/Services/JsonApiServiceCollectionExtensions.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/539)
=> Share current user observable between components 

src/SIL.XForge/Models/UserEntity.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs
* Fix login page unresponsive after login failure due to null or empty password
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/538)
=> SF-177 fix login unresponsive

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/535)
=> SF-123 Enhance change password page error handling, refactor

NuGet.config, src/SIL.XForge.Scripture/Configuration/SFConfigurationServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Configuration/SyncOptions.cs, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/XForgeRichText.cs, src/SIL.XForge.Scripture/Services/XForgeScriptureText.cs, src/SIL.XForge.Scripture/Services/XForgeTextCorpusFactory.cs, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/SiteOptions.cs, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, src/SIL.XForge/SIL.XForge.csproj, src/SIL.XForge/Services/JsonRpcServiceCollectionExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/541)
=> Add machine API

src/Api/Model/Shared/Command/UserCommands.php, src/Api/Model/Shared/PasswordModel.php, test/php/model/shared/commands/UserCommandsTest.php
* bug: signup with google, logout, signup takes account
* add regression test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/542)
=> fix signup bug

src/Api/Model/Shared/Command/UserCommands.php
* remove redundant code now we have a migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/546)
=> fix signup bug completely 2

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
- Includes dynamic population of questions (dummy data only)
- Status of questions
- Answers per question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/544)
=> Feature SF-140

deploy/virtualbox_xenial_gui_creation/Vagrantfile
This dependency has recently been added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/549)
=> update Vagrantfile to include /var/lib/xforge

src/SIL.XForge.Scripture/ClientApp/e2e/src/app.e2e-spec.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/app.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.e2e-spec.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/my-account.po.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.html
I made some file changes to the angular design for e2e change-password. Now, all test scenarios are passing with new changes. I have added "my-account.po.ts" file for this commit because of change password button moved the home page into my account page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/530)
=> SF-134: e2e test for change password

src/SIL.XForge.Scripture/ClientApp/e2e/src/change-password.po.ts, src/SIL.XForge.Scripture/ClientApp/e2e/src/login.po.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/scripture/canon.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/scripture/scr-vers.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/scripture/verse-ref.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sync-job.ts, src/SIL.XForge.Scripture/ClientApp/src/app/fetch-data/fetch-data.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-rpc.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/xforge-jsonapi-source.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/projects/projects.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge.Scripture/ClientApp/tslint.json
* improve tslint rule and fix files
* note it currently ignores getters and setters. Place these below the constructor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/558)
=> Improve ng lint class member order

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/556)
=> Fix: SF-176 Sys Admin cannot update password

README.md, src/SIL.XForge.Scripture/ClientApp/monitor-test-headless.sh, src/SIL.XForge.Scripture/ClientApp/test-headless.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/560)
=> Add test runner script

src/SIL.XForge/DataAccess/DataAccessExtensions.cs, src/SIL.XForge/DataAccess/IUpdateBuilder.cs, src/SIL.XForge/DataAccess/MongoUpdateBuilder.cs, src/SIL.XForge/Services/OneToManyRelationship.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Services/ProjectUserService.cs, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs, src/SIL.XForge/Services/UserService.cs, src/SIL.XForge/Utils/ExpressionHelper.cs, src/SIL.XForge/Utils/FieldExpressionFlattener.cs, src/SIL.XForge/Utils/ParameterRebinder.cs, test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilder.cs
- use expressions for IUpdateBuilder
- expressions make it possible to cast project user base class to
concrete class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/561)
=> Fix bug when updating a project user

src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.ts
(by switching from snackbar to noticeservice)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/563)
=> SF-132 Make reset password error disappear

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.ts
The unit tests should probably be looked at afresh rather than only trying as a diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/553)
=> Convert Change Password component to MDC

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/574)
=> Add Unit Test Debugging instructions to README

src/SIL.XForge/Services/RepositoryResourceServiceBase.cs
embed inner exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/575)
=> SF-61: Admin User Details

src/SIL.XForge.Identity/Controllers/IdentityRpcController.cs, src/SIL.XForge.Identity/Services/ExternalAuthenticationService.cs, src/SIL.XForge/Controllers/ProjectsRpcController.cs, src/SIL.XForge/DataAccess/DuplicateKeyException.cs, src/SIL.XForge/DataAccess/IRepository.cs, src/SIL.XForge/DataAccess/MongoRepository.cs, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs, test/SIL.XForge.Tests/DataAccess/MemoryRepository.cs, test/SIL.XForge.Tests/Services/ResourceServiceBaseTests.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/578)
=> Add DuplicateKeyException to data access layer

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- top app bar icons cannot be list items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/582)
=> Fix error when clicking on top app bar icons

src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/583)
=> Fix Settings and Sync not showing for non-Project Administrators

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html
* more MDC conversion
* change text
* remove extra divider in Nav when checking disabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/586)
=> Tidy-up Project Settings and Nav

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/models/mock-realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/Services/TextService.cs, test/SIL.XForge.Scripture.Tests/Services/TextServiceTests.cs
* show loading progress bar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/588)
=> SF-209 cleanup questions

src/SIL.XForge.Scripture/ClientApp/src/global.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
- use a key in "connectedDataMap" that supports strict equality
- set angular-split gutter background image to "none" when disabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/597)
=> Fix console errors

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/comment.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/comment-data.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/comment.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/verse-ref-data.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/text.service.ts, src/SIL.XForge.Scripture/ClientApp/src/typings/ot-json0.d.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/json-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-store-sync-strategy.ts, src/SIL.XForge.Scripture/Models/TextEntity.cs, src/SIL.XForge.Scripture/Services/TextService.cs, test/SIL.XForge.Scripture.Tests/Services/TextServiceTests.cs
* change to chapter resolution (from book)
* Answers are an array in each question
* Comments are in there own doc like questions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/596)
=> SF-219 Add Answers and Comments

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.spec.ts, src/SIL.XForge/Models/UserEntity.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/598)
=> SF-178: Ensure Email is default contact method

README.md, src/SIL.XForge.Scripture/ClientApp/monitor-test-headless.sh, src/SIL.XForge.Scripture/ClientApp/test-headless.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/600)
=> Add filtering to test runner

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/machine-http-client.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/602)
=> Keep access token up-to-date for machine API

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/delete-account-dialog/delete-account-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/delete-account-dialog/delete-account-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/delete-account-dialog/delete-account-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/delete-account-dialog/delete-account-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.ts
TODO: fix tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/589)
=> WIP: SF-178: Convert delete-account dlg to MDC

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/translate-metrics.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/ClientApp/src/styles.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/orbit-service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Models/TranslateConfig.cs, src/SIL.XForge.Scripture/Models/TranslateMetrics.cs, src/SIL.XForge/Controllers/ProjectsRpcController.cs, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, src/SIL.XForge/Services/XFRpcHttpRouter.cs, test/SIL.XForge.Tests/Controllers/ProjectsRpcControllerTests.cs, test/SIL.XForge.Tests/Controllers/TestProjectsRpcController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/601)
=> Add metrics collection to translate task

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-settings/project-settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SyncJobService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectUserServiceTests.cs
* add translate settings to project settings
* backend side-effect to change Paratext project
* add write status component
* re-tick if at least one task is not ticked and persist error message
* refactor layout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/606)
=> SF-211 Translate Settings

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/615)
=> Change machine database name

src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
SF-229 will benefit from a similar fix in project.component.ts, but here is the first part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/611)
=> SF-229 Accommodate data in-progress

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-data.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/610)
=> Add translate overview page

src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts
Lest it be blank.
I am not excited about this approach. I am all ears for a better idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/616)
=> SF-229 Delay building selection list until have required data

src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
* improve reliability of TC unit tests (and any other headless test runners).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/619)
=> TC fix for disconnected browser

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/620)
=> SF-237: Sync fails when source has more chapters than target

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-api.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/query-operators.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/orbit-service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-pull-fail-strategy.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-pull-fail-strategy.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-push-fail-strategy.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/strategies/remote-push-fail-strategy.ts, src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/621)
=> Properly handle project deletion when no project selected

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/625)
=> SF-234 Add log in to Paratext button

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/verify-email/verify-email.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/delete-account-dialog/delete-account-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/627)
=> Remove all compileComponents() calls in unit tests

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-data.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-api.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/626)
=> SF-235: Add ability to start training

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/translate-metrics.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/Models/TranslateMetrics.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/628)
=> Add text ID and chapter to translate metrics

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/translate-metrics.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/Models/TranslateMetrics.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/631)
=> Only train a segment when it exceeds a length threshold

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.ts
* move At Least One validator from settings component and make generic
* fix placeholder and value showing together in select (value must be string; not object)
This should be merged with a merge commit to retain SF-213 (RL) and SF-231 (IH) commits. Please refer to the code review already done on SF-213 (#624).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/632)
=> Bug/SF-231 Ensure at least one task on connect

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/624)
=> Convert Connect to Paratext to MDC

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/translate-metrics.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/Models/TranslateMetrics.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/633)
=> Add edit end event property to translate metrics

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/635)
=> Only trained aligned part of source segment

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/636)
=> Fix deployment issue with Machine

README.md
Formatting changes were automatic from tools.
---
I've found the branch descriptions to be confusing, and so I've sought here to word it more plainly. 
I also styled branch names here as `symbols` rather than **UI elements**, since I understand them more that way, but that needn't be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/638)
=> README: Add Debugging info, clarify wording

src/SIL.XForge.Scripture/ClientApp/src/identity/reset-password/reset-password.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/623)
=> Tidy, moving TestEnvironment down.

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/642)
=> SF-248: Crash when approving a session with no results

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/640)
=> Allow words to break to prevent scripture editor growing

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/644)
=> SF-249: Disable SHIFT-Enter and variants in text

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs, src/SIL.XForge.Scripture/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/643)
=> Add access control for Machine API

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFJsonApiServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SyncJobManager.cs, src/SIL.XForge.Scripture/Services/SyncJobService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectUserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/648)
=> SF-243: Switch to using native select on "connect project" view

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.ts
- ensure that the segment format is updated when editing
- do not use flexbox to set height of texts (too slow when editing)
- set position of suggestions when shown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/649)
=> Fix various bugs in the editor component

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestion.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/650)
=> Insert suggestion when ENTER is pressed

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/652)
=> Remove npm vulnerabilities

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/Models/TranslateProjectUserConfig.cs, src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/SFBuildHandler.cs, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge/DataAccess/ArrayPosition.cs, src/SIL.XForge/DataAccess/IUpdateBuilder.cs, src/SIL.XForge/DataAccess/MongoUpdateBuilder.cs, src/SIL.XForge/DataAccess/XFFieldDefinition.cs, src/SIL.XForge/Services/ProjectUserService.cs, src/SIL.XForge/Services/ResourceServiceBase.cs, src/SIL.XForge/Services/UserService.cs, src/SIL.XForge/Utils/ConstantFinder.cs, src/SIL.XForge/Utils/ExpressionHelper.cs, src/SIL.XForge/Utils/FieldExpressionFlattener.cs, test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilder.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/654)
=> Clear segment checksum when training completed

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/655)
=> Fix suggestions horizontally overflowing window

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html
* Also prevent distorted chapter nav display in checking
* component on mobile viewports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/656)
=> SF-244 Get chapter nav options to display on single line

src/Api/Library/Shared/Script/Migration/FixCommentGuid.php
This migration takes comments with a redundant context guid:
```
sense#05f3fb35-e855-47fc-bef7-478f2a7c6dae example#dc996a25-9eab-4684-8fdc-ddadc2e49a5e sentence.en.en
```
and removes one of the language tags:
```
sense#05f3fb35-e855-47fc-bef7-478f2a7c6dae example#dc996a25-9eab-4684-8fdc-ddadc2e49a5e sentence.en
```
I based it off of an existing migration that changed the context guids to use the language tag rather than the language abbreviation.
The reason I added on to another migration is because they use a lot of the same boilerplate, and they're both idempotent. It was an easy way of making sure this was going to work without reimplementing a lot of stuff again. It also makes it easier for reviewers to see exactly what I've added. I'm guessing I should split this out into its own …
=> Add migration to fix double language tags on comment context guid (LFv1)

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/668)
=> SF-238: Sync fails on community checking project

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/typings.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/669)
=> SF-260, SF-268: Fix paste and undo in text

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/671)
=> SF-250: Hang when clicking My Projects

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
- also fixes SF-269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/672)
=> SF-274: Drawer does not show on first login

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segmenter.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-segmenter.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss, src/SIL.XForge.Scripture/ClientApp/src/typings.d.ts, src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- make inline embeds unselectable
- disable pasting HTML
- properly handle USX poetry markers
- add styles for more USX markers
- display caller value in notes
- allow text component to deal with an unknown segment refs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/673)
=> SF-260: Possible to copy/paste inline embeds

src/SIL.XForge.Scripture/ClientApp/src/_variables.scss, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/nav-menu/nav-menu.component.ts, src/SIL.XForge.Scripture/ClientApp/src/index.html, src/SIL.XForge.Scripture/ClientApp/src/styles.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/675)
=> SF-254: Fix scrolling in drawer

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/676)
=> SF-270: No margin when wrapping on translate overview

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/677)
=> SF-272: Suggestion confidence cut off on mobile

src/SIL.XForge.Scripture/ClientApp/src/styles.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/678)
=> SF-215: Project select overflowing when too long

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/682)
=> Add instructions to setup development vagrant

src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/684)
=> SF-277: Translate does not load on first connect

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/659)
=> SF-256 Tell user to register a PT project on connect project page

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/686)
=> SF-284, SF-285: Console error when switching projects in mobile

src/SIL.XForge.Scripture/AssemblyInfo.cs, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-data.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segmenter.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-data.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-offline-store.ts, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge/Services/CommonServiceCollectionExtensions.cs, src/SIL.XForge/Services/FileSystemService.cs, src/SIL.XForge/Services/IFileSystemService.cs, src/ShareDB/Connection.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, test/SIL.XForge.Tests/DataAccess/MemoryRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/660)
=> SF-233 Handle changing mother translation

package-lock.json, package.json, src/angular-app/bellows/polyfills.browser.ts
This hasn't been tested vigorously, but both LF and SF appear to work just fine after this is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/692)
=> Remove Zone.js

gulpfile.js
* fix build after move to AWS where deprecated authprogs permissions have been removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/694)
=> Remove CAT build in gulp

src/angular-app/bellows/core/offline/editor-data.service.ts
Fixes LF-274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/699)
=> Always return a value in processEditorDto

deploy/developer_dependencies.yml, installer/ubuntu1604Installer.sh
Just added an npm install before refreshDeps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/703)
=> Fix installer

deploy/dependencies.yml, deploy/developer_dependencies.yml, installer/ubuntu1604Installer.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/702)
=> Install Script: Fixes install of Mongo

.github/FUNDING.yml
Add Give Direct funding URL https://www.givedirect.org/donate/?cid=13536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/709)
=> Create FUNDING.yml to enable Sponsor button

.github/FUNDING.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/710)
=> update URL for Language Software designation

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/713)
=> Updates Protractor to 5.4.2

installer/ubuntu1604Installer.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/714)
=> Ubuntu install script sets group write permissions on src/assets

package-lock.json, package.json, src/Site/views/shared/container/container.html.twig, src/angular-app/bellows/apps/projects/projects-app.component.ts, src/angular-app/bellows/apps/projects/projects-app.module.ts, src/angular-app/bellows/apps/usermanagement/user-management-app.component.ts, src/angular-app/bellows/core/helphero.service.ts, src/angular-app/languageforge/lexicon/core/lexicon-core.module.ts, src/angular-app/languageforge/lexicon/editor/editor.component.ts, src/angular-app/languageforge/lexicon/lexicon-app.component.ts, src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/708)
=> Implements JS/TS support for LF HelpHero tours

src/angular-app/bellows/core/notice/notice.component.html, src/angular-app/bellows/shared/list-view.component.ts, src/angular-app/languageforge/lexicon/lexicon-app.component.ts, test/app/bellows/shared/login.page.ts, test/app/bellows/shared/utils.ts, test/app/bellows/user-profile.e2e-spec.ts, test/app/languageforge/lexicon-traversal.e2e-spec.ts, test/app/languageforge/lexicon/shared/editor.util.ts
Instructions for running e2e tests can be found in the [README](https://github.com/sillsdev/web-languageforge). The full set of commands needs to run in order to run the tests. This is known only to work on Ubuntu 16.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/718)
=> Enables reliable E2E testing on Ubuntu 16.04

gulpfile.js, package-lock.json, package.json, test/app/browserstackConf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/719)
=> Basic framework to implement BrowserStack with TeamCity

.gitmodules, README.md, deploy/playbook_bionic.yml
Also fixed some permissions in the ansible script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/722)
=> Update readme to reflect installer

src/Api/Library/Shared/SilexSessionHelper.php, src/Site/Controller/App.php, src/Site/Controller/Auth.php, src/Site/Controller/Base.php, src/Site/Controller/Page.php
When attempting to access a project without permissions, a user is redirected to the projects page with an error message while an admin is added as a manager to the project and continues. Also addressed some cases of the `UserUnauthorizedException` and redirecting from within the `App` Controller.
As a note, the error message with likely want to be relocated. Feedback as to where is appreciated. Also if there is a way to use the angular errors, those might be preferred, but I have yet to attempt such integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/720)
=> Fixes crash on accessing a project without membership

.vscode/settings.json
This adds the proper configuration for running PHPUnit inside VSCode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/733)
=> add VSCode PHPUnit configuration

deploy/playbook_bionic.yml, deploy/vars/config_developer.yml
The project currently uses node 8.11.4 and npm 6.4.1, which are several years old.
I have updated the Ansible install script to install node LTS 10.16.0 and npm 6.10.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/732)
=> Update node and npm to LTS in Ansible install script

README.md, deploy/playbook_bionic.yml, deploy/vars/config_developer.yml
* tested on Linux Mint 19
* update node and npm versions (as used on TC agent)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/790)
=> Fix Ansible deploy for other Bionic-based distros

deploy/playbook_bionic.yml, deploy/vars/config_developer.yml
- force PHP version 7.3
- install base package which was missing (not sure why)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/813)
=> Fix various issues with ansible install script

package-lock.json, package.json, src/angular-app/bellows/core/offline/editor-data.service.ts, src/angular-app/bellows/shared/model/ldapi.model.ts, src/angular-app/scriptureforge/sfchecks/shared/sil-selection.directive.ts, tsconfig.json
I think this will fix the compile errors on master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/834)
=> Try to fix up Typescript errors

docker/docker-compose.yml
this was a copy/paste error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/838)
=> fix dist folder path

docker/Makefile, docker/api/Dockerfile, docker/docker-compose.yml, docker/e2e-api/Dockerfile, docker/e2e-api/run.sh, docker/e2e-ui/Dockerfile, docker/e2e-ui/run.sh, docker/test-api/run.sh, docker/wait/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/839)
=> DRY wait orchestration

docker/api/Dockerfile, docker/e2e-api/Dockerfile, docker/e2e-ui/Dockerfile, docker/ui/Dockerfile
I optimized these four Dockerfiles with some best practices to move things farther up that are unlikely to change (like npm dependencies) and move copying in src or test directories as far down as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/850)
=> optimize Dockerfiles

package-lock.json, package.json
Upgrade jquery due to vulnerabilities indicated in advisory. Cross-Site Scripting - https://npmjs.com/advisories/1518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/862)
=> Upgrade jquery from 3.4.1 to 3.6.0

docker/docker-compose.yml, docker/ld-api/Dockerfile, docker/ld-api/ld.env, docker/ld-sql/Dockerfile, docker/ld-sql/testlanguagedepot.sql, src/Api/Service/Ldapi.php
<del>WIP. At the moment these Docker images will build correctly, but I don't yet have the right infrastructure in place to have the Language Forge images talk to them. I want to create a hosts entry in the lf-api container that will tell it that "admin.languagedepot.org" is the ld-api container, and have lf-api trust the certificate (generated by Caddy?) that ld-api will return. Once that's in place, this will be ready to merge.</del>
**Update:** Now working and ready for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/831)
=> Add Docker images for Language Depot API

docker/docker-compose.yml
Missed a commit in #831 that addressed review comments regarding the docker-compose.yml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/867)
=> Address review comments missed in #831

README.md, docker/Makefile, docker/api/Dockerfile, docker/db-reset/Dockerfile, docker/db-reset/run.sh, docker/docker-compose.yml, docker/ui/Dockerfile
This is some initial refactoring needed in preparation for a deployable app
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/872)
=> Chore/refactor UI image

docker/e2e-ui/run.sh, docker/ui/Dockerfile, gulpfile.js
Updated ui/Dockerfile to upgrade nodejs and npm versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/874)
=> Upgrade to node:14-alpine and npm@7.6.3

src/config.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/904)
=> don't think this is being used anymore

docker/ld-api/Dockerfile
This is a quick-and-dirty fix rather than a proper fix, meant to get the build up and working while I investigate the actual cause and put together a proper fix for the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/905)
=> Fix failing ld-api docker build

docker/docker-compose.yml, src/Site/Controller/Auth.php, src/composer.json, src/composer.lock, src/config.php, src/index.php, test/php/TestConfig.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/902)
=> establish new env var usage approach

src/config.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/903)
=> don't think this is used anymore

docker/ui-builder/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/915)
=> ui-builder was rebuilding when backend files were changed

docker/docker-compose.yml, src/Site/OAuth/FacebookOAuth.php, src/Site/OAuth/GoogleOAuth.php, src/config.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/909)
=> migrate oauth env var usage

src/Site/Controller/App.php, src/Site/Controller/Base.php, src/config.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/912)
=> no need for env var anymore

docker/docker-compose.yml, src/config.php, src/index.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/910)
=> migrate remember me env var usage

docker/Makefile, docker/docker-compose.yml, src/config.php, test/php/TestConfig.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/913)
=> migrate ldapi token to new env usage

docker/ui-builder/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/916)
=> empty args are handled differently than I thought

src/Site/Controller/Base.php, src/config.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/911)
=> not sure why it'd be valuable to have this flexibility.

.vscode/launch.json, src/angular-app/languageforge/main.ts, src/angular-app/main.ts, tsconfig.json, webpack.config.js
Needed to make changes to the structure of the angularjs app to allow vscode debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/921)
=> Restructured angular app to allow vscode debugging

test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.ts
One E2E test is failing intermittently with some kind of race condition. This might fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/932)
=> Try to fix intermittent E2E failure

docker/deployment/app-deployment.yaml, docker/deployment/db-deployment.yaml
We need to have more space for MongoDB data and indexes
Also fixes up a domain reference
=> upgrade db persistent vol claim to 16GB

docker/deployment/db-deployment.yaml
another necessary modification for the service spec
=> set db clusterIP:None

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
This checks in the folder that I forgot to include in #984.
=> Fix E2E test debugging

docker/deployment/app-deployment.yaml, docker/deployment/db-deployment.yaml
These settings are some finalizations to the config's at this point.
=> K8s tweaks for staging

src/Site/Controller/App.php
This is a bit of unused-code removal that should have gone into https://github.com/sillsdev/web-languageforge/pull/1021.
=> Remove one more bit of unused code

docker/Makefile, docker/app/Dockerfile, webpack-legacy.config.js
these were accidentally missed in #1040
=> removed bugsnag refs

docker/deployment/scripts/kubeRsyncSendReceive.sh
This change should have made it in with the original PR but didn't.
=> address review comments

src/Site/views/languageforge/container/languageforge.html.twig, src/Site/views/languageforge/theme/default/sass/_global.scss
some changes per the instructions of the issue #993
Unfortunately, I was not able to run E2E tests nor unit tests
=> Move "settings" Cog to a more visible and understandable location in the menu (issue #993)

README.md, docker/deployment/Makefile, docker/deployment/app-deployment.yaml
This will piggy-back off the work going on in #1066 to utilize unique versioning of the app.
=> Parameterized docker image version for deployment

README.md, docker/deployment/app-deployment.yaml, docker/deployment/db-deployment.yaml
additionally, I expanded the volumes in preparation for prod data
=> Documented Backup/Restore process & expand volumes for prod data

src/Site/views/shared/_global.scss
#1020
Configuration view has unnecessary horizontal scrollbar. Added styles to #app-container
=> Remove unnecessary horizontal scrollbar in configuration view

docker/deployment/Makefile
change beta.languageforge.org to languageforge.org in the Makefile
TODO:
fixes #1107
=> update deployment Makefile with production website

src/releasenotes/languageforge.md
=> 1.8 Release Notes

.github/pull_request_template.md
Remove the checkboxes and keep them as bullet points so that they don't show up as "tasks" in the PR card.
=> Remove checkboxes from "Type of Change" in PR template

src/Site/views/languageforge/theme/default/page/home/index.html.twig
Add the phrase "see recent improvements" under the "Help Improve Language Forge" at @alex-larkin's request.
Fixes #1148
=> Tweak sentence on front page

src/angular-app/languageforge/lexicon/editor/_editor.scss, src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss, src/angular-app/languageforge/lexicon/editor/editor-entry.view.html, src/angular-app/languageforge/lexicon/editor/editor.component.html, src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss, src/angular-app/languageforge/lexicon/editor/field/dc-rendered.component.html, src/releasenotes/languageforge.md
Users are seeing some whitespace in the app that is preventing them from getting to certain fields at the bottom of the app.
Fixes an untracked issue, however this work is related to a number of issues that can be found in #1143
Screenshots supplied below with appropriate tests.
I confirmed the correct codebase was in staging: https://github.com/sillsdev/web-languageforge/runs/3629842410
=> Remove some extra whitespace that is making the app hard to use

src/Site/Controller/Redirect.php
=> Fix PHP warning in Redirect controller

src/Site/OAuth/OAuthBase.php
This updates the `$user->last_login` timestamp for OAuth logins.  This fixes a bug where the `last_login` field is not updated for users who choose to login via Google or FB login.
I also changed the name of the method to `doSilexLogin()` to make it more clear that this is a login success handler.
The "Last Login" field in the user profile view will now be updated when users login via OAuth
This change cannot be tested on a local developer machine.  We must wait for this to land on qa.languageforge.org
=> update $user->last_login on OAuth login

src/angular-app/languageforge/lexicon/editor/_editor.scss, src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss, src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts
Fixes #1190 and #1172
I verified this in staging and it looked good
=> Release 1.9.1

package-lock.json, package.json, webpack.config.js
I came across some old livereload deps that aren't used anymore.
- cleaning up repo
N/A
=> cleaned up some old livereload remnants

src/angular-app/languageforge/lexicon/editor/editor.component.ts
Fixes #1133 
See #1261 
See #1261
=> Release 1.11.1

.github/workflows/build-and-deploy-images.yml, README.md
These changes are in response to a retrospective item about streamlining out change management processes for LF.
- Engineering
N/A
This will be tested in practice since it's mostly about our manual processes but changes will still need to be made to the TC deployment job once this gets merged into `develop`.
=> Move to a 2-branch model

README.md
Readme update.
Fixes # (issue)
- Documentation
No source code changes.
=> Added blurb to VS Code section for Windows/WSL users

.github/workflows/integrate-and-deploy.yml, .github/workflows/production.yml, docker/Makefile
Some issues were noticed in the latest release, details found in issue #1301 
Fixes #1301 
N/A
These changes were straightforward so I think it's safe to watch them on the next release rather than setting up a temporary testing environment for mock deployments.
=> Production deployment tweaks

.github/workflows/pull-request.yml, playwright.config.ts, test/e2e/example.spec.ts, test/e2e/pages/activity.page.ts, test/e2e/pages/change-password.page.ts, test/e2e/pages/forgot-password.page.ts, test/e2e/pages/login.page.ts, test/e2e/pages/projects.page.ts, test/e2e/pages/signup.page.ts, test/e2e/pages/site-admin.page.ts, test/e2e/pages/user-profile.page.ts, test/e2e/site-traversal.spec.ts, test/e2e/testConstants.json, test/e2e/utils/TestControl.php, test/e2e/utils/fixtures.ts, test/e2e/utils/globalSetup.ts, test/e2e/utils/login.ts, test/e2e/utils/testControl.ts
The following tests have been converted to playwright
Bellows E2E Page Traversal
✓ Explore signup page
✓ Explore forgot password page
✓ Explore login page
✓ Explore change password page
✓ Explore activity page
✓ Explore project page
✓ Explore site admin page
✓ Explore user profile page
For details/remarks regarding converting the above tests, refer to the spreadsheet; https://docs.google.com/spreadsheets/d/1w9wjfm-02QHLhv0ObPAKKlqnDWeag379GIXwOcRU4W0/edit#gid=0
Fixes #1333 
- E2E test
=> Site traversal playwright tests

docker/deployment/app-deployment.yaml, docker/docker-compose.yml
Docker-compose and Kubernetes setups for creating a separate lfmerge container.
Docker-compose setup has been tested. Kubernetes setup is still undergoing testing.
=> Run lfmerge in separate container

.github/workflows/build-and-publish-next.yml, .github/workflows/integrate-and-deploy.yml, .github/workflows/production.yml, .github/workflows/staging.yml, .vscode/extensions.json, docker/Makefile, docker/deployment/Makefile, docker/docker-compose.yml, docs/DEVELOPER.md, next-app/README-Tech.md, next-app/README.md, next-app/jsconfig.json, next-app/package-lock.json, next-app/package.json, next-app/src/lib/Header.svelte, next-app/src/lib/PageHeader.svelte, next-app/src/lib/error/Error.svelte, next-app/src/lib/error/index.js, next-app/src/lib/fetch/server.js, next-app/src/lib/forms/Button.svelte, next-app/src/lib/forms/Form.svelte, next-app/src/lib/forms/Input.svelte, next-app/src/lib/progress/Progress.svelte, next-app/src/routes/__layout.svelte, next-app/src/routes/password/change.svelte, next-app/src/routes/password/changed.svelte, next-app/src/routes/password/index.json.js, next-app/svelte.config.js, next-app/tailwind.config.cjs
This PR introduces a brand new infrastructure and architecture to the LF app.  It enables a capability by capability migration from the existing Angularjs impl to a modern stack in Svelte and Sveltekit.
Fixes #1309 
1. Log in to the app
1. Choose to change your password
1. Walk through the change password pages
1. Attempt to log back in with a new, different password
1. take note of current images in prod
1. merge to `master`
1. set kube context to `prod` from local machine
1. `make delete` from `deployment` dir
1. cut the release
1. monitor the "Deploy to production" action
=> LFNext infrastructure and change password migration

next-app/package-lock.json, next-app/src/lib/Header.svelte, next-app/src/lib/app.css, next-app/src/lib/error/Error.svelte, next-app/src/lib/icons/ErrorIcon.svelte, next-app/src/lib/icons/HamburgerIcon.svelte, next-app/src/routes/__layout.svelte
This PR establishes the foundation for a drawer style menu in the LFNext portion of the app.
Fixes #1386 
https://user-images.githubusercontent.com/4412848/164744482-2cdda524-fed3-419b-bd32-1fe08d665803.mov
https://user-images.githubusercontent.com/4412848/164745513-90955e09-9a4b-4f52-b6b1-c14114a90d01.mov
https://user-images.githubusercontent.com/4412848/164748445-d2915ef2-e05c-478b-9c23-b20a2f60ce11.mov
=> LFNext menu

next-app/src/lib/app.css, next-app/src/routes/__layout.svelte
=> Refactor usage of `prose`

docs/DEVELOPER.md
add instructions for running playwright tests to DEVELOPER.md
- documentation update
=> add instructions for running playwright tests

docs/DEVELOPER.md
add information for setting up Docker in a Windows development environment
documentation update
=> add additional instructions for Docker in Ubuntu

docker/deployment/app-deployment.yaml, docker/deployment/db-deployment.yaml, docker/deployment/lfmerge-deployment.yaml, docker/deployment/mail-deployment.yaml, docker/deployment/next-app-deployment.yaml, docker/deployment/next-proxy-deployment.yaml
There were times when lfmerge would utilize so much memory it would cause issues on the node where it was running.  This PR will help establish some limits to resource utilization so any overuse of resources will only affect lfmerge.
- k8s infrastructure optmization
N/A
=> Establish resource limits of containers in k8s

.github/workflows/production.yml, .github/workflows/staging.yml
LTOps requested k8s context be controlled at the app level, not at org anymore.
- Deployment configuration
N/A
=> updated name of k8s secrets

.github/workflows/integrate-and-deploy.yml
See notes in referenced issue below.
Fixes #1469 
N/A
=> corrected missed naming refactor

.github/workflows/pull-request.yml, .husky/pre-commit, package-lock.json, package.json
Part 3/3 of #1203
Adds pre-commit hook and CI integration for prettier.
- Tooling upgrade
Here's what the pre-commit hook looks like in action:
The CI integration can be seen in action here:
https://github.com/myieye/web-languageforge/actions/runs/3235861576/jobs/5300876250
=> Add prettier pre-commit hook and CI check

.github/pull_request_template.md
This PR updates the PR template according to discussions on our last retrospective
- This change requires a documentation update
N/A
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.
=> incorporated retro feedback into pr template

Makefile, docker-compose.yml
Fixes #1494 
This PR cleans up the dev workspace a little more thoroughly
N/A
1. `make`
2. `make clean`
3. `make unit-tests`
4. `make playwright-tests`
5. make note of the `test-results` folder and any `*storageState.json` files
6. `make clean-powerwash` and ensure those files are gone
7. `docker images` and ensure there are no more `lf-*` images 
N/A
=> Clean up transient build/test artifacts

docs/DIAGRAM.md
As part of my on-boarding I decided to make a mermaid diagram, this is a diagram in markdown, it's not an image that I copied in so it'll be easy to keep up to date as things change.
Edit: make sure you view the markdown preview of the file
=> docker services diagram

package-lock.json, package.json, src/angular-app/bellows/core/api/project.service.ts, src/angular-app/bellows/core/offline/editor-data.service.ts, src/angular-app/languageforge/lexicon/lexicon-app.component.ts, src/app_dependencies.json, src/offlineCheck.txt, webpack.config.js
Fixes #1574 
This PR pulls out the dep on offline.js and replaces it with the modern HTML spec on it:  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine
- UI change
https://user-images.githubusercontent.com/4412848/201421607-d3ed747d-92b5-4bc4-90e5-dcfa5147df5b.mov
- Use DevTools to simulate offline or turn your wifi off and ensure the app reflects the correct status
=> refactor offline detection

docker-compose.yml, docker/deployment/db-deployment.yaml
Fixes #1587 
This PR seeks to upgrade mongo from 4.2 to 4.4
https://www.mongodb.com/docs/manual/release-notes/4.4-upgrade-standalone
https://github.com/sillsdev/web-languageforge/blob/develop/docs/RELEASE.md#database-upgrades
- database upgrade
N/A
- General smoke test of application
- see https://github.com/sillsdev/web-languageforge/blob/develop/docs/RELEASE.md#database-upgrades for further instructions
=> upgrade to mongodb 4.4

src/composer.lock
Our PHP Mongo dependency had fallen behind and need to be updated.
- dependency update
N/A
- verify automated tests passed
- general smoke test of app
=> updated mongodb dependency

docs/DEVELOPER.md
Some needed updates to the DEVELOPER readme to remove old sections on Protractor E2E tests and to add a section on IDE developer experience.
- documentation
=> Updates to DEVELOPER.md

src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts
Fixes #1625 
This PR simply updates an outdated compatibility message
N/A
- somehow or another, find a project on LD that is older than 9.0 and try to import it.
=> updated error message about FLEx support

docker-compose.yml, docker/deployment/db-deployment.yaml
Fixes #1568 
This PR upgrades the running versions of mongodb to 5.0
- database upgrade
- Successful automated tests are a decent indicator of success
- A general smoke test of the app would be further affirming
=> upgraded db container to mongodb 5.0

.github/workflows/integrate-and-deploy.yml
There were some deprecation warnings recently in a GHA run.  This PR should address those.
- CI/CD config change
warning:
- Ensure there are no deprecation warnings when the `integrate-and-deploy` workflow is run
=> address deprecation warnings in GHA runs

next-app/package-lock.json, next-app/package.json, next-app/src/app.html, next-app/src/lib/auth/index.ts, next-app/src/lib/error/index.ts, next-app/src/lib/fetch.ts, next-app/src/lib/server/sf.ts, next-app/src/lib/server/user.ts, next-app/src/lib/stats/Stat.svelte, next-app/src/routes/+layout.svelte, next-app/src/routes/+page.svelte, next-app/src/routes/password/+server.ts, next-app/src/routes/password/change/+page.svelte, next-app/src/routes/projects/[project_code]/+page.server.ts, next-app/src/routes/projects/[project_code]/+page.svelte, next-app/src/routes/projects/[project_code]/Activity.svelte, next-app/src/routes/projects/[project_code]/activities/+server.ts, next-app/src/routes/projects/[project_code]/meta/+server.ts, next-app/svelte.config.js
This PR brings the LFNext app up to date with the recently released SvelteKit 1.0
- dependency upgrade
- Attempt to change password without providing anything and ensure error messaging looks good
- Attempt to change password while providing different passwords and ensure error messaging looks good
- View the project's dashboard and click the "show all" button at the bottom of the activity table
=> upgrade LFNext to newly released sveltekit 1.0

test/e2e/user-profile.spec.ts
We're experiencing weird failures in CI and want to see if these tests are causing them.
See: https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1671712283656969
=> Disable potentially flaky tests

docker/db/README.md, docs/RELEASE.md
#1668 's upgrade included a new client, i.e., `mongo` is now `mongosh`.  This PR updates the docs that were missed in that PR.
- documentation update
N/A
=> update docs to new mongo 6.0 client

.github/pull_request_template.md
A reworking of our GitHub PR template.
- Removed "Type of Change" [as discussed](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1673519978863289).
- Reworded almost everything to a length that is more likely to be read. I think I preserved all the critical details.
- Restructured "(issue)" to give it some extra prominence and so we can replace it with only Double-click + Paste
- Merged the two testing sections
- Made everything that is _intended to be replaced italic_
- Turned QA environment url into a link, so it's obvious that it's a real domain/url
- Left the checklist alone 😉 
_A summary of the change including motivation and context._
_Demonstrate any UI / behavioral changes with screenshots or animations._
Testers, use the following instructions on …
=> Rework and simplify PR template

src/Site/views/languageforge/container/languageforge.html.twig, src/angular-app/bellows/core/navbar.controller.ts, src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts, test/e2e/constants.ts, test/e2e/global-setup.ts, test/e2e/pages/base-page.ts, test/e2e/pages/configuration-input-systems.tab.ts, test/e2e/pages/editor.page.ts, test/e2e/pages/signup.page.ts, test/e2e/pages/tabbed-page.ts, test/e2e/playwright.config.ts, test/e2e/tests/signup.spec.ts
Fixes both "Share" buttons from navigating to editor (previously I only fixed one).
Fixes some flaky E2E tests that I found while digging through recent actions.
Share buttons:
- Navigate to "Settings > Configuration"
- Try "Settings > Share with others" and "Share"
- Verify that you stay on the current page
E2E tests: let 'em rip 🔥
=> Share button and flaky E2E test fixes

next-app/src/routes/projects/[project_code]/Activity.svelte, next-app/src/routes/projects/[project_code]/activities/+server.ts, src/Api/Model/Shared/Command/UserCommands.php, src/Api/Model/Shared/Dto/RightsHelper.php, src/Api/Model/Shared/UserModel.php, src/Api/Service/Sf.php, src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts, src/angular-app/bellows/apps/userprofile/user-profile-app.component.html, src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts, src/angular-app/bellows/core/api/user.service.ts, test/e2e/pages/user-profile.page.ts, test/e2e/tests/user-profile.spec.ts, test/php/model/shared/UserModelTest.php, test/php/model/shared/commands/UserCommandsTest.php, test/php/model/shared/dto/ActivityListDtoTest.php
Fixes #1362
Adding a tab to the user profile for a user to delete their account. If a user is a project owner, a message letting them know to transfer or delete their owned projects is displayed. I have noticed that every so often, on a first load of the user profile, the delete dialog is still shown to users who own projects, due to mistiming of boolean values being set, possibly due to race conditions.
- This change requires a documentation update - maybe add a post to the community site
- UI change
When a user owns projects (cannot yet delete their account):
When a user has no projects (can go ahead and delete their account):
1. Access this tab as a user …
=> Allow users to delete their Language Forge account

src/composer.json, src/composer.lock
Upgrade the [Google OAuth composer dependency](https://packagist.org/packages/league/oauth2-google) library to the latest version (v4)
~~I have commented my code, particularly in hard-to-understand areas~~
~~I have added tests that prove my fix is effective or that my feature works~~
- Test Google OAuth path for sign-in on QA
- Test Google Oauth path for register new user on QA
=> Upgrade oauth2-google composer dependency

next-app/package-lock.json, next-app/package.json, next-app/src/lib/Details.svelte, next-app/src/routes/+page.svelte
This PR will add some of the potential components needed for the LFNext editor pages, see the mock-ups for reference.
There will be nothing to test until these components are actually integrated into live pages.
=> LFNext editor components

next-app/src/routes/+page.svelte
late PR feedback from #1705 
- since this is only a change on the LFNext playground, there's really nothing to test in staging.
=> fixed sorting typo in LFNext playground

next-app/src/routes/+page.svelte
This came from the following discussion:  https://github.com/sillsdev/web-languageforge/pull/1705#discussion_r1086127481
no need for testing since this is just playground stuff at this point
=> decided on better mark-up

src/Site/Controller/Redirect.php
Comments out some of our server side catches and redirects to try to expose the root cause of OAuth redirecting users out.
=> Comment out catches and redirects to 'logout'

CONTRIBUTING.md
=> Document new QA / testing workflow

src/.well-known/assetlinks.json
We need this file in order to make the TWA (Trusted Web Activity) Android app for Language Forge.
[Language Forge TWA Android.zip](https://github.com/sillsdev/web-languageforge/files/10858072/Language.Forge.TWA.Android.zip)
Run this .apk file of the Android app. 
1. Verify that you can sign in, or, if you're already signed into LF in Chrome, that you are automatically signed into the app.
2. Verify that webpage is displayed properly in the app.
=> Add assetlinks.json file for TWA

docker/lfmerge/Dockerfile
See https://github.com/sillsdev/LfMerge/pull/325 and https://github.com/sillsdev/LfMerge/pull/328
=> Bump LfMerge version (Enable 10MB limit for webm files and fix env vars)

src/Api/Model/Shared/UserListModel.php
Fixes bug where missing isDeleted field was causing users to *not* show up in active-user lists.
Fixes #1770.
=> Treat missing isDeleted field as false

.github/workflows/pull-request.yml, package-lock.json, package.json, src/angular-app/languageforge/lexicon/editor/_editor.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-multiparagraph.scss, src/angular-app/languageforge/lexicon/editor/field/_dc-multitext.scss
I have observed failing code formatting checks
on CI that don't fail locally, e.g. #1777 had a failed code formatter check.  Attempting to get more info with this PR.
=> attempt additional prettier checks on PR builds

next-app/package.json, package.json
=> Bump PNPM version to 9.11.0
