sillsdev/web-languageforge

src/Site/views/languageforge/theme/default/cssBootstrap4/languageforge_default.css
src/Site/views/languageforge/theme/default/cssBootstrap4/sass/base/_global.scss
src/Site/views/languageforge/theme/default/cssBootstrap4/sass/new-project/languageforge_new-project.scss
src/angular-app/bellows/directive/bootstrap4/modal.html
src/angular-app/bellows/directive/bootstrap4/pui-language.html
src/angular-app/languageforge/lexicon/new-project/bootstrap4/languageforge_new-project.css
src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.js
src/angular-app/languageforge/lexicon/views/configuration.js
src/angular-app/languageforge/lexicon/views/select-new-language.html

The diff is far more noisy than the actual changes:
- In `_global.scss` mostly rules were moved around (with a few changes).
- `languageforge_new-project.scss` had some style rules moved to `_global.scss`.
- `modal.html` had two wrapping `div`s removed, and the indention adjusted accordingly.
Other than that the diff is mostly straightforward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/76)

Fix modals

---

src/Site/Controller/Auth.php
src/Site/views/languageforge/container/languageforgeBootstrap4.html.twig

- Changes "Bad credentials" to "Invalid username or password." I'm not sure if there's a better way to do this, but I don't see one.
- Apparently I made the mobile logged-out header title show up even on large screens in c5bbcedf6e55f1e776d583221b4ccbb81270d8f7. This is now fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/85)

Miscilaneous authentication and mobile fixes

---

gulpfile.js

Previously included files were not watched (e.g. `_global.scss`). Even if they were watched, it's not easy to know what files depend on them. Therefore it's simplest (though not the most efficient) to rebuild Sass whenever any Sass file changes.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/87)

Fix Gulp watching of SCSS includes

---

test/app/bellows/pages/appFrame.js
test/app/languageforge/lexicon/pages/lexModals.js

Fixes warnings in the e2e tests about multiple elements being found for a selector. I was hoping to make the tests fail when multiple elements are found, but it doesn't look like Protractor supports this. It is possible to work around (see angular/protractor#2417) but probably not worth the extra work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/90)

Fix warnings in e2e tests

---

cleanup_css.sh
src/angular-app/languageforge/lexicon/directive/dc-audio.html

Not sure what the best to add the cleanup script is. You can shell out from Gulp, but then you're basically writing a shell script in JavaScript.
Also fixed a dropdown menu on Language Forge that was overlooked during the move to Bootstrap 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/96)

Add CSS cleanup script and fix audio dropdown menu

---

test/app/allspecs/e2e/afterEach.spec.js
test/app/bellows/pages/projectSettingsPage.js
test/app/bellows/pages/util.js

Previously all messages in the console were matched by text to determine whether they are errors. Every time a warning is encountered that isn't explicitly ignored, it's considered an error. I've changed it to check the message's log level. I believe `INFO` level logging is [ignored by default.](https://github.com/webdriverio/webdriverio/issues/491#issuecomment-90496527)
Now if the log level is `WARNING` it will never be considered an error. I also remove some text ignoring rules that didn't seem to be necessary anymore, and confirmed the tests are still passing (though not always--they're rather unstable right now).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languagefor …

Make console warnings not be errors in e2e testing

---

src/Api/Library/Shared/Website.php
src/Api/Library/Shared/WebsiteInstances.php
src/Api/Model/Shared/Command/SessionCommands.php
src/angular-app/languageforge/lexicon/lexicon.js

This only applies to the lexicon app. It could be added to others, but they haven't been experiencing the same performance issues. I can't tell any significant change in performance, but the [AngularJS production guide](https://docs.angularjs.org/guide/production) says it gives "a significant performance boost."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/106)

Run AngularJS in production mode in the lexicon app

---

src/Site/views/languageforge/theme/default/sass/_global.scss
src/angular-app/bellows/cssBootstrap4/palaso-ui.scss
src/angular-app/bellows/directive/notice.js
src/angular-app/languageforge/lexicon/lexicon.js

- Notifications are smaller and have text centered
- Header is nolonger sticky on mobile
- Notifications appear at the bottom of the screen on mobile
- Notification of offline mode only stays for 5 seconds
- Header changes to gray and text says "Language Forge Offline"
- Placement of close button on notifications has been fixed
Bug: With notifications shown at the bottom of the screen with absolute positioning, multiple notifications now stack instead of being displayed one above another. I'm unclear on the best approach to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/108)

Improve notifications on mobile and header

---

deploy/code.yml
deploy/dependencies.yml

This fixes some of the issues I ran into while setting up.
- `npm install` is now part of the Ansible script
- FactoryReset.php is now run as root as it requires
- Ansible doesn't throw a fit if `/usr/local/bin/node` is already a file (not a symlink).
I have no idea what I'm doing with Ansible, so some of this could be all wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/127)

Fixes to Ansible setup

---

src/angular-app/bellows/js/bellows.services.api.js

This fixes [an issue on live where projectId is sometimes undefined.](https://trello.com/c/XT3zQccy/825-console-error-on-live-project-apltw-2014-domexception-failed-to-execute-only-on-idbkeyrange-the-parameter-is-not-a-valid-key)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/132)

Fix hash-bang issue

---

src/Site/Controller/Base.php
src/Site/views/shared/container/container.html.twig
src/angular-app/bellows/js/bellows.services.api.js
src/angular-app/languageforge/lexicon/lexicon.js

Removes window.session from the page template. On the client side it was still being used to determine whether the site is in production or not.
@megahirt We discussed a bit on Flowdock whether to make .org production and all else development, or .local development and all else production. This PR uses .local, but as I started to open this PR it occurred to me that when proxying with host rewriting, the client-side will see a non-.local hostname (for example, I've been accessing Language Forge on my phone as <ip address>:3000). This makes me think it might be better to fall back to development mode when the host ends in neither .org or .local.
Either way it's not a big deal at this time. All the isProduction variable is used for is turning on AngularJS optimizations, though it could be …

Remove window.session from the the page template

---

src/angular-app/languageforge/lexicon/js/lexicon.services.config.js

The root cause of the bug was the function that removed fields from the config's list of visible fields if they had been hidden for a particular user or role. It was removing fields from the fieldOrder list *while* it was still iterating over that list, which is always fraught with danger. The solution is to filter the list first, then set the config.
This is a fix for #160.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/161)

Fix fields not being properly hidden

---

src/angular-app/bellows/directive/bootstrap4/picklist-editor.html
src/angular-app/bellows/directive/picklist-editor.js

We now track the index of every item in the list, so that the delete buttons appear to "travel" alongside their corresponding items if items are rearranged.
This is a bugfix for #29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/163)

Fix wrong items being deleteable from option lists

---

installer/ubuntu1604Installer.sh
refreshDeps.sh

The folder `web-scriptureforge` was created via root.  `node_modules` does not exist on a clean install.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/179)

Installer: Fix usage for clean install

---

src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php
src/Api/Model/Scriptureforge/Sfchecks/Dto/UsxTrimHelper.php
src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html
src/angular-app/scriptureforge/sfchecks/partials/questions.js

PR originally on [web-scriptureforge repo](https://github.com/sillsdev/web-scriptureforge/pull/128), transferred over to this repo instead. Will probably squash-and-merge rather than merge the branch.
This fixes comment exporting for both Paratext 7 and 8. I've changed the "Prepare Export" button to be two buttons, one for Paratext 7 and one for Paratext 8 instead, and also changed the two-step process into a single-step process. (You used to click "Prepare", then wait a short while, then click "Download", but it makes more sense to download the file as soon as it's available. Thanks to @megahirt for the suggestion.) Screenshot:
One feature NOT included in this PR is the ability to export all comments, not just those in a single text. The code is in place, we just have to implement it and …

Fix comments export to ParaText 7 and/or 8

---

src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.js
src/angular-app/bellows/directive/palaso.ui.comments.comments-right-panel.js
src/angular-app/bellows/directive/palaso.ui.comments.regarding-field.js

Fixed the latest bug in Trello that was introduced from the last PR.
- Fixed dynamic updating of comment context only when using an optionlist field type
- Only clear an existing comment after posting a comment and not on a refresh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/185)

Fixed comment context changing when editing other fields

---

src/angular-app/bellows/cssBootstrap4/palaso-ui.scss
src/angular-app/bellows/directive/bootstrap4/pui-soundplayer.html
src/angular-app/bellows/directive/soundplayer.js
src/angular-app/languageforge/lexicon/editor/field/dc-audio.html
src/angular-app/languageforge/lexicon/editor/field/dc-audio.js
src/angular-app/scriptureforge/sfchecks/partials/question.html
src/angular-app/scriptureforge/sfchecks/partials/questions.html
src/angular-app/scriptureforge/sfchecks/sass/sfchecks.scss

Language Forge:
Scripture Forge, default state:
Scripture Forge, playing state:
The UI on LF is good in my opinion, but the SF UI is a bit rough. I'm not entirely certain the best way to approach it, but I think it is acceptable for now.
There are, unfortunately, merge conflicts, but I believe they should be straightforward to resolve. If requested I would be happy to rebase.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/187)

Add sliders to audio player on both sites

---

src/Site/views/scriptureforge/theme/default/sass/_global.scss
src/angular-app/bellows/directive/bootstrap4/pui-soundplayer.html
src/angular-app/bellows/directive/palaso-ui.scss
src/angular-app/bellows/directive/soundplayer.js
src/angular-app/languageforge/lexicon/editor/field/dc-audio.html
src/angular-app/scriptureforge/sfchecks/partials/question.html
src/angular-app/scriptureforge/sfchecks/partials/questions.html
src/angular-app/scriptureforge/sfchecks/sfchecks.scss

This PR does two things:
- Previously when the audio was playing and the user tried to seek, the slider would keep jerking forward to the current playback position. Now the slider stops updating when the user is using it.
- Previously the audio player on SF was to the left of the title and expanded to show playback only when playing. Now it is below the title and the playback control is always visible.
I have not succeeded in running the e2e tests for this branch. As it stands I am unable to get any of the tests to run properly on master, so either they're broken on master already or (more likely) there's a problem with my setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/we …

Fix operation of slider while playing and position of audio player

---

src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php
src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexExample.php
src/Api/Model/Languageforge/Lexicon/LexMultiParagraph.php
src/Api/Model/Languageforge/Lexicon/LexMultiText.php
src/Api/Model/Languageforge/Lexicon/LexMultiValue.php
src/Api/Model/Languageforge/Lexicon/LexParagraph.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
src/Api/Model/Scriptureforge/Sfchecks/Command/QuestionCommands.php
src/Api/Model/Shared/ActivityModel.php
src/Api/Model/Shared/Command/ActivityCommands.php
src/Api/Model/Shared/Dto/ActivityListDto.php
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Model/Shared/UnreadLexCommentModel.php
src/Api/Model/Shared/UnreadLexReplyModel.php
src/Api/Service/Sf.php
src/angular-app/bellows/apps/activity/activity-app.component.ts
src/angular-app/bellows/core/api/activity.service.ts
test/php/model/languageforge/lexicon/LexEntryModelTest.php
test/php/model/languageforge/lexicon/LexMultiParagraphTest.php
test/php/model/shared/LexMultiTextTest.php
test/php/model/shared/LexMultiValueTest.php
test/php/model/shared/commands/ActivityCommandsTest.php
test/php/model/shared/dto/ActivityListDtoTest.php

The activity list API is missing a couple of unit tests for the new entry or project API calls, but I've tested them by hand and they do return the right DTO data structure. I also think that some thought could be given to how the "old" API could be improved, at least with a view to making the names more consistent (e.g., `getActivityForUser` doesn't actually get the activity of a single user; rather, it gets *all* available activity, and the "ForUser" part of the name just refers to which user should be considered as having *seen* all that activity. Whereas `getActivityForProject` is actually getting the activity for a single project. The naming is inconsistent at the moment, which may cause future confusion).
This is ready for review, and could be merged into master so that work on the …

Activity feed API for Language Forge

---

src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.html
src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.js

Refers to Trello card:
https://trello.com/c/e3Hy9Er0/1083-comments-spinner-continues-to-spin-indefinitely
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/192)

Hide comment bubbles for new entries until the word has been saved

---

src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.js
src/angular-app/bellows/directive/palaso.ui.comments.dc-comment.html
src/angular-app/languageforge/lexicon/editor/editor-abstract.html
src/angular-app/languageforge/lexicon/editor/editor.js

Applies to the following Trello cards:
https://trello.com/c/QqQ8Q8Od/1084-comment-bubbles-are-visible-for-observer-role-but-this-should-not-be-the-comment-bubbles-should-only-be-visible-for-the-permissi
https://trello.com/c/6q97M4FK/905-during-s-r-users-should-be-locked-out-of-comments
As I don't have the ability to test a S/R I am unable to completely test that it works. The logic is the same as the observer so in theory it will be fine. I tested it to some extent with the observer role so I'm pretty sure it will be ok. For the send receive in progress I decided not to hide the entire commenting panel if it was open but rather just hide the textarea and any buttons that would allow edit/delete functionality. If we decided to hide it then I suspect the user would get frustrated with it …

Commenting disabled for observers and anyone with no rights

---

src/Site/views/scriptureforge/theme/default/sass/_global.scss
src/angular-app/scriptureforge/sfchecks/sfchecks.html

I'm still not entirely certain how it broke or why it broke, but removing a class that made it display flex fixes it. E2e tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/197)

Fix layout of invite a friend dialog on SF

---

src/angular-app/bellows/directive/palaso-ui.scss
src/angular-app/languageforge/lexicon/editor/field/dc-entry.html
src/angular-app/languageforge/lexicon/editor/field/dc-example.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.html
test/app/languageforge/lexicon/editor/e2e/editor-entry.spec.js
test/app/languageforge/lexicon/pages/editorPage.js

Previously each entry, sense, and example had a trash can for a delete button. The trash can has been replaced with a vertical ellipsis that opens a dropdown menu. Currently the dropdown menu has only one action (to delete). This is in preparation to add menu items to move a sense or example up or down (when applicable).
All e2e tests are passing on both LF and SF, though this change only affects LF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/195)

Move delete button into ellipsis menu

---

src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
src/Api/Model/Languageforge/Semdomtrans/Command/SemDomTransItemCommands.php
src/Api/Model/Scriptureforge/Sfchecks/Command/QuestionCommands.php
src/Api/Model/Scriptureforge/Sfchecks/Command/TextCommands.php
src/Api/Model/Shared/Command/UserCommands.php
src/Api/Model/Shared/Mapper/MapperModel.php
src/Api/Model/Shared/Mapper/MongoMapper.php
test/php/model/languageforge/lexicon/command/LexCommentCommandsTest.php
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php
test/php/model/scriptureforge/Sfchecks/AnswerModelTest.php
test/php/model/scriptureforge/Sfchecks/command/QuestionCommandsTest.php
test/php/model/scriptureforge/Sfchecks/command/SfchecksUploadCommandsTest.php
test/php/model/scriptureforge/Sfchecks/command/TextCommandsTest.php
test/php/model/shared/CommentModelTest.php
test/php/model/shared/ProjectModelTest.php
test/php/model/shared/UserModelTest.php
test/php/model/shared/UserUnreadModelTest.php
test/php/model/shared/commands/ActivityCommandsTest.php
test/php/model/shared/commands/ProjectCommandsTest.php
test/php/model/shared/dto/ActivityListDtoTest.php

There are a few fields that will cause test failures if they're trimmed when empty, because of some assumptions in our code (like "a question will always have an answers array", for example). The `shouldKeepKey` function ensures that those fields will still be persisted even if they're empty. This is not a great long-term solution; it would be better to find and correct all those assumptions. But in the short term, this works and makes all PHP unit tests pass.
All PHP unit tests passing with this PR, and all E2E tests for Language Forge. (I haven't yet run E2E tests for Scripture Forge due to a misconfiguration on my laptop).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-la …

Mongo mapper trims empty fields

---

src/angular-app/bellows/directive/palaso-ui.scss

The typeahead had a bright yellowish background for the item being hovered over. This made it illegible because the text goes to white on hover. There is already a dark blue background in place on hover. With these lines removed it looks how one would think it would.
Not sure how this became a problem, but before it just looked wrong and was illegible, and now it looks right.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/201)

Fix highlight background color of typeahead

---

src/angular-app/bellows/apps/public/signup/signup-app.component.html
src/angular-app/bellows/apps/public/signup/signup.scss

This is the simplest change I could think of that works. If we want something more complicated, I'll design it, but this design allows me to make no code changes and just change the HTML and CSS.
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/203)

Add Google OAuth button to regular signup page

---

src/angular-app/languageforge/lexicon/editor/field/dc-multiparagraph.html
src/angular-app/languageforge/lexicon/editor/field/dc-multitext.html
src/angular-app/languageforge/lexicon/editor/field/dc-text.html
src/angular-app/languageforge/lexicon/editor/field/dc-text.js

Text fields can be disabled for several reasons: the field contains metadata like `<span>` tags that would be lost if it's edited in LF. Or there's a Send/Receive in progress. Or the user doesn't have permission to edit the project (Observer role, for instance). These three cases should show different messages in the hover text.
This PR is merging into the `lf-qa` branch instead of master because we currently have QA branching off of master at a point a few commits back from HEAD. (Specifically, just before the commit where the unified-config feature was merged into master). And this code needs to go into QA so that we can deploy it to live in the upcoming deployment. Once QA is merged into `lf-live` and released, we will merge `lf-qa` and `lf-live` back into master, and this code will …

Improve "why this field is disabled" message

---

src/angular-app/bellows/directive/_palaso.ui.comments.dc-comment.scss
src/angular-app/languageforge/lexicon/editor/editor-abstract.html
src/angular-app/languageforge/lexicon/editor/editor-comments.html
src/angular-app/languageforge/lexicon/editor/editor.js
src/angular-app/languageforge/lexicon/editor/field/dc-fieldrepeat.html
src/angular-app/languageforge/lexicon/editor/field/dc-multiparagraph.html
src/angular-app/languageforge/lexicon/editor/field/dc-multitext.html

Looks like we aren't using the **Editor Comments** view any more. This removes it and cleans up. E2E LF passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/220)

Remove unused Editor Comments view

---

package-lock.json
package.json
src/Api/Model/Shared/Translate/Command/TranslateProjectCommands.php
src/Api/Model/Shared/Translate/TranslateConfig.php
src/angular-app/bellows/apps/translate/editor/document-editor.ts
src/angular-app/bellows/apps/translate/editor/editor.component.html
src/angular-app/bellows/apps/translate/editor/editor.component.ts
src/angular-app/bellows/apps/translate/editor/segment.ts
src/angular-app/bellows/apps/translate/shared/model/translate-config.model.ts
src/netcore-api/SIL.XForge.WebApi.Server/Models/Translate/TranslateUserPreferences.cs

- Save the ref of the last segment that the user was editing along with a checksum for the segment.
- When the user opens the project again, navigate to the saved segment.
- Check if the segment has changed by checking the checksum.
- The "Save & Close" button is no longer necessary, since a changed segment will eventually be trained when the user switches segments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/221)

Navigate to last selected segment when opening project

---

src/Api/Library/Scriptureforge/Sfchecks/ParatextExport.php
test/php/library/scriptureforge/sfchecks/ParatextExportTest.php

This is in response to an user who found it hard to process answers and comments without seeing the question in context.
This will export the question title along with the answer.  Comments also now show who it was in reply to.
This is a minimal change to be able to ship this functionality out to an user.
Upon reviewing the code, it seemed to me that this class should be refactored to be a proper class without all static functions, and move the "main" static function to one of the Command classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/225)

Paratext export contains question in context

---

src/Site/Controller/Validate.php
src/Site/OAuth/OAuthBase.php
src/index.php

The cause was that the invite-a-user feature doesn't assign a username and requires validation. I decided that OAuth authentication counts as validating your email address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/230)

Fix bug where invited users can't do OAuth signup

---

gulpfile.js
src/Site/OAuth/OAuthJWTToken.php
src/config.php

This allows us to supply the OAuth client ID for the Gather Words appvia either a Gulp build parameter (`-- gatherWordsClientId`) or via the `GATHER_WORDS_CLIENT_ID` environment variable. We use the latter in our TeamCity build so that the client ID won't show up in logs. (Less important when it comes to client IDs, but important when it comes to client secrets — though the Android app OAuth process doesn't use client secrets.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/234)

Add build parameter for Gather Words client ID

---

package-lock.json
package.json
src/Api/Model/Shared/InputSystem.php
src/Site/Controller/Base.php
src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts
src/angular-app/bellows/directive/palaso.ui.comments.comments-right-panel.js
src/angular-app/bellows/shared/model/input-system.model.ts
src/angular-app/languageforge/lexicon/core/lexicon-utility.service.ts
src/angular-app/languageforge/lexicon/editor/editor-entry.html
src/angular-app/languageforge/lexicon/editor/editor-list.html
src/angular-app/languageforge/lexicon/editor/editor.js
src/angular-app/languageforge/lexicon/editor/field/dc-entry.js
src/angular-app/languageforge/lexicon/editor/field/dc-multitext.html
src/angular-app/languageforge/lexicon/editor/field/dc-rendered.js
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.html
src/angular-app/languageforge/lexicon/editor/field/field.module.ts
src/angular-app/languageforge/lexicon/lexicon.js
src/angular-app/languageforge/lexicon/lexicon.module.ts
src/angular-app/languageforge/lexicon/settings/configuration/configuration-input-systems.component.html
src/app_dependencies.json
src/config.php.fortest
src/config.php.live
test/app/languageforge/lexicon/shared/editor.page.ts
webpack.config.js

This adds a new property off of the Input System model and when non-empty adds a style="font-family:" attribute to all data associated with the writing system.  The templates affected are dc-multitext and dc-rendered.
The lexicon utilities that generate "rendered" fields like word, meaning and citation form did not have the inputsystems configuration accessible so I had to enable that by propogating the global config all the way through.
In general, this code is a mess and once we refactor the entire editor to use a single DTO where all data is accessible at application load time and services are used to share data, we'll be in a much better place.
This is as minimal of a change as I could make in order to ship the "font name" feature to users who requested to be able to display their …

Add "Font Name" to Input System model

---

src/Api/Model/Scriptureforge/Sfchecks/AnswerModel.php
src/Site/views/scriptureforge/theme/default/page/sfchecks_usersguide.html.twig
src/angular-app/bellows/apps/translate/core/translate-send-receive.service.ts
src/angular-app/bellows/apps/translate/new-project/views/new-project-chooser.html
src/angular-app/bellows/apps/translate/new-project/views/new-project-sr-credentials.html
src/angular-app/bellows/apps/translate/settings/sync.component.html
src/angular-app/scriptureforge/sfchecks/partials/project.html
src/angular-app/scriptureforge/sfchecks/partials/questions-settings.html
src/netcore-api/SIL.XForge.WebApi.Server/Controllers/UsersController.cs
src/netcore-api/SIL.XForge.WebApi.Server/Services/ParatextSendReceiveRunner.cs
src/releasenotes/scriptureforge.md

This PR changes the spelling of "ParaTExt" to "Paratext" across our code-base
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/242)

normalize spelling of Paratext

---

src/angular-app/bellows/core/offline/lexicon-comments.service.ts
src/angular-app/bellows/directive/palaso.ui.comments.comment-bubble.js
src/angular-app/bellows/directive/palaso.ui.comments.comments-right-panel.html
src/angular-app/languageforge/lexicon/core/lexicon-config.service.ts
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/field/dc-entry.html
src/angular-app/languageforge/lexicon/editor/field/dc-entry.js
test/app/languageforge/lexicon/shared/editor.page.ts

Relates to https://trello.com/c/5nmjsPhK
3 E2E tests are failing - same as `master`
New comments can not be posted directly against the entry - view only. Replying is allowed for any comments that do appear on the entry.
If no comments are set on the entry then the comment bubble is hidden. No point showing it as clicking it would effectively do nothing as you can't comment.
Have tested with a comment on the entry that has no `contextGuid` set. I've not been able to test with a real sync though - hopefully it is fine though. So long as the `contextGuid` is undefined OR an empty string then it will be fine. Otherwise, if the sync wants to be updated, the `contextGuid` can be set to `"entry"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Allow comments to appear directly on the main entry

---

src/Api/Model/Scriptureforge/Sfchecks/Command/QuestionCommands.php
src/Api/Model/Scriptureforge/Sfchecks/Command/TextCommands.php
src/Api/Model/Shared/Command/ActivityCommands.php
src/Api/Service/Sf.php
src/angular-app/bellows/apps/activity/activity-container.component.html
test/app/bellows/shared/activity.page.ts
test/app/scriptureforge/activity/activity.e2e-spec.ts
test/app/scriptureforge/activity/activityCustomMatchers.d.ts
test/app/setupTestEnvironment.php
test/php/model/shared/commands/ActivityCommandsTest.php
test/php/model/shared/dto/ActivityListDtoTest.php
test/php/service/ApiCrudTest.php

Have updated all SF E2E tests for the new activity feed layout.
All tests are passing for SF & LF (except for the usual 3).
There were two activities that were not tracking the `userRef`. I've added in the `userRef` based on how I saw it being used in other parts of the API - this will need to be reviewed in case there is a more official way of doing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/255)

E2E Activity Feed tests fixed

---

src/angular-app/languageforge/lexicon/core/lexicon-rights.service.ts
src/angular-app/languageforge/lexicon/editor/comment/comment-bubble.component.html
src/angular-app/languageforge/lexicon/editor/comment/comment-bubble.component.ts
src/angular-app/languageforge/lexicon/editor/comment/comment.module.ts
src/angular-app/languageforge/lexicon/editor/comment/comments-right-panel.component.html
src/angular-app/languageforge/lexicon/editor/comment/comments-right-panel.component.ts
src/angular-app/languageforge/lexicon/editor/comment/current-entry-comment-count.component.html
src/angular-app/languageforge/lexicon/editor/comment/current-entry-comment-count.component.ts
src/angular-app/languageforge/lexicon/editor/comment/dc-comment.component.html
src/angular-app/languageforge/lexicon/editor/comment/dc-comment.component.ts
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.component.html
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.component.ts
src/angular-app/languageforge/lexicon/editor/comment/regarding-field.component.html
src/angular-app/languageforge/lexicon/editor/comment/regarding-field.component.ts
src/angular-app/languageforge/lexicon/editor/editor-entry.html
src/angular-app/languageforge/lexicon/editor/editor.js
src/angular-app/languageforge/lexicon/editor/field/dc-multioptionlist.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-multioptionlist.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-semanticdomain.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-semanticdomain.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts
src/angular-app/languageforge/lexicon/editor/field/field-control.model.ts
src/angular-app/languageforge/lexicon/shared/model/lex-comment.model.ts
test/app/languageforge/lexicon/shared/editor.page.ts

This removes API calls and takes data from component inputs instead. Since Angular components have an isolated scopes inputs were added (esp. `dc-comment` which entirely relied on the parent scope).
- also simplify multi option lists and semantic domain fields
LF E2E is passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/260)

Refactor comments to Angular components

---

package-lock.json
package.json

Currently we are using node-sass@4.5.0 on [our fork of node-sass](https://github.com/sillsdev/node-sass). 
Node-sass is a wrapper around libsass, which is written in C. The bindings between Node and libsass have to be recompiled for every API change in Node (which is generally quite frequent). The node-sass installer attempts to download a binary for the current platform, Node version, and node-sass version (i.e. it has to find a binary that matches all three). Lately in xForge it has had to fall back to building the bindings from source. I noticed this because on Uma's machine the build fails. The error message isn't very clear about why, but ideally building from source should not be necessary; it should just download the binaries.
The reason it can't download the binaries is because we …

Upgrade node-sass to 4.9.0

---

.editorconfig
README.md
deploy/vars_palaso.yml

To run the translation app we need a 'ServerAlias localhost' line in the site config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/263)

Add localhost alias

---

src/Api/Library/Shared/Script/Migration/FixSenseAndExampleLabels.php
src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
src/Api/Model/Shared/ActivityModel.php
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php

Now when a lexical entry is updated, the activity log will contain not just the differences, but also the human-readable field labels for those differences. This will enable the activity log frontend to generate a complete activity-log entry without needing a second server round-trip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/265)

Field labels in activity log

---

src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php
src/Api/Model/Shared/ActivityModel.php
src/Api/Model/Shared/Command/ActivityCommands.php

We don't record *who* pressed the "Like" button, only who wrote the comment that was "liked".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/266)

Record comment "likes" in activity log

---

README.md
deploy/code.yml
deploy/dependencies.yml
deploy/xenial/Vagrantfile

This PR updates the Vagrant install to a usable condition. The original Vagrantfile was not very helpful, so I used the Taylor-2017 Vagrantfile as a starting point. This also involved some changes to two Ansible files (dependencies.yml and code.yml).
Most of the changes should be relatively straight forward:
- Changing references to a mongodb service to mongod
- Generate website definitions *after* `npm install` has been run, not before (local Gulp does not exist until then)
Intended usage is as follows:
- Download deploy/xenial/Vagrantfile and save it as Vagrantfile
- Run `vagrant up --no-provision`
- Run `vagrant up --provision`
--- …

Create a working Vagrant install from the taylor-2017 version

---

gulpfile.js
webpack.config.js

VirtualBox does not forward file change events on the host to the guest. Watching builds on the Linux side, therefore, does not work.
The current workaround is to run them on the Windows using `node node_modules/.bin/webpack --watch  --env.applicationName=languageforge --colors`. The way the Gulp script currently is written uses the shell and fails on Windows. This changes it to use the Webpack API. Admittedly, some parts of this change are suboptimal. The CLI exposes some options not directly available via the API, but it is possible to recreate the same effect via the API. 
For example, where the CLI lets us use the `-p` flag, to do the same via the CLI, we have to load two plugins explicitly and set NODE_ENV to `'production'`. This is exactly what that flag does to begin with.
---
This …

Make Gulp run Webpack via the API so it will work on Windows

---

README.md
debuge2e.sh
test/app/protractorConf.js

At present it is not possible to pause the tests while running because `browser.pause()` is broken as of Node 8.x. The old debugger has been replaced with one that works with the Chrome devtools.
This adds a script that signals the Node process running the tests to tell it to enable its debugger and start listening. Also adds usage instructions to the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/282)

Upgrade test pausing to work with new debugger in Node 8

---

src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
src/Api/Model/Shared/Dto/ActivityListDto.php
src/Api/Service/Sf.php
test/php/model/languageforge/lexicon/LexEntryModelTest.php
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php

Activity list in Mongo stores `actionContent` as a map of string keys to string values, so storing the old and new values of fields required some complicated key names to uniquely identify the fields. For the activity log frontend code, however, we can simplify those key names and turn the changes into a much simpler `changes` array, where each change is a record with the following keys:
- `changeType`: one of `edited_field`, `added_field`, `deleted_field`, or later on `moved_field` (once https://github.com/sillsdev/web-languageforge/pull/209 is implemented)
- `fieldName`: the name of the field in MongoDB (not localized)
- `fieldLabel`: an object representing the field label (localized) to display in the activity log. This object will always contain a `label` key (value is a string) and …

Activity log DTO sends easier-to-parse content to frontend

---

src/Api/Model/Shared/Dto/ActivityListDto.php

The `instanceof` logic in `prepareDto` assumes that the project model instance received is always the most specific instance possible (e.g., was created by `ProjectModel::getById`). But there are some code paths (for example, `ActivityListDto::getActivityForUser`) where `new ProjectModel($id)` is called, which creates a base ProjectModel instance instead of a more specific instance like LexProjectModel. The simplest fix is to rely on the `appName` field, rather than the PHP class instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/287)

Ensure activity log DTO always processes difference data

---

src/Api/Model/Shared/Command/UserCommands.php
test/php/model/shared/commands/UserCommandsTest.php

- allow update of a single ordinary parameter
The old code probably worked fine in PHP5 because `$params['username']` would have returned `null` rather than throw an exception. The two new tests were failing before the other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/288)

Fix user update and user profile update

---

src/Api/Model/Shared/ProjectModel.php
src/angular-app/bellows/directive/picklist-editor.html
src/angular-app/scriptureforge/sfchecks/partials/projectSettings.js
test/app/scriptureforge/sfchecks/question.e2e-spec.ts
test/app/scriptureforge/sfchecks/sf-checks-project-settings.e2e-spec.ts
test/app/scriptureforge/sfchecks/shared/project-settings.page.ts
test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php
test/php/model/scriptureforge/Sfchecks/command/SfchecksProjectCommandsTest.php

- add regression E2E tests
- remove readonly restriction on 'userProperties'
- fix pick list editor submitting forms (change <button> to <a>)
- some general tidy-up in changed files
Note: `projectSettings.js` changes are all non-functional tidy-up changes.
This is in response to a user reported error: https://community.scripture.software.sil.org/t/how-to-access-and-display-user-profiles/451
SF E2E tests passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/289)

fix SF user profile list settings not persisting

---

src/Api/Model/Shared/ActivityModel.php
src/Api/Model/Shared/Command/ActivityCommands.php
src/Api/Model/Shared/Dto/ActivityListDto.php
test/php/model/shared/dto/ActivityListDtoTest.php

For "add_lex_comment" and "update_lex_comment" activities, activity log DTO now returns a "fieldLabel" field whose contents look like:
```json
"fieldLabel": { "label": "Translation", "sense": 1, "example": 2 }
```
Or, at a minimum:
```json
"fieldLabel": { "label": "Word" }
```
The "fieldLabel.label" field should always be there, but "fieldLabel.sense" and "fieldLabel.example" are optional (though if "fieldLabel.example" appears, then "fieldLabel.sense" is guaranteed to also be there).
The DTO will also contain a "lexCommentFieldValue" which will contain the value of the field at the time the comment was made; this may be useful for displaying in the activity log.
Feedback requested on naming consistency: should "fieldLabel" be called "fieldLabel", or "lexCommentLabel", or …

Comments now have labels in activity log DTO

---

docs/webdesign/LanguageForgeV2/learn.html
src/Site/views/languageforge/theme/default/page/home/index.html.twig
src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.ts
src/angular-app/languageforge/lexicon/new-project/views/new-project-initial-data.html
src/angular-app/languageforge/lexicon/new-project/views/new-project-name.html
src/angular-app/languageforge/semdomtrans/new-project/app-management/ng-app.html
src/help/Concepts/FieldWorks_Language_Explorer.htm

The most prominent change is in `index.html.twig`.
The flie `FieldWorks_Language_Explorer.htm` had mixed line endings. Most of them were CRLF, so that's what I changed them all to. The diff doesn't show this very clearly.
This is not changing every reference. I tried not to get carried away and left alone some references, especially where it was clarified that FLEx refers to FieldWorks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/295)

Change references to FLEx to FieldWorks

---

src/angular-app/bellows/apps/userprofile/userprofile.scss

The SMS and email settings buttons have had the problem of appearing on top of the telephone input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/296)

Fix z-index of telephone input

---

deploy/dependencies.yml

When I run Ansible via a Vagrant provisioning script this task keeps adding lines to `/etc/apt/sources.list.d/mongodb-org-3.6.list`. Generally it looks something like this:
```
deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
```
These extra lines cause apt to print warnings, e.g.:
```
Target Packages (multiverse/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/mongodb-org-3.6.list:1 and /etc/apt/sources.list.d/mongodb-org-3.6.list:2
```
With every run it adds another line (generally without spaces within the brackets) and the warnings grow larger. …

Remove spaces in Mongo repository string

---

src/Site/views/languageforge/theme/default/sass/_global.scss
src/Site/views/scriptureforge/theme/default/sass/_global.scss

Currently the xForge footer is sticky. I can understand the purpose of a sticky header, but the footer seems unnecessary (looking at commit history, there's a possibility it may have even been changed by accident). On mobile this is especially problematic, especially when typing causes half the screen to be taken by the keyboard.
Surprisingly, this small change to the CSS breaks the e2e tests. Frequently buttons are hidden behind the sticky header and we have to scroll to the top before clicking them. Tests are passing as well as they do on master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/292)

Unsticky footer on mobile

---

README.md
deploy/dependencies.yml
deploy/vagrant_xenial_gui/Vagrantfile
deploy/virtualbox_xenial_gui_creation/Vagrantfile

I've created a Vagrant install method where everything is inside the box, including development tools. I initially thought this would be too slow, but Mark does all his development in VirtualBox and says it is not a problem. It's not ideal, but it's likely faster than using VirtualBox shared folders. At the very least it avoids the numerous problems with having the source code on the host and the application in the box.
The Vagrant GUI install method downloads a box with xForge already installed. This box is generated using `deploy/virtualbox_xenial_gui_creation/Vagrantfile` and should be updated whenever our installation method changes. Currently it's hosted on my Vagrant Cloud account at [NathanielPaulus/xenial64-xforge](https://app.vagrantup.com/NathanielPaulus/boxes/xenial64-xforge). …

Add Vagrant GUI install method and update local Linux setup instructions

---

src/Site/views/scriptureforge/theme/default/sass/_global.scss

Unfortunately when shuffling the Sass around I dropped the background color on the SF header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/306)

Fix SF header background color, broken in 724a2db

---

src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
test/php/model/languageforge/lexicon/LexEntryModelTest.php
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
test/php/model/shared/dto/ActivityListDtoTest.php

When adding (or deleting) a sense or example, include `oldValue` and `newValue` values for each subfield in the sense or example that was deleted, so that the activity log can show appropriate content for the add or delete activity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/300)

Include field values for added senses & examples

---

src/angular-app/bellows/core/navbar.controller.ts
src/angular-app/languageforge/lexicon/lexicon-app.component.ts

If the session doesn't contain a `.projectSettings` property, we should still present a languages menu, even if it's just a default one.
All E2E tests that were passing before this PR are still passing. (8 tests are failing on master as of when I'm submitting this, and this PR doesn't fix them).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/307)

Interface language: handle no-recent-project case

---

src/Site/views/shared/_global.scss
src/angular-app/bellows/apps/usermanagement/members.component.html
src/angular-app/bellows/directive/typeahead.html
src/angular-app/bellows/shared/select-language.component.html
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/settings/configuration/_configuration.scss
test/app/languageforge/lexicon/shared/lex-modals.util.ts

The positioning of the clear button on the user management app has been incorrect.
Before | After
---------|-------
On Language Forge it was also wrong, but not as bad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/310)

Fix positioning of user search clear button

---

src/angular-app/bellows/directive/pui-run-report.js

This is somewhat unintuitive. The original code looks more "correct." However, it appears that AngularJS maps null/undefined in the model to an empty string value in the select tag. I'm guessing this is because it needs a concept of the selection value being null. 
This isn't clearly documented, but the examples in [the documentation](https://docs.angularjs.org/api/ng/directive/ngOptions) don't define the property in the scope, making it undefined by default.
Before | After
---------|-------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/311)

Fix blank entry in SF reports select tag

---

src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts
test/app/bellows/user-profile.e2e-spec.ts

LF & SF used to both have two avatars on the page, with IDs mobileSmallAvatarURL and smallAvatarURL. A recent change to LF makes it use the same image element for both mobile and desktop, so one of the elements was removed, hence the error "imageElement is null".
Unfortunately the way the e2e tests run this error is masked, likely because console errors are not check until the end of an individual test, and by that time the page has been unloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/312)

Fix imageElement is null error

---

src/Api/Model/Languageforge/Lexicon/Command/LexCommentCommands.php
src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
src/Api/Model/Shared/ActivityModel.php
src/Api/Model/Shared/Command/ActivityCommands.php
src/Api/Model/Shared/Dto/ActivityListDto.php
test/php/model/shared/commands/ActivityCommandsTest.php
test/php/model/shared/dto/ActivityListDtoTest.php

This adds activity log entries for:
* Comment likes
* Status changes (todo / resolved / open) on comments
* Replies to comments
* Editing comments or replies
* Deleting comments or replies
Also add comments explaining proper usage of USER and USER2 fields in activity log. One activity type will need to be updated (it currently uses USER and USER2 the wrong way around), which will require a data migration once this goes live. This PR intentionally does not include that change or the data migration script, which will be submitted in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/316)

Add activity log for more comment activity

---

src/Api/Model/Languageforge/Lexicon/Dto/LexBaseViewDto.php
src/Api/Model/Shared/Command/SessionCommands.php
src/Site/views/languageforge/container/languageforge.html.twig
src/Site/views/languageforge/theme/default/sass/_global.scss
src/angular-app/bellows/apps/public/forgot_password/forgot-password-app.module.ts
src/angular-app/bellows/apps/public/link_oauth_account/link-oauth-account-app.module.ts
src/angular-app/bellows/apps/public/login/login-app.module.ts
src/angular-app/bellows/core/core.module.ts
src/angular-app/bellows/core/navbar.controller.ts
src/angular-app/bellows/shared/interface-language.component.html
src/angular-app/bellows/shared/interface-language.component.ts
src/angular-app/bellows/shared/model/project-settings.model.ts
src/angular-app/languageforge/lexicon/lexicon-app.component.ts
src/angular-app/languageforge/lexicon/shared/model/lexicon-project-settings.model.ts
test/app/languageforge/lexicon/settings/semantic-domains.e2e-spec.ts
test/php/model/languageforge/lexicon/dto/LexBaseViewDtoTest.php
test/php/model/shared/commands/SessionCommandsTest.php

- refactor for better separation-of-concerns for the interface language picker
- enable interface language picker in bellows apps
SF and LF E2E tests both passing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/320)

Transifex language picker working for Bellows apps

---

src/angular-app/bellows/apps/activity/activity-container.component.html
src/angular-app/bellows/apps/activity/activity-container.compontent.ts

PR (NEW) addresses the following:
Updated activity summary to not include how many entries were updated when viewing activities from a specific entry
Fixed a bug where it showed entries even if there were no updates made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/331)

Activity feed tweaks

---

src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexExample.php
src/Api/Model/Languageforge/Lexicon/LexPicture.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
src/Api/Model/Scriptureforge/Sfchecks/QuestionModel.php
src/Api/Model/Shared/Mapper/MapperModel.php
src/Api/Model/Shared/Mapper/MapperUtils.php
src/Api/Model/Shared/Mapper/MongoMapper.php
src/Api/Model/Shared/Mapper/ObjectForEncoding.php
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
test/php/model/shared/mapper/MapperUtilsTest.php

This is the backend code that should enable https://github.com/sillsdev/web-languageforge/pull/209 to work: the Mongo mapper can now be told about some properties and subproperties (properties of properties) that should be treated with special care to match up the "old" values to the "new" values. For any order-sensitive properties, instead of matching the updated data from the frontend by index, it will match by a key contained in the data ("guid" by default), and reorder the data in Mongo before applying the normal update code.
The classic case is a lexical entry whose senses are being edited. Consider an entry with senses A, B and C. The user has created a new sense D, deleted sense B, and re-ordered the senses so that their order is now D, C, A. Furthermore, he has edited the meaning …

Mongo mapper can now rearrange items

---

src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-example.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-example.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/shared/editor.page.ts
test/app/languageforge/lexicon/shared/editor.util.ts
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php

Reordering senses and examples in the UI is functional and the e2e tests pass. The PHP test, however, is failing, and there appear to be issues with GUIDs changing due to reordering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/209)

Reordering senses and examples

---

src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts
src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts
webpack.config.js

If S/R results in a recoverable error, we now display a more specific error message and take the user back to the new-project page. For non-FLEx projects and if the user is not authorized to access the project on LanguageDepot we delete the project from Mongo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/337)

 Improve S/R error handling

---

src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts

When the user tries to create a project that doesn't have any data
on LanguageDepot yet, we display an error message. We also have to
remove the project from the mongo database again so that when there
is data on LD the project gets created with the correct writing
systems and settings. Otherwise we will end up with a mismatch
between LD and LF.
This change adds the "delete from mongo" part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/339)

Delete project when trying to s/r empty project

---

test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php

A second is a million microseconds, not a thousand.
Also updated the code so it won't have to do the multiplication more than once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/345)

Fix timeout in WaitForFileExist

---

src/Api/Model/Shared/Command/ActivityCommands.php

This was left out through simple omission, not by design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/351)

Mark activity unread when entries are updated

---

src/Api/Model/Shared/ActivityModel.php
src/angular-app/bellows/apps/activity/activity-container.component.html
src/angular-app/bellows/apps/activity/activity-container.component.ts

Also moved two activity types to the correct section (visual change only; no code effects, but it was easy to miss them because they were in the wrong grouping).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/358)

Include "delete comment/reply" in valid-activities list

---

src/angular-app/languageforge/lexicon/lexicon-app.component.ts

- this fixes a race condition bug in Field Configuration settings
because it relies on users being populated before config is. The
proper fix is a single DTO (but not right before shipping).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/359)

Ensure users is loaded before config in lexicon app

---

deploy/vagrant_xenial_gui/Vagrantfile

* Don't keep initial insecure keypair for ssh access.
* At provision time, delete and re-generate host keys until handled in
the base box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/368)

Enhance vagrant security

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

Safari does not support `AudioContext` without vendor prefixing. This PR adds the user of the Webkit vendor prefix.
Audio recording is now supported in Safari 11+. Safari <=10 does not support `getUserMedia()`.
I tested this on BrowserStack and it appeared to work. Sound recording is, however, silent when done through BrowserStack. If anyone has an opportunity to test this in Safari 11+ that would be even better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/371)

Fix audio recording issue on Safari

---

src/Api/Model/Shared/Command/UserCommands.php
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/semdomtrans/views/edit.css

Display RTL scripts on the right hand side of the compact list view.
This supersedes PR #372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/381)

 Fix RTL in compact list view (LF-184)

---

deploy/virtualbox_xenial_gui_creation/Vagrantfile
deploy/virtualbox_xenial_gui_creation/instructions.md

This fixes two issues:
- Code in the instructions file was run together (see [the previous version rendered](https://github.com/sillsdev/web-languageforge/blob/b9295dd5db7b0d159dae8dbc02b1e5ff24b57d57/deploy/virtualbox_xenial_gui_creation/instructions.md)).
- The hostname of the creation box being `vag-u1604-xf-creation` caused issues because later the box hostname would be `vag-u1604-xf`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/395)

Fix hostname of Vagrant creation box and formatting of instructions

---

gulpfile.js

I introduced this issue more than a year ago when fixing other issues related to shelling out. It was supposed to trim `\n` characters off the end of each line before logging it, but it operated with the incorrect assumption that every piece of data that came its way ended with a newline character (which may have incidentally been correct at the time). This resulted in lines that said "WAR" instead of "WARN" or "np" instead of "npm". It also appears to have split lines that were not supposed to be split up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/394)

Fix truncated lines in Gulp output

---

src/SIL.XForge.Identity/Controllers/Account/ResetPasswordViewModel.cs

Fixed the issue by removing maximum length and setting minimum length 7 characters for Password and Conform Password.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/417)

SF-68 Reset password page should accept only 7+ character passwords and maximum limit needs to be removed

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs

* String.Equals isn't supported by the LINQ Translator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/436)

Fix unsupported filter exception on e-mail check

---

src/SIL.XForge.Identity/Controllers/Account/RegisterViewModel.cs
src/SIL.XForge.Identity/Views/Account/ForgotPassword.cshtml
src/SIL.XForge.Identity/Views/Account/Register.cshtml
src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml
src/SIL.XForge.Identity/wwwroot/css/site.css
src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml

Fix: SF-79 "Email Address" label should not move along with password strength
* Fixed the problem - moving the email label control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/421)

Fix: SF-79 "Email Address" label should not move along with password 

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs

FIX: SF -69 Reset password page does not returns with information message pop up.
Once Reset password been updated, alert message be thrown to login page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/419)

Fix: SF-69

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/change-password/change-password.component.scss

* Changed CSS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/438)

Fix: SF-85 UI is collapse on Change Password page at mobile view port

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
src/SIL.XForge.Identity/Controllers/Account/ResetPasswordViewModel.cs
src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml
test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs

- check token and expiry before honoring the the final reset request
- invalidate the reset token following a successful login (the user obviously remembers the forgotten password)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/428)

SF-67: reset password loopholes

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
src/SIL.XForge.Identity/Controllers/Account/ResetPasswordViewModel.cs
src/SIL.XForge.Identity/Views/Account/ResetPassword.cshtml
test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs

- not all users have a username (email is key)
- prevents discovering usernames through an alphabet attack on reset keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/448)

Remove Username from Reset Password model

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
src/SIL.XForge.Identity/Controllers/IdentityController.cs
src/SIL.XForge.Identity/Services/UserResourceOwnerPasswordValidator.cs
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts
src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
src/SIL.XForge/Models/UserEntity.cs
src/SIL.XForge/Models/UserResource.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
test/SIL.XForge.Identity.Tests/Controllers/IdentityControllerTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- add a canonical email property to user
- use canonical email for querying
- use normal email for display and sending emails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/447)

SF-86: Duplicate eMail is accepting on Sign up

---

src/SIL.XForge.Identity/Controllers/Account/AccountController.cs
src/SIL.XForge.Identity/Controllers/IdentityController.cs
src/SIL.XForge.Identity/Models/SendInviteParams.cs
src/SIL.XForge.Identity/Models/SendInviteResult.cs
src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
src/SIL.XForge.Scripture/ClientApp/src/identity/identity.service.ts
src/SIL.XForge.Scripture/ClientApp/src/identity/models/send-invite-params.ts
src/SIL.XForge.Scripture/ClientApp/src/identity/models/send-invite-result.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
test/SIL.XForge.Identity.Tests/Controllers/Account/AccountControllerTests.cs
test/SIL.XForge.Identity.Tests/Controllers/IdentityControllerTests.cs

- fix unit tests
- don't display server messages directly
- use LocationService for siteOrigin
- add join email
- don't send inviter name to back-end
- extract invite dialog to its own component
The only thing it doesn't do yet is add the user to the current project. We need the context of a current project before we can finish this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/465)

SF-31 fixup

---

deploy/vagrant_xenial_gui/Vagrantfile
deploy/virtualbox_xenial_gui_creation/instructions.md

* Fixes running refreshDeps.
* Add a note to more clearly alert user of provisioning problems, and
what to do if so.
* Only pull up to a certain point in the repo, in case a later commit
breaks running the provision script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/449)

vagrant: refreshDeps after ansible

---

.editorconfig
.prettierignore
.prettierrc.yml
.vscode/extensions.json
.vscode/settings.json

- recommend the Prettier extension
- format on save
- update max line length to 98 to match other LSDev projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/470)

SF-58 (Prettier): Format on Save

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/tslint.json

- Install prettier, lint-staged, and husky for SF 2.0
- Define a pre-commit hook to prettier files and stage the updated versions
- Also add command line access to Prettier (under "scripts")
- Configure TSLint to accept single- or double-quoted strings (Prettier will enforce consistency)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/485)

SF-58: Prettier pre-commit hook

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.ts
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- Show a Snackbar notification of any error thrown when creating or updating a user in the SysAdmin User Entry component
- Use constants and `@example.com` in UserServiceTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/559)

SF-61: Let the Admin know if an email address is taken

---

README.md
src/SIL.XForge.Scripture/ClientApp/monitor-test-headless.sh
src/SIL.XForge.Scripture/ClientApp/test-headless.sh

The Angular MDC URI might look a little funny, but I find it slightly confusing to find the API docs if I instead am pointed to https://trimox.github.io/angular-mdc-web/ . Throwing a developer right into one of the API docs for a control may make it more intuitive to find the rest of the documentation (it is for me).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/565)

Update doc, script

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

Fixes a bug reported by @megahirt.
Previously the audio sample rate was hard-coded at 44100. This caused pitch and playback distortions on some machines. This PR bases the sample rate on the rate provided by the AudioContext supplied by the browser.
I've verified that this change still works on my machine, but I haven't actually experienced the audio distortion, so I can't be absolutely certain it fixed the actual problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/569)

Fix audio recording sample rate (LFv1)

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.ts
src/SIL.XForge/DataAccess/MongoRepository.cs
src/SIL.XForge/Services/RepositoryResourceServiceBase.cs
test/SIL.XForge.Tests/DataAccess/MemoryRepository.cs
test/SIL.XForge.Tests/Services/ResourceServiceTestEnvironmentBase.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- If an insert or update fails (due to a conflict), throw status 409 (Conflict)
- Check caught exceptions' status codes; rethrow if not 409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/571)

SF-61: catch only DuplicateKey exceptions in sa-user-entry

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-segmenter.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs
src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs

- Chrome does not break on em-spaces
- Use spaces inside of an inline embed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/584)

Enable proper breaking of consecutive blank verses

---

src/angular-app/bellows/shared/sound-player.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts

Previously the audio recorder would remain open when switching between dictionary entries. This commit fixes the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/593)

Close audio recorder when switching entry (LFv1)

---

.gitignore
src/angular-app/bellows/shared/palaso-ui.scss
src/angular-app/scriptureforge/sfchecks/project/project-settings.html
src/angular-app/scriptureforge/sfchecks/project/project.html
src/angular-app/scriptureforge/sfchecks/sfchecks.scss
src/angular-app/scriptureforge/sfchecks/text/question.html
src/angular-app/scriptureforge/sfchecks/text/text-settings.html
src/angular-app/scriptureforge/sfchecks/text/text.html

This PR implement basic right to left support in Scripture Forge using HTML's `dir="auto"`.
SF e2e tests are passing.
Below are some screenshots showing major changes (this is not exhaustive):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/594)

Right to left support in Scripture Forge (SFv1)

---

LICENSE.txt
README.md

Previously the text of the GPL was included where the LGPL should have been. Also, a link to the LGPL  was actually a link to the GPL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/595)

Fix references to LGPL

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

This commit reduces the audio recording gain from 10 to 1, which also eliminates the need to implement clipping.
Work on this was delayed a bit when I discovered an audio recording related bug and attempted to fix it. The audio recorder persists when switching between dictionary entries. That bug has proved to be somewhat more difficult to repair than I anticipated, and I am still working on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/592)

Reduce audio recording gain from 10 to 1 (LFv1)

---

src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html

This is a tiny fix to a bug I encountered while trying to reproduce another bug. The username field on the admin page should be editable when creating a user, but not when editing a user. Previously the functionality was exactly the opposite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/604)

Fix admin page username field state (xFv1)

---

src/Api/Library/Scriptureforge/Sfchecks/SfchecksReports.php

Previously the reports would throw an exception if a user didn't have email. The report generator also assumed users marked as "active" are actually active (it actually just means they can log in). This commit changes it to instead check whether they have ever logged in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/603)

Fix SF reports when user has no email (SFv1)

---

src/angular-app/bellows/core/offline/editor-data.service.ts

Replaces the use of Intl for sorting strings when Intl is not defined. Sorts instead based on Unicode value by simple string comparison (`"apple" < "cow"` in JavaScript). [According to MDN,](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) "Strings are compared based on standard lexicographical ordering, using Unicode values."
I've tested this on an older iPad with Safari 9.x, and it works correctly. Searching entries does not seem to work (every word is a result whether it matches or not), but I don't think that is related to this PR. Also search not working in an older browser is a much less critical issue than the entire page being broken due to an error, which is what this PR is fixing.
---
This change is [<img …

Fix lexicon editor in Safari < 10 (LFv1)

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/634)

Flush active edit buffer on dispose in translate metrics

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.ts

----
I'm still working on the parent issue, but this fixes a problem encountered along the way. It looks from Connection.cs like it's okay for `type` to be null, so I modified realtime-doc.ts to handle that possibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/639)

SF-233 Handle null doc types

---

src/angular-app/bellows/core/offline/lexicon-comments.service.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts

This issue was caused by `this` referring to the wrong object (possibly starting in 6345e3f4ed27b74c54b51bdbe1395e30557f7bc9). The view calls a function that is a property of the component, but the function is actually defined in the comment service (in the component we have `getEntryCommentCount = this.commentService.getEntryCommentCount`). When AngularJS calls the function it uses the wrong context (most likely the context of the component). When the function references `this.comments` it is undefined.
Because this type of bug is so easy to create I think we should consider whether all methods should be written using arrow functions so `this` will have lexical scope. It's not the default TypeScript syntax, but it is safer and actually more "correct."
The two main ways of writing methods …

Fix missing comment indicator in LF entry list (LFv1)

---

src/Api/Model/Scriptureforge/Sfchecks/Dto/QuestionCommentDto.php
src/Api/Model/Scriptureforge/Sfchecks/Dto/QuestionListDto.php
src/Api/Model/Scriptureforge/Sfchecks/SfchecksProjectModel.php
src/angular-app/scriptureforge/sfchecks/project/project-settings.html
src/angular-app/scriptureforge/sfchecks/text/question.html
src/angular-app/scriptureforge/sfchecks/text/text.html

This adds two new project properties which are editable by managers on the project properties tab:
The font size property controls the font size for all texts in the project, and controls the font size for the left-hand text column (not user-selected quotes).
The RTL property specifically sets the dir="rtl" for the text columns in both the text view and the question/comment view, and also sets dir="rtl" for the scripture quotation divs when user's include a quote in their answer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/647)

[SFv1] Add project-level font size and RTL script options.  This completes the RTL fix from earlier.

---

src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js

* remove retries (it just fails slower on TC)
* always use browserDisconnectTimeout and browserNoActivityTimeout values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/653)

Improve TC unit tests when run locally

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

My original plan was to hang on to the microphone until the recording component was closed. However, after experimenting a bit I found that hanging onto it after the recording stops has no advantages, and was even slightly more complicated to implement.
At present the audio recording indicators of Chrome and Firefox (only tested browsers) only show up when the user is actually recording an audio segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/658)

Release microphone when done recording (LFv1)

---

src/angular-app/bellows/shared/sound-player.component.html
src/angular-app/bellows/shared/sound-player.component.ts

Due to a bug on the config page I wasn't able to test this locally. I did see it in production though.
The actual cause of the bug is an incorrect assumption that only one sound player is present on the page. Given the simplicity of the bug, I don't think it's a problem that I wasn't able to test it with multiple sliders locally. Since it works with one I can be reasonably confident it will work with multiple. At the very least it shouldn't be a regression.
EDIT: The branch name is definitely incorrect. It should be audio player, not audio recorder. Unfortunately there's not simple way to rename it at this point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/6 …

Fix bug with multiple audio players (LFv1)

---

src/Api/Model/Shared/Dto/ManageUsersDto.php
src/Api/Model/Shared/InviteeListProjectModel.php
src/Api/Model/Shared/ProjectModel.php
src/angular-app/bellows/apps/usermanagement/members.component.html
src/angular-app/bellows/apps/usermanagement/user-management-app.component.ts
src/angular-app/bellows/apps/usermanagement/user-management.scss
test/php/model/scriptureforge/Sfchecks/dto/ProjectSettingsDtoTest.php

These are fairly straightforward changes. On the back end it adds an invitees list to the user management DTO. On the front end it lists them after active users on the user management page.
This UI has the disadvantage of listing email under the username header when no username is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/645)

[LFv1] List invited users on user management page

---

src/angular-app/bellows/shared/list-view.component.html

All I can say is this bug took longer to solve than it should have.
Pagination now works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/662)

[xFv1] Fix broken pagination

---

src/angular-app/bellows/core/offline/lexicon-comments.service.ts
src/angular-app/languageforge/lexicon/editor/comment/comment-bubble.component.ts

This PR fixes a race condition that I believe is the cause of disappearing comments. I don't fully understand exactly how this race condition happens sometimes but not other times, but it does appear to be the cause when we do see the bug.
This is a companion pull request to #665.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/664)

Fix race condition in setContextGuid that caused comments disappear (LFv1)

---

webpack.config.js

I believe this is all that is required to enable sourcemaps in production, assuming the command for building the TypeScript for production is `gulp build-webpack --applicationName languageforge --doNoCompression false`.
In addition to helping us locate the source of bugs, I'm guessing it will also help Bugsnag to correctly group errors, which it is currently doing quite poorly.
When the sources are uploaded to production the .map files need to go along with them. I don't see them listed in either upload-exclude.txt or upload-include.txt, which I am guessing are used in the deploy process.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/679)

Enable sourcemaps in production build

---

src/angular-app/languageforge/lexicon/lexicon-app.component.ts

I first noticed this error locally and then also recognized it as one of the errors on Bugsnag. (It was causing `Cannot set property 'textContent' of null`).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/680)

Fix console error that occurs when going offline

---

src/angular-app/bellows/apps/usermanagement/members.component.ts

Fixes the message shown when changing an invited user's role on a project.
Old message: "undefined's role was changed to observer_with_comment"
New message: "user@example.com's role was changed to Observer with comment."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/691)

Fix message when changing role of invited user

---

src/angular-app/languageforge/lexicon/editor/editor.component.html
src/angular-app/languageforge/lexicon/editor/editor.component.ts

- These buttons navigate to the next and previous entry in the order they are listed (they're not history buttons). If entries are sorted and/or filtered, the buttons navigate through the sorted/filtered version of the list.
- On medium displays the text for the show/hide extra fields button is now hidden. This makes room for the new buttons.
- The status text to the left of the save button is now gone. All the same information is now directly on the save button.
Small display:
Medium display:
Large display:
Trello: https://trello.com/c/ioYzPULU/361-next-previous-arrow-buttons-to-browse-entry-list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/693)

Add next entry and previous entry buttons

---

src/Site/Controller/Base.php
src/Site/views/shared/container/container.html.twig

This adds support for the HelpHero tutorial walk throughs described at https://app.helphero.co/install?type=async-html
This is the HTML snippet method.  If we had a single page app for the entire site, then we would use the npm install method.  We could still use npm install and link locally, however linking to their CDN is a good first step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/689)

add HelpHero JS snippet

---

src/angular-app/bellows/core/api/project.service.ts

This removes the link to create a new Translate app project on scriptureforge.org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/688)

Remove access to v1 translate app

---

scripts/server/backup/doBackupsAndRsyncToPalasoBackupServer.sh

This reflects the current state of the script on the production server.  At some point the script was changed to do the archive-rotator function on the backup server instead of the production machine.  This change saves space on the production server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/690)

update backup and rsync script

---

src/Site/views/shared/container/container.html.twig

This bug made loading pages impossible if you were not logged in (including loading the login page).
Unfortunately none of us caught it before it was on master because (presumably) we didn't think to log out and back in again.
Getting the e2e tests working again should probably be a priority.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/700)

Fix "Variable userId does not exist" bug

---

src/angular-app/languageforge/lexicon/lexicon-app.component.ts

This fixes a race condition where the project data might finish loading before the project config is loaded, which results in it looking empty because the lexicon-entry renderer depends on the project config being populated. Now we load the initial project data only after the config is completely loaded, which should ensure that it's always ready to render as soon as it loads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/701)

Fix blank lexicon entries on first load

---

src/Api/Model/Shared/Mapper/JsonEncoder.php
test/php/model/shared/mapper/json/JsonDateMapperTest.php

Safari parses timestamps strictly according to [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6), which requires a colon in the timezone (`"+07:00"`, not `"+0700"`). The default ISO8601 format codes in PHP use `"+0700"` format, so we need to change how we encode dates in JSON so that Safari (and other strictly-compliant browsers, like Safari Mobile) accept the dates the server returns.
Tested in BrowserStack and confirmed to work: with this change, the activity log shows up properly in Safari.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/706)

Fix activity log not showing in Safari

---

src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/shared/configuration.page.ts

Tests were expecting input system checkboxes to all start unchecked, but now they all start checked. This required adjusting expectations for initial state in the following tests:
- check Apply button is enabled on changes
- can fully function "Select All" down the Input System observer column
- can select and de-select all down the Input System commenter column
- can select and de-select all down the Input System contributor column
- can select and de-select all down the Input System manager column
- can fully function "Select All" along an Input System row
Also, some modals were occasionally being slow to appear, resulting in spurious test failures, so we just wait for them before proceeding with the tests. Timing issues were fixed in:
- can open the custom field modal for an entry …

Fix E2E tests for input systems

---

src/angular-app/bellows/core/exception-handling.service.ts

Should fix LF-222, and possibly reveal some bug reports that we'd been missing before (because when `this.metadata` was non-null but `this.metadata.userName` was null, the original exception was swallowed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/707)

Report bugs to Bugsnag even if username is null

---

src/angular-app/languageforge/lexicon/lexicon-app.component.ts

On some computers, upon loading the entries in a project, the entries list returned blank. See the following screenshot of the issue:
There was a race condition between `lexProjectService.users()` and `loadEditorData()` within `$onInit()` in `LexiconAppController`. I restructured `$onInit()` to ensure that `loadEditorData()` always runs _after_ `lexProjectService.users()` finishes. 
See [the trello card](https://trello.com/c/Os5YtuQI/368-on-startup-empty-entries) for more technical details.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/725)

Fixed the empty entries bug

---

deploy/playbook_bionic.yml

Ubuntu 18.04 systemd uses /tmp isolation by default, which means every process gets its own private /tmp folder. Since our php e2e tests run in two processes (a setup script and then the actual tests), the actual tests cannot access the needed tempfiles when /tmp isolation is enabled, causing tests--like file upload tests--to always fail.
Disabling this feature is less secure, but since we only ever need to run these tests on dev machines and never on the production box, this is a safe solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/727)

Disable systemd /tmp isolation for dev machines

---

deploy/playbook_bionic.yml

The lfmerge package has been commented out in the ansible installer because the package had not been deployed yet to Ubuntu 18.04 Bionic yet. It is now available on Bionic, so I am un-commenting lfmerge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/728)

Re-enable lfmerge package in ansible installer

---

test/app/bellows/projects.e2e-spec.ts

E2E tests for #720 
Tests added:
- Admin accessing project they are not a member of should take them to the project
- User accessing project they are not a member of should take them to the projects list
There are ~7 tests related to file uploading that still fail, but all others should pass. 
Trello: https://trello.com/c/5Ugulre2/386-e2e-test-for-accessing-project-without-membership
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/729)

E2E tests for project accesses without membership

---

deploy/playbook_bionic.yml

When running the Ansible install script after it has already been initially run, it still builds PECL Mongo, which takes an exorbitant amount of time to complete. This PR adds a check that will skip the PECL Mongo install if it is already present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/737)

Skip PECL Mongo compile if already installed

---

test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts

The autosave feature altered a test that was not expecting data to persist. After adding data to a field, it now needs to be sanitized before the test concludes in order to pass future tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/735)

Santize input altered during comment E2E tests

---

src/Api/Library/Shared/Communicate/CommunicateHelper.php
src/Site/Controller/Base.php
src/Site/Controller/Page.php

Composer updates included bringing Twig to 2.11.3. In Twig 2.7, Twig refactored it's namespaces and classes, deprecating the old names. This PR refactors our code to be Twig >2.7 complaint.
The E2E tests did catch the errors when attempting to sign up as a new user, but it was caught as a timeout error rather than as an exception. Aside from those addressed in #735, all tests pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/736)

Update Twig code to be >2.7 compatible

---

.vscode/extensions.json
.vscode/launch.json
README.md
browserStackE2E.sh
deploy/playbook_bionic.yml
deploy/vars/config_developer.yml
gulpfile.js
installer/ubuntu1604Installer.sh
installer/windowsHostFileAdditions.txt
rune2e.sh
scripts/server/mongodb/copyServerToLocalChris.bat
scripts/tools/FactoryReset.php
src/Api/Library/Shared/WebsiteInstances.json
src/Site/Provider/AuthUserProvider.php
test/app/browserstackConf.js
test/app/chromeDirectHeadlessLFProtractorConf.js
test/app/chromeDirectLFProtractorConf.js
test/app/protractorConf.js
test/app/setupTestEnvironment.php
test/app/testConstants.json
test/php/TestConfig.php
test/php/model/shared/UserModelTest.php

The `.localhost` TLD is recognized by browsers and systems for localhost use while our use of `.local` is not.  This change across the entire code-base changes all references from `.local` to `.localhost`
Once this PR is merged, ***developers may need to run ansible and FactoryReset.php again*** before the site is operational again.
The PR also removes references to:
dev.languageforge.local
dev.scriptureforge.local
demo.*
as these are no longer in use.
The site will now be accessed at http://languageforge.localhost
All PHP Tests are passing and all but the 3 E2E tests that are known to fail are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/734)

Change to use languageforge.localhost

---

scripts/server/elasticSearch/setupElasticSearchCATIndex.sh
src/Api/Model/Shared/Translate/Dto/TranslateMetricDto.php
src/composer.json

GeoIP is no longer being used in this project. One of the PHP Unit tests was failing due to a missing GeoIP file,  `/usr/share/GeoIP/GeoLite2-City.mmdb`, so this PR deletes all straggler references to GeoIP. All of the PHP unit tests are passing after this change except the following, which was already broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/743)

Remove GeoIP references

---

deploy/playbook_bionic.yml

In Ansible scripts, `become_user: www-data` will be ignored unless `become: yes` is set prior to it. This PR adds `become: yes` to the PHP unit tests in the `playbook_bionic.yml` script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/744)

Add become:yes to make PHP tests run as www-data

---

deploy/playbook_bionic.yml
developerInstall.sh

Sometimes, the `playbook_bionic.yml` script may be wanted for setups other than specifically a developer machine, such as a build agent. Some steps in this script are not needed in such cases. PR adds the following features:
- `developer` tags to exclusively developer install tasks so that they can be easily skipped
- a `developerInstall.sh` script that builds a bare machine specifically into a dev machine from the ground up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/742)

Create a developer install script

---

src/Site/Controller/App.php
src/Site/views/languageforge/container/languageforge.html.twig

**Problem**: An LF user [suggested](https://community.software.sil.org/t/request-walk-through/2322) that we add a link within the Help menu to start the Lexicon tour. 
**Solution**: This is achieved through HelpHero's linked tour start (a HelpHero generated URL that redirects to the homepage of the tour and starts it) inserted into the LF HTML template. 
**How to Test Locally**: The HH URL is hashed, in part, by the path of the tour's homepage. Because we have set the tour to only run on production, an attempt to start the tour from `.localhost` will redirect to the live site, require authentication, and then link to a project that does not exist. In order to test the tour locally, go into the HelpHero Editor in Chrome on an https of `.localhost`. Navigate to Lexicon (LF) tour and remove …

Adds "Start Language Forge Tour" to the Help menu

---

src/composer.lock

A more detailed env dump was added to web-php-utilities, so this PR updates the commit hash in `composer.lock` to get the latest.
In addition, the `geoip2 ` module was not removed from the lockfile yet, so this PR removes that too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/745)

Upgrade sillsdev/web-php-utilities

---

src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php

When running the PHP unit tests on the build agent (and only on the build agent) one 7z related test always failed (see below). This PR resolves the error and all PHP unit tests are now passing on the build agent.
It turns out that the system was falling back to a non-UTF-8 encoding. Since the files in question in the unit test contained non-Roman characters, these characters got mapped to `?`'s during the unzipping process. `LiftImport` was prefixing the `7z` command with `LANG=en_us.UTF-8` with the goal of setting a UTF-8 encoding. This works on most systems since `en_us` is so common. On minimal installs (like the build agent), the `en_us` locale may not be installed, so the system falls back to the `C` locale (not `C.UTF-8`). The `C.UTF-8` encoding exists on every system, so changing …

Use C.UTF-8 to ensure non-Roman script filenames are retained during unzipping

---

src/Api/Library/Shared/SilexSessionHelper.php
src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
src/Api/Model/Languageforge/Lexicon/LexRoles.php
src/Api/Model/Shared/Command/ProjectCommands.php
src/Api/Model/Shared/Dto/ManageUsersDto.php
src/Api/Model/Shared/Rights/ProjectRoles.php
src/angular-app/bellows/apps/projects/projects-app.component.html
src/angular-app/bellows/apps/projects/projects-app.component.ts
src/angular-app/bellows/apps/usermanagement/members.component.html
src/angular-app/bellows/apps/usermanagement/members.component.ts
src/angular-app/bellows/apps/usermanagement/user-management-app.component.ts
src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts
src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts
src/angular-app/scriptureforge/sfchecks/project/project-settings.controller.ts
test/app/bellows/projects.e2e-spec.ts
test/app/bellows/shared/projects.page.ts
test/app/bellows/shared/user-management.page.ts
test/app/bellows/user-management.e2e-spec.ts
test/php/model/shared/commands/ProjectCommandsTest.php

**Problem:**
In order to troubleshoot, devs are often added to projects in order to solve issues. When accessing projects, admins are added to those projects as Managers. This can create confusion.
**Solution:**
To solve this problem a Tech Support user was implemented that is effectively a clone of the manager role. It is implemented throughout the front and back ends. On the user management app, a Tech Support user is the only one who can change their own role, it is locked to anyone else. Further, there is no way for a user to assign another user to Tech Support. Currently the only way to become Tech Support is to click the "+ Tech Support" button as an admin from the projects app or attempt to access a project you are not of member of whilst being logged-in as an admin. The role is …

Tech Support Role

---

test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php

Our PHP tests fail periodically with one failing test having to do with LFMerge pid file check.  This PR attempts to make this test a reliable one again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/749)

add clearstatscache() to fix lfmerge pid test race condition

---

src/angular-app/bellows/polyfills.browser.ts

A lot of the most common errors in Bugsnag are from `Array.includes` being undefined in IE11 and UC Browser. A few days ago proximately 2/3 of the events from the top ten errors on Bugsnag were due to this.
I also alphabetized the list of polyfill imports to make TSLint happy. The _only_ substantive change is adding the last line in the file.
I've tested in IE11 and verified that `Array.prototype.includes` is defined and works as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/755)

Add Array.includes polyfill to fix lots of Bugsnag errors

---

buildagentInstall.sh
deploy/hosts
deploy/playbook_bionic.yml

Do you need to set up a new build-agent? Wouldn't it be nice if you could have a script that just ran and built it from the ground up? This PR adds such a script. It also adds some tweaks to the `playbook_bionic.yml` script and `hosts` file to make it easier to isolate when running to configure a build-agent.
The script is assumed to be run on a box that is already configured as a build-agent. The shell script runs two separate ansible playbooks:
1. `playbook_bionic.yml --skip-tags "developer"`
This sets up the machine environment for xForge v1.
2. `playbook_buildagent.yml` (from the private repo)
This sets up the machine to be an xForge v1 buildagent.
--- …

Create a build-agent shell script

---

src/Api/Model/Shared/Command/SessionCommands.php
test/php/model/shared/commands/SessionCommandsTest.php

The current testing infrastructure copies data to `tmp/jsonSessionData` in order for it to be accessed externally. This is no longer a need and thus references to `jsonSessionData` are extraneous. This PR removes all related code. All PHP and E2E tests pass.
**PHP**:
**E2E**:
[Trello card](https://trello.com/c/lksCxYVL/398-remove-jsonsessiondata-from-tmp-dir-usage)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/750)

Remove references to temp/jsonSessionData

---

src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor-list.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/editor.module.ts

Previously the optionLists data wasn't making it all the way to the dc-rendered component, so the component couldn't look up proper abbreviations for parts of speech and had to resort to using the key instead. This was mostly invisible for projects that had an English language user interface, but for non-English interfaces the English part-of-speech abbreviations were being wrongly shown. Fixed.
This should fix https://jira.sil.org/browse/LF-319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/756)

Rendered entries now show correct part of speech

---

src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts

One of our `null` tests was one line *after* where it needed to be.
Should fix https://jira.sil.org/browse/LF-318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/754)

Fix one reason for "Cannot read property 'data' of undefined" error

---

package-lock.json
package.json

This PR forces angular-* modules to match the version of angular, which should solve the "lowercase is not a function" error that was sometimes showing up. The cause is that between Angular 1.6 and 1.7, they removed the long-deprecated angular.lowercase function, which some code (including angular-sanitize) had been depending on. This means that the 1.6 to 1.7 upgrade is a breaking change, which means that it's not safe to use a package version like "^1.6.10" for the angular-sanitize module, because that will pull in 1.7.x (since npm thinks that angular is following SemVer). The angular-* modules need to be the same version as angular to be safe, so we use "1.6.10" instead of "^1.6.10" in the angular-sanitize version in package.json.
See also …

Solve the "lowercase is not a function" error loading Angular

---

.vscode/settings.json
src/Api/Model/Shared/Command/ProjectCommands.php
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Model/Shared/InviteToken.php
src/Api/Model/Shared/ProjectModel.php
src/Api/Service/Sf.php
src/Site/Controller/App.php
src/Site/Controller/Validate.php
src/angular-app/bellows/apps/projects/projects-app.component.ts
src/angular-app/bellows/apps/public/login/login-app.component.html
src/angular-app/bellows/apps/public/login/login-app.component.ts
src/angular-app/bellows/apps/public/login/login-app.module.ts
src/angular-app/bellows/apps/public/login/login.html
src/angular-app/bellows/core/notice/notice.component.ts
src/angular-app/bellows/core/notice/notice.service.ts
src/composer.json
src/composer.lock
src/index.php
test/php/model/shared/commands/ProjectCommandsTest.php

**Overview:**
In order to better support users without emails and to streamline project sharing, it was determined that we should allow project managers to create invite links, which, upon accessing, add a user to a project with a specified role. This PR includes all of the back-end support for this link sharing. It includes three major partitions:
**1. Creation and management of share link:**
There are three new API calls related to the shareable link
- `'project_getInviteLink', [defaultRole]: link<string>`
- Takes a roleKey and returns the invite Url
- `'project_disableInviteToken', []: void`
- Makes the inviteToken an empty string, thereby disabling it
- `'project_updateInviteTokenRole', [newRole]: void`
- Given a roleKey will update the role a user is assigned when joining via the …

Back end for link sharing

---

rune2e.sh
src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/bellows/core/utility.service.ts
src/angular-app/languageforge/lexicon/core/lexicon-editor-data.service.ts
src/angular-app/languageforge/lexicon/core/lexicon-utility.service.ts
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor-list.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/editor.module.ts
src/angular-app/languageforge/lexicon/editor/field/dc-rendered.component.html
src/angular-app/languageforge/lexicon/lexicon-app.component.html
src/angular-app/languageforge/lexicon/lexicon-app.module.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/shared/editor.page.ts

The improved lexicon search/filter is mostly complete and all e2e tests are passing.
Description | Before | After
-------|------|-----
When all entries are being shown | ![Screenshot from 2019-08-02 15-03-17](https://user-images.githubusercontent.com/6140710/62392896-b28da700-b536-11e9-9977-667fcf76fed7.png) | ![Screenshot from 2019-08-02 15-01-36](https://user-images.githubusercontent.com/6140710/62392849-807c4500-b536-11e9-9116-1bc1befb6642.png)
When searching for entries | ![Screenshot from 2019-08-02 15-04-55](https://user-images.githubusercontent.com/6140710/62393118-43fd1900-b537-11e9-8f31-0cfae833fb04.png) | ![Screenshot from 2019-08-02 15-07-49](https://user-images.githubusercontent.com/6140710/62393141-5bd49d00-b537-11e9-8467-eebd4f28c987.png)
Filtering options || ![Screenshot …

Lexicon search/filter

---

src/angular-app/bellows/apps/public/login/login-app.component.html
src/angular-app/bellows/apps/public/login/login-app.component.ts
src/angular-app/bellows/apps/public/login/login.html
src/angular-app/bellows/apps/public/signup/signup-app.component.html
src/angular-app/bellows/apps/public/signup/signup-app.component.ts

Before | After
-----|-----
- Fixes "Login" being on the page twice
- Fixes stretching of "Continue with Facebook" button
- Autofocuses first input on login and sign up pages
Should "Continue with Facebook" be on the sign up page? Right now we just have the option to sign in with Google.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/761)

Remove double title on login page and autofocus username input

---

src/Site/OAuth/FacebookOAuth.php
src/angular-app/bellows/apps/public/login/login-app.component.html
src/angular-app/bellows/apps/public/login/login.scss
src/angular-app/bellows/apps/public/oauth-signup/oauth-signup-app.component.ts

The login buttons for Google and Facebook now have a consistent look and are compliant with each company's brand-use guidelines (e.g., we use the right shade of blue for each button). As a bonus, we also create the buttons with HTML and CSS instead of PNG images, which means their text can be translated.
Also, I noticed that Facebook avatar URLs were being incorrectly handled in the previous Facebook OAuth code, so I've fixed that. We now produce correct URLs for people's Facebook profile picture, and use that as our default avatar if someone signs up via Facebook OAuth (just like we do for Google OAuth).
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languagefor …

Consistent, translatable login buttons for Google and Facebook

---

src/Site/views/languageforge/container/languageforge.html.twig
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/lexicon-app.component.html
src/angular-app/languageforge/lexicon/lexicon-app.component.ts

(I've mostly moved over to SF, but I can't do much until I get a Paratext account verified. I felt like I was at a stand-still, so I swung back to LF to grab some low-hanging fruit).
These two screenshots show all the changes (though they're not all related).
When offline:
- Font size is now correct
- All of header fades to gray
- Logo isn't lost
On mobile:
- There isn't a scrollbar for the entries anymore (this can't be seen in the screenshots). It's still present on any size larger than Bootstrap's `xs` (extra small).
- There's less padding on the sides
For some reason GitHub is showing the two screenshots at a slightly different size, so if other stuff looks visually different, that's probably why.
Before | After
-----|-----
---
This change is [<img …

Miscellaneous fixes

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

If the user navigated back to the entry list while having the comments panel (or the recent-activity panel) open, coming back from the entry list to an entry would leave a blank space where the comments panel is supposed to be, and it would be impossible to show the comments panel by clicking on the Comments button.
The root cause was that going back to the entry list did not hide the right panel, which meant that `this.rightPanelVisible` was still true inside the editor controller. But most of the controller code assumes that `this.rightPanelVisible` starts out false (as it's set by the constructor). In particular, this means that the `showRightPanel()` function was misbehaving: it saw that `this.rightPanelVisible` was true, so it assumed that there must be an element with the …

Fix blank comments panel when coming from entry list

---

src/config.php.fortest
src/config.php.live

The lines needed in the config for Facebook login were added in 65fdc3b03eec4d28e679e08fff16edf4ebec549b, but only in `config.php`, not `config.php.live`. The result was that when the e2e tests finished running, `config.php` had been modified.
@rmunn, should they also be added to `config.php.fortest`?
Wouldn't it be "more correct" for them to be named `config.live.php` and `config.fortest.php`? At the very least editors would (probably) automatically detect it as PHP, whereas right now VS Code renders them as plain text files. I'm guessing the reason `config.php.fortest` ends with `fortest` is because `.test` would have caused the file to be treated incorrectly.
--- …

Update PHP live config to have Facebook client ID and secret

---

src/Site/views/shared/_global.scss

Edge and IE have an x button to clear text inputs. Since we implement our own we don't want theirs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/769)

Disable x button in IE/Edge inputs

---

test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts

One comment-pane E2E test was flaky because of some details of how the comments pane is animated. They're explained in a comment in the PR, so I won't repeat it here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/768)

Fix flaky comment pane E2E test

---

src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/role-dropdown.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/role-dropdown.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/share-with-others.scss

I've made some changes to the sharing dialog that hasn't been merged into master yet. As such I am setting the base for this PR to `feature/sharingDialog`. Whether actually merging into that branch is the best strategy I leave to others to decide. It could be merged into master after merging that one, or something else.
- Previously only part of each menu item in the role dropdown was clickable, and the cursor wasn’t a hand. I’ve changed it to use an `<a>` tag, which solves both of these problems and makes them act like the other menus we have.
- I added the leftmost icons to the menu. Previously these icons showed only in the button part of the dropdown, after an item was selected. This change is a little more debatable (nothing was actually wrong before), but it was a very easy change, …

[PR to another branch] Improvements to the sharing dialog

---

test/app/bellows/shared/projects.page.ts
test/app/bellows/shared/user-management.page.ts

This is not a good long-term fix since it exercises an app (the user management app) which we no longer expose to the user in our UI and so we'll probably remove it at some point. But in the short term, it gets the E2E tests passing again. In the long term, we should change the `addUserToProject` implementation to use the user's email address and enter it in the new "Share With Others" dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/775)

Fix E2E tests of projects page

---

src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts

It is often happening that there's an invalid `sortBy` parameter in the URL, and our code currently assumes that the URL parameter will always be found in the sort options; when that wasn't happening, the `findSelectedFilter` function was returning null or undefined. Now we check the result first, and only assign it to `entryListModifiers.sortBy` if it is valid.
This passes E2E tests once PR #768 has been merged, and should fix LF-258, LF-259, and LF-283.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/772)

Fix bug where entryListModifiers.sortBy is null

---

src/angular-app/bellows/core/navbar.controller.ts
test/app/bellows/shared/user-management.page.ts
test/app/bellows/user-management.e2e-spec.ts

As with PR #775, this is not an ideal solution since we're exercising a UI element that will probably be removed in the future. But this makes all unit tests green again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/776)

Fix User Management E2E tests

---

src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/core/lexicon-utility.service.ts
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-rendered.component.html

- User-specified fonts applied to entry list on editor page
- Word/lexeme now truncated with ellipsis (this could be controversial, but I think it's better than the current behavior of wrapping and pushing the second line out of the way).
- String values are not set to "[Empty]" if their use is anything other than immediately being displayed in the UI. This means if a value is empty, we pass around the empty string, and only convert it to "[Empty]" for display in the UI.
This does not change how `dc-rendered` works, which is responsible for both the entry preview, and the entry list on the list page. I've started some work on that and made good progress. It was clear, however, that it would take significantly more work, so I wanted to get this PR out there as a start. Also, @megahirt, if …

Custom user fonts on editor page entry list

---

src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
src/Api/Model/Languageforge/Lexicon/LexMultiText.php
test/php/model/languageforge/lexicon/Import/LiftImportTest.php

LiftImport needs to be able to cope with a `<range>` element that doesn't have an `href` attribute, but defines the range inline. Our current code had an assumption that there will always be an `href` attribute, but the LIFT spec (as defined by the RelaxNG schema) [lists `href` as optional](https://github.com/sillsdev/libpalaso/blob/18f9433cdf2808bc0f362eef9ae38e6c8706c8ca/SIL.Lift/Validation/lift-0.13.rng#L537). The code already knows how to parse `<range>` elements defined inline, we just need to make sure we don't assume the presence of an optional attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/778)

Fix LF-372: parse inline LIFT ranges right

---

src/Api/Model/Scriptureforge/Sfchecks/SfchecksRoles.php
src/angular-app/scriptureforge/sfchecks/project/project-settings.controller.ts

This is an attempt to get the current master shippable to Scripture Forge. If there are other issues that would prevent master from shipping to SF, I'm not aware of them.
There are 7 e2e test failures on SF, and quite a bit more on LF. I haven't investigated extremely carefully, but some of them are caused by the change from the user management app to the share dialog. I'm not aware that anything is actually broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/779)

Add SF tech support role

---

upload-exclude.txt

* in src this is empty for testing. The file is only changed on the server so don't overwrite it on deploy upload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/782)

Exclude site wide notices file from upload

---

scripts/tools/csvInsights.php
src/Api/Model/Shared/Dto/ProjectInsightsDto.php

This PR fixes the CSV insights function based upon actual usage with production data.  This PR is for master.  The insights have already been fixed via a hotfix on sf/live.  Additionally, this adds a command line wrapper script to run the CSV insights directly on the command-line without a web interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/787)

Fix CSV Insights and add command-line wrapper

---

scripts/tools/changeSiteName.php
src/Api/Model/Shared/Mapper/MapperModel.php

We used to have a changesitename script, but a few years ago it was integrated into the FactoryReset.php script.  I wanted to have the ability to run just the change site name script, so I am bringing it back in this PR.
One thing I encountered was that changing the sitename updated all of the project modified timestamps, which is not what I wanted.  So this PR also includes a fix for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/786)

changesitename script

---

src/Api/Model/Shared/Mapper/MapperModel.php

Ira spotted a bug after the last PR had already been merged.
Moved the $now outside of the if statement since it could cause the variable to be undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/788)

fix if statement in MapperModel

---

src/angular-app/languageforge/lexicon/core/lexicon-config.service.ts

Many projects don't have anything configured for the Tech Support role, since it was newly added, so those projects end up throwing an exception in the filter() call in removeDisabledConfigFields. And since the filter didn't return true, all fields end up being stripped out. The Tech Support role is supposed to have the same rights as a project manager, so if it's looked for and not found, we give manager rights.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/796)

Fix blank project page for Tech Support role

---

src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts

In some cases, field.inputSystems could end up with at least one undefined value in field-unified-view-model.ts after many user edits. This change should fix that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/797)

Fix bug where editing input systems could fail

---

src/Api/Model/Shared/Dto/ProjectInsightsDto.php

Previously the date object was being constructed with `date_create($event['date'])`.
This always returned false because the format was incorrect. The result was that the number of recent users reported was always 0.
Once this is merged we should also cherry-pick it to sf-live.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/792)

Fix recent users count in project stats

---

src/Api/Model/Shared/Command/UserCommands.php

When the site admin tries to list users, if there is even one user who was in a deleted project but somehow that project was not removed from their membership list, the user list fails to load. This change makes it just ignore that missing project when loading the user list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/801)

Make user list robust against missing projects

---

src/angular-app/bellows/shared/pick-list-editor.module.ts

If the items array for an option list is missing in Mongo (because it was empty and the DB code stripped it out), ensure that the picklist component gets an empty array in this.items instead of undefined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/798)

Ensure picklists can cope with missing input items

---

gulpfile.js
src/Api/Model/Languageforge/Lexicon/Command/SendReceiveCommands.php
src/config.php
src/config.php.fortest
src/config.php.live
test/php/TestConfig.php

It does no harm to send an Authorization: Bearer token to an API endpoint that's not expecting it, so we can put this into place in LF first and then add the API token requirement to the Language Depot API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/799)

Use API token for new Language Depot API

---

deploy/playbook_bionic.yml

This PR adds the apt key for the PHP PPA and change the repo to "main" instead of "release" - this should make the ansible script run successfully now.
A short and simple fix that took several hours to get right.  Sometimes that's how it goes.  I won't merge this PR yet until I have successfully run through the whole setup...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/812)

fix PHP PPA errors

---

.gitmodules

This PR finishes removing the submodule deploy_archive so that you don't get git checkout errors like this:
Alas, you will likely also need to remove a few [submodule] lines from your .git/config pertaining to deploy_archive.
Sorry about the mess.  When I remove the deploy/ submodule, I'll try and get it all in one go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/835)

remove remnants of deploy_archive submodule

---

test/app/bellows/reset-forgotten-password.e2e-spec.ts
test/app/bellows/signup.e2e-spec.ts

The failure on the reset password part of the E2E traversal test is because the traversal test is designed to be run first, before anything else, but the test locator logic is running tests in subdirectories before it runs tests in the parent directory, so that the test/app/bellows/bellows-traversal.e2e-spec.ts test is running *after* the test/app/bellows/reset-forgotten-password.e2e-spec.ts test. The bellows-traversal test needs to run first. Moving the reset-forgotten-password test into the parent directory fixes this issue.
This doesn't fix all the E2E tests, but we at least have fewer failures after this PR than before the PR. :-)
--- …

Fix reset password part of E2E traversal test

---

test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php

I've decided to cut these two failing PHP tests as they don't actually check code, but just fail if LFMerge is not present on the system.  If that's not the case for a production environment, then we've got bigger problems than a failing test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/841)

delete 2 failing LFMerge PHP tests

---

test/app/bellows/bellows-traversal.e2e-spec.ts
test/app/bellows/reset-forgotten-password.e2e-spec.ts
test/app/bellows/shared/activity.page.ts
test/app/bellows/shared/change-password.page.ts
test/app/bellows/shared/forgot-password.page.ts
test/app/bellows/shared/login.page.ts
test/app/bellows/shared/projects.page.ts
test/app/bellows/shared/reset-password.page.ts
test/app/bellows/shared/signup.page.ts
test/app/bellows/shared/site-admin.page.ts
test/app/bellows/shared/user-profile.page.ts
test/app/bellows/shared/utils.ts

bellows-traversal.e2e-spec.ts and reset-forgotten-password.e2e-spec.ts and all their helper code (the various page proxy classes they use) are now completely async, which should (once we can comfirm E2E tests are working) help reduce the number of browser.wait() calls we have to make.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/836)

Convert some E2E tests to be async

---

test/app/bellows/change-password.e2e-spec.ts

The async nature of calls like changePasswordPage.get() meant that the tests that expect to be on the change-password page were running before changePasswordPage.get() had actually returned. Using explicit awaits in the E2E test fixes that.
Before this PR, I was getting random failures on the "Bellows E2E Change Password app", usually with errors like `[ng:btstrpd] App already bootstrapped with this element '&lt;body class="ng-scope"&gt;'`. or `Failed: Wait timed out after 3010ms`. With the changes in this PR, the test suite passes 100% of the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/842)

Fix change-password.e2e-spec.ts tests

---

docker/e2e-ui/run.sh

The run.sh file in docker/e2e-ui was originally designed to pass in the name of the site (sf for Scripture Forge, lf for Language Forge, etc) as its first parameter, so it was designed to swallow its first parameter and pass any later parameters on to the Gulp task, for things like `--specs=change-password`. Now that we're no longer calling it with the site name, we no longer need to strip the first parameter.
Also added quotation marks around the `$@` usage so that spaces won't be dropped: see https://www.grymoire.com/Unix/Sh.html#uh-42 for why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/843)

Fix extra params in e2e-ui/run.sh

---

test/app/bellows/project-settings.e2e-spec.ts
test/app/bellows/projects.e2e-spec.ts
test/app/bellows/shared/project-settings.page.ts
test/app/bellows/shared/projects.page.ts
test/app/bellows/shared/user-management.page.ts
test/app/bellows/signup.e2e-spec.ts
test/app/bellows/user-management.e2e-spec.ts
test/app/bellows/user-profile.e2e-spec.ts
test/app/languageforge/lexicon-traversal.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-input-systems.e2e-spec.ts
test/app/languageforge/lexicon/settings/interface-language.e2e-spec.ts
test/app/languageforge/lexicon/settings/lexicon-project-settings.e2e-spec.ts
test/app/languageforge/lexicon/settings/semantic-domains.e2e-spec.ts
test/app/languageforge/lexicon/shared/configuration.page.ts
test/app/languageforge/lexicon/shared/editor.page.ts
test/app/languageforge/lexicon/shared/new-lex-project.page.ts
test/app/languageforge/lexicon/shared/project-settings.page.ts

This fixes many (hopefully, all) E2E test failures caused by race conditions, e.g. a FooPage.get() call at the end of one test that isn't being awaited, so the next test starts before the get() call has actually completed and then the next test fails because the browser isn't yet on that page.
There are still quite a few E2E test failures remaining, but I believe those are all, or mostly, real failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/847)

Fix most async problems in E2E tests

---

docker/Makefile
docker/docker-compose.yml

Use snake_case for names, as that's what Docker seems to prefer.  Add lf_ to the beginning of all volume names so that we can programmatically remove all lf_ volumes locally and on the build server without bothering other volumes needed for other projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/851)

standardize naming of volumes for easy cleanup on CI (TeamCity)

---

package.json

Latest version of node-sass, which should help future-proof this dependency at least a little bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/832)

Update node-sass to 4.14.1

---

src/Api/Model/Shared/Command/LdapiCommands.php
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Service/Sf.php
src/angular-app/bellows/core/api/roles.service.ts
test/app/bellows/shared/utils.ts
test/app/languageforge/lexicon-traversal.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/settings/semantic-domains.e2e-spec.ts
test/app/languageforge/lexicon/shared/editor.page.ts

Three fixes included:
- Fix LD API call that was causing "Oh. Error." messages during most tests, and several test failures
- Fix unsightly RPC errors in Chrome if it hangs around after you cancel E2E test execution (caused by the offline check trying to look up rights in the current project when the current project was a test project that had been deleted at the end of the test)
- Fix a few utility helper functions that weren't actually async even though they looked async (e.g., findEntryByLexeme, which I renamed to clickEntryByLexeme because then it can be called as `await editorPage.browse.clickEntryByLexeme('foo')` instead of `await (await editorPage.browse.findEntryByLexeme('foo')).click()`).
This PR supersedes #846 as it includes all of #846's fixes. I decided it was less confusing …

Fix more async problems in E2E tests

---

src/angular-app/bellows/core/exception-handling.service.ts

Our exception handling service is getting many errors with no `.message` property while running unit tests, which results in the useless error message "undefined (reported to Bugsnag)" in E2E test logs. This should fix that and at least print *something* meaningful even if the exception received has no `.message` property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/856)

Fix "undefined (reported to Bugsnag)" errors

---

src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html

The "Select All" tests were failing because the wrong Angular directive was being used for the "Select All" checkboxes in the field config. The ng-click directive fires before ng-model, so at the time the ng-click directive was firing on a "Select All" checkbox, the model was holding the *old* value for the checkbox, not the *new* value. Result: when you turned a "Select All" box *on*, it would turn all the checkboxes in its row and column *off*.
Replacing ng-click with ng-change on all the Select All checkboxes solved the issue. Since ng-change runs *after* ng-model, by the time the handler runs and updates the state of the checkboxes in the row and column, the model contains the *new* value and the "Select All" feature works like you'd expect it to work.
With this PR, all the …

Fix project config E2E tests

---

src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts

The cause of the failure was an LD API call that I added to the updateUser method of UserProfileAppController. When the user updates their profile in Language Forge, I had an LD API call to update that user's account in Language Depot. And for some reason, by the time that LD API call is being made, LF no longer counts the user as being logged in. So the `checkPermissions` method in Sf.php says "Oh, you're not logged in? Well, this isn't an anonymous method, so go log in first." Except the actual error message printed in that code path is "Your session has timed out.  Please login again." And that's not the message the E2E test is expecting to see, so it fails.
Thing is, we're not yet at the stage of merging user accounts in Language Depot with Language Forge, so that LD API call is …

Fix two new E2E failures in user-profile tests

---

test/app/bellows/shared/utils.ts
test/app/languageforge/lexicon/shared/editor.util.ts

The `sendKeys` helper function in editor.util.ts wasn't properly async, so any tests relying on that were running their checks before the keystrokes had actually been sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/860)

Another E2E async fix

---

docker/api/Dockerfile
docker/docker-compose.yml
docker/e2e-api/run.sh
test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.ts

This fixes all remaining E2E tests except the Send/Receive tests, which are expected failures until we have lfmerge in the container. Since there are only two lfmerge Send/Receive tests in our E2E test suite, I've disabled those two tests until we add lfmerge. That way we'll get a green build, and then we can just ensure that when we add lfmerge we continue to get a green build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/864)

Fix permissions issue in E2E tests

---

test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts

Race condition between dismissing modal and checking that the item was deleted; solved with `waitForAngular()` which will ensure that the item deletion completes before the next line of the E2E test proceeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/866)

Fix one flaky E2E test

---

.gitignore
.vscode/tasks.json
docker/Makefile
docker/docker-compose.yml
docker/ui-builder/Dockerfile
gulpfile.js
package-lock.json
package.json
webpack.config.js

This removes all references to sass and webpack from the gulpfile
In order to accomplish parallel sass and webpack watches, I am using the npm-run-all dev dependency.  The new way to run sass and webpack are:
```
npm run sass
npm run sass:watch
npm run webpack
npm run webpack:watch
npm run webpack:production
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/885)

Move webpack and sass to npm scripts (remove from gulp)

---

docker/Makefile
docker/docker-compose.yml
docker/test-e2e/Dockerfile
docker/test-e2e/run.sh
gulpfile.js
package.json
test/app/protractorConf.js

This removes the protractor command (and related tsc compile command) from the gulpfile.  
This adds two new npm scripts:
- `compile-test-e2e`
- `test-e2e`
`compile-test-e2e` runs during image build and `test-e2e` runs as the container command.
I also took the opportunity to remove comments in the protractorConf.js file.
TODO: make custom specs  work by passing in arguments to npm run test-e2e (still figuring that out)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/891)

move protractor e2e test command to package.json

---

README.md
docker/Makefile
docker/app/Dockerfile
docker/test-e2e/Dockerfile
docker/wait/Dockerfile

I built the wait image and pushed it to docker hub under my personal repository.  The wait image just includes docker-compose-wait, is simple and hasn't changed since @longrunningprocess created it, so I decided we could just build once and then reference it in our code as a simplification step.
This should hopefully simplify our building of the wait image, as well as resolve the conversation about where to build wait, as discussed in #891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/893)

use megahirt/wait instead of locally built wait

---

.github/workflows/build-and-deploy-images.yml
.github/workflows/publish-base-app.yml.disabled
docker-static/base-app/Dockerfile
docker/app/Dockerfile

This shifts about half of the lines in the app/Dockerfile into a separate Dockerfile which we publish under the name `sillsdev/web-languageforge:base-app-latest`  A previous run of this branch used a Github Action to publish the image which contains PHP7.3:apache, plus PHP extensions and LFMerge.  These things will rarely change and are a good starting place for further customizations.
This PR creates a docker-static folder which contains the base-app Dockerfile.  Publishing changes to this image is manual.  One can use the disabled github action which is checked into this PR as well for those manual updates if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-langua …

Use published base-app to optimize docker build time

---

docker/Makefile
docker/ld-api/Dockerfile
src/Api/Model/Shared/Command/LdapiCommands.php

Commit 607e5d51 in the LD API has changed the search endpoints from`/api/v2/searchUsers` to `/api/v2/search/users` (and similar for projects). This commit updates the API endpoints that Language Forge calls to match these new locations.
Since the ld-api container isn't part of the default "make build" list, you'll need to run `docker-compose build ld-api` after this PR is merged into master, or you'll see some error messages in the Language Forge UI as LF tries to access the new endpoints while your local ld-api container hasn't yet been rebuilt and is thus still serving up the old endpoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/901)

Update search endpoints in LD API

---

docker/ld-api/Dockerfile

Now that pnpm 6.0.1 is out, we can safely build the ld-api container with pnpm version 6, which includes a handy "pnpm fetch" command that's optimized for Dockerfile builds. I'll add that to the build soon.
This PR replaces #907.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/908)

Build ld-api container with pnpm 6

---

docker-static/base-app/Dockerfile

With this change, lfmerge logs will be sent to `/var/log/messages` and we'll be better able to debug lfmerge issues. (Without this change, lfmerge logs to syslog are being quietly swallowed in the Docker container and we can't see what it's doing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/924)

Fix lfmerge logging

---

docker-static/base-app/Dockerfile
docker-static/base-app/lfmerge.conf

This will allow LfMerge to find the Mongo database container. Future improvements might include looking for environment variables in LfMerge, but this is enough to get LfMerge working in the Docker environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/925)

Fix LfMerge config in base Docker image

---

.github/workflows/build-and-deploy-images.yml

We switch to using a branch as a trigger for GA after realizing that git tags are meant to be permanent and never be moved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/927)

build-and-deploy-images GA now tracks 'staging' branch

---

docker-static/base-app/Dockerfile
docker-static/base-app/entrypoint.sh

The Send/Receive feature uses Mercurial, which is a Python app. So our base image needs a working Python 2 installation.
This PR also adds an entrypoint script which will run `/etc/init.d/rsyslog start` so that lfmerge logs will go to /var/log/syslog rather than being silently swallowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/928)

Mercurial needs python

---

docker-static/base-app/Dockerfile

#928 made two changes, adding the Python deb package and tweaking the entrypoint so that `/etc/init.d/rsyslog start` would be called on startup. The latter change didn't work properly, so this PR reverts that change while leaving the Python change in place. This will allow Send/Receive to work, although it won't log to `/var/log/syslog` until someone logs into the QA container and runs `/etc/init.d/rsyslog start` by hand. I'll submit a new PR with entrypoint changes once I've gotten them working, but this PR will at least get Send/Receive working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/929)

Remove entrypoint changes that aren't working

---

docker-static/base-app/Dockerfile

This fixes https://github.com/sillsdev/web-languageforge/pull/928 by restoring the CMD line to the Dockerfile, which was the cause of Apache not starting after #928 was merged. I had assumed that giving an ENTRYPOINT line without a CMD line would keep the CMD line of the parent Dockerfile, but it turns out that's not the case. Setting ENTRYPOINT resets CMD, so if you want to keep the same CMD you have to re-issue the CMD line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/930)

Run rsyslog on startup of base app

---

docker/docker-compose.yml

Sometimes the E2E tests were starting before the app-for-e2e container was fully available. This PR fixes that race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/931)

Fix race condition in E2E test startup

---

docker/docker-compose.yml

The only thing I could think devs might've been doing is touching the index or config files expecting to see the changes but those weren't volume mapped... 🤷‍♂️

Added some volume mappings to help developers

---

refreshDeps.sh

The LfMerge build on Jenkins expects the refreshDeps.sh script to exist in this repo. (The LfMerge build clones the web-languageforge repo to get access to some of its PHP files during unit testing). The simplest way to fix the Jenkins LfMerge build is to just make sure that there's a refreshDeps.sh script in the LF Git repo, for now. Eventually I'll update the Jenkins LfMerge build, but that's a more complicated process.
Thankfully, now that we're no longer using Gulp, it's much easier to see what refreshDeps.sh is doing, and we also no longer need to specify the applicationName in the script either. So it's just "composer install" and "npm install" in the appropriate directories.
--- …

Restore refreshDeps.sh script (used by LfMerge build)

---

test/app/languageforge/lexicon/shared/new-lex-project.page.ts

Another attempt to fix the flaky E2E test. I looked into it and noticed that the "no error" check only looks for the presence of the string "alert" in the element's class attribute... but if the form is valid then there's supposed to be a green checkmark with the class `alert-success`. So this PR is attempting to fix the flaky test by only considering the text `alert-danger` to represent an error, and not failing the test if `alert-success` is present in the element's class attribute.
I'll create this PR in draft mode, then set it as ready to review & merge if the E2E tests pass on TeamCity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-languageforge/940)

Fix flaky E2E test

---

docker/docker-compose.yml
src/Api/Library/Shared/Communicate/Email.php

there may be times when the host name of the mailer is not "mail" so it's better to have this parameterized so there is more flexibility in deployments.

parameterized the mail host as an ENV var

---

.vscode/launch.json
README.md
docker/docker-compose.yml

This is a follow up PR to the initial enabling of XDebug PHP debugging.  With this change, you can now set a breakpoint in a PHP test and debug it in VSCode using XDebug.
In order to use XDebug for Unit Tests, 3 lines in the docker-compose file must be uncommented.  They are left commented because the XDebug settings do not play well with our CI environment.
Specifically the 
```
```
fails on TeamCity for reasons I don't understand right now.

enable xDebug for PHP unit-tests

---

.github/workflows/build-and-deploy-images.yml

Now that the QA infrastructure deployment is in place, this will ensure the images are ready when the CI/CD processes kick off.

time to change the GHA trigger from staging to master

---

scripts/tools/csvInsights.php
src/Api/Library/Shared/Website.php
test/app/setupTestEnvironment.php
test/php/library/shared/WebsiteTest.php
test/php/library/shared/communicate/CommunicateTest.php

This is a small "hack" necessary for Language Forge to function with production data under any site e.g. localhost, qa.languageforge.org or languageforge.org.  There is no longer a business case to keep a separate site distinction in this code-base.  A future change may remove the Website class entirely.

make languageforge.org the default for Website::get()

---

docker/deployment/db-deployment.yaml

The value "None" for the clusterIP property is invalid and so we remove the property entirely in hopes that it is not needed for deployment.
The following error occurred during deployment:
```
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Service "db" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set
```

remove "clusterIP: None" from db-deployment

---

test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.ts

I discovered that Selenium's `inputElement.clear()` function [does not actually trigger Angular change detection](https://stackoverflow.com/questions/50677760/selenium-clear-command-doesnt-clear-the-element)! Which explains why this particular test has been so flaky for so long. With this new approach, the test should be more consistent.

Fix flaky E2E test in Lexicon New Project suite

---

README.md
docker/Makefile
docker/test-e2e/run.sh

Passing a `TEST_SPECS` variable to Make, either via an environment variable (`export TEST_SPECS=foo`) or as `make TEST_SPECS=foo e2e-tests` on the command line, will now select only that spec file to run. E.g.:
```bash
make TEST_SPECS=test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.js e2e-tests
```
Note that the `TEST_SPECS` value should end in .js, not .ts, and should be relative to the root of the repo.

Select E2E tests with TEST_SPECS env var

---

.github/workflows/build-and-deploy-images.yml
README.md
docker/app/Dockerfile
docker/deployment/Makefile
docker/deployment/app-deployment.yaml
docker/mail/Dockerfile

The goal for `staging` will be the following:
Any push to `staging` or fast-forwarding the branch to a commit on `master` will trigger the build-n-publish workflow on GHA.  While that's happening, TC should be running unit and e2e tests.  Once those tests finish successfully, TC should deploy the infrastructure to QA.  It's important at this point to know that the build-n-publish workflow in GHA is in no way coupled/serialized to the unit/e2e tests that are running, these two platforms should be running at the same time and, if they do, the newly built images will be available by the time the QA deployment goes looking for the latest images.

Long-term deployment strategy

---

.vscode/extensions.json
.vscode/tasks.json
README.md
docker/test-e2e/.vscode/launch.json

This setup uses VS Code's Remote Containers feature to run VS Code inside the test-e2e container, where it can directly attach to Node processes and let you set breakpoints on the E2E tests.

Allow debugging E2E tests

---

docker/deployment/app-deployment.yaml

due to diff's in k8s/docker volumes, S/R was not working in staging ultimately because LFMerge's directory setup (https://github.com/sillsdev/LfMerge/blob/master/debian/postinst#L24) was being blown away during a volume mount in staging, see discussion in #981

Fixed S/R bug in staging (#981)

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
README.md
docker/test-e2e/.vscode/launch.json
docker/test-e2e/.vscode/tasks.json

Now you can use the launch config "Reset and debug E2E tests" to re-run the `setupTestEnvironment.php` script before launching your E2E debug session, all from within the E2E test container.

Add ability to reset E2E tests before debugging

---

webpack-dev.config.js
webpack-prd.config.js
webpack.config.js

The dev and prd configs shared almost all of their values, so we can extract those parts of the config to the common config file.
Verified locally by re-running build and running E2E tests; Webpack config still works as it should.

Extract common Webpack config from dev and prd

---

docker/Makefile
src/Api/Library/Shared/Communicate/Communicate.php
src/Api/Library/Shared/UrlHelper.php
src/Api/Library/Shared/Website.php
src/Site/OAuth/OAuthBase.php

To fix the OAuth login issue introduced by #955, we need to actually use the `WEBSITE` environment variable that is being passed in. This allows qa.languageforge.org to create redirection URLs after OAuth login that return to the correct site instead of having the QA site redirect to the live site.

Use WEBSITE env var to get base URL

---

src/Api/Model/Languageforge/Lexicon/Config/LexRoleViewConfig.php
src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html
src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.ts
src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts
src/angular-app/languageforge/lexicon/shared/model/lexicon-config.model.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/shared/configuration.page.ts

In project config, field input systems are supposed to override user input systems, not the other way around. Previously the logic was incorrectly having user input systems override field input systems.
This fix changes the logic for input systems so that the list of input systems for the field and the list of input systems for the user are ANDed together to get the override list. I.e., if the user has input systems A, B and D selected but C turned off, and the field is supposed to show input systems B, C and D, then the user will see just input systems B and D for that field.
We also get rid of the Reset buttons on the input systems settings. It was insufficiently obvious to users what they did, and with the new logic for calculating field overrides they're not needed any longer.
Demo: …

Better handling of field input systems overrides

---

.devcontainer/devcontainer.json

This ensures that the E2E test container will be ready for debugging as soon as it starts up. (Previously, VS Code could attach to the container before it was actually ready, and it wasn't always clear why you had to wait a minute before pressing the "Launch Debug Session" button).

Better setup for E2E test container

---

package-lock.json
package.json

Version 1.0.0 of `angular-ui-router` introduces unwanted behavior: when calling `$state.go()`, the page components get refreshed, which causes the input field to lose cursor focus. Since we're calling `$state.go()` every time the user stops typing for a moment, that causes very bad UX on the list-filter field.
Fixes #1002.

Roll back angular-ui-router version to 0.4.3

---

src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php

Fixes #1005.
I decided to not allow .svg images yet, since to be totally safe we need to write code that would strip out any embedded Javascript. Embedded Javascript in an .svg image can be useful for totally legitimate reasons such as tecnical images that can hide or reveal sections on click, but they can also be a vector (heh) for remote code execution. So before we allow SVGs, I want to add code that will examine the uploaded .svg file and strip out any embedded Javascript, because I cannot think of any reason why .svg images in Language Forge (and FieldWorks) would need embedded Javascript.

Allow uploading images in .gif format

---

docker/app-base/entrypoint.sh

This will allow us to fix any send/receive sessions that were partway through being run when the previous container was killed (e.g. if the pod was moved to a different Kubernetes node during a S/R process). We use `which lfmergeqm && ...` to ensure that this doesn't cause the container to fail if the entrypoint script ends up run on a container without lfmerge (which might happen once we separate lfmerge into its own container in the future).

Run lfmerge queue manager on container startup

---

docker/app-base/Dockerfile
docker/app-base/entrypoint.sh
docker/app-base/lfmergeqm-background.sh

This will allow lfmergeqm's Janitor class to find and clean up any failed syncs that aren't in the queue (state is SYNCING but there's no active lfmerge process handling that project). The main reason this can happen is if the app container was restarted in the middle of a Send/Receive, killing a previous lfmerge process.
This will have a minor merge conflict with #1030, which moves and rearranges some of the files touched here.

Run lfmergeqm every 24 hours

---

docker/Makefile
docker/app/Dockerfile
docker/docker-compose.yml
docker/ui-builder/Dockerfile
docker/ui-builder/Dockerfile.prod

This will allow us to simplify the Makefile and the build process; now building the `app` container will just require building one single Dockerfile.
Resolves #1028.

Move ui-builder into app Dockerfile

---

docker/docker-compose.yml

The Selenium docker image tagged 3.141.59-20210729 contains a browser version that our current Protractor version doesn't know how to handle.
Temporarily pin our Selenium docker image to 3.141.59-20210713 so that our E2E tests will run; later when we upgrade Protractor we can unpin this and run the latest Selenium image again.

Fix E2E tests not starting after clean-powerwash

---

docker/Makefile
docker/ui-builder/Dockerfile

The ui-builder changes from #1038 accidentally got reverted in #1040, probably due to a rebase onto a master branch that hadn't yet had the merge of #1038 applied yet. This should fix the issue.

Fix `make dev`

---

docker/app/Dockerfile
docker/app/entrypoint.sh

It's not `if [ which some-cmd ]`, it's `if which some-cmd`. It can also be a good idea to redirect the output of `which` to `/dev/null` so that you don't end up printing the full path of the command in your server logs (which is almost never necessary).

Fix mistake in entrypoint.sh script

---

docker/Makefile
docker/app/Dockerfile
docker/docker-compose.yml
docker/test-e2e/Dockerfile

Two changes here:
- Move ui-builder Docker into test-e2e. This lets us get rid of the `ui-builder` entirely from the Makefile.
- More efficient Dockerfile for the `lf-app` image. Specifically, there's no need to reinstall Composer dependencies every time we make any change to the source code anywhere. This change saves a couple minutes per build, and a LOT of time when iterating over code, building and running E2E tests repeatedly.
These could be split into separate PRs, but it's a little easier to keep them together in a single PR. I'll split them if requested during code review.

Dockerfile improvements

---

docker/docker-compose.yml
src/Api/Model/Shared/UserModel.php
test/app/setupTestEnvironment.php

The exception was caused by the Language Depot API returning HTTP 403 Forbidden instead of HTTP 200 OK, because the JWT token keys weren't actually set up correctly in development mode. Also, our Ldapi.php code doesn't handle HTTP 403 Forbidden correctly, which is something else I'll need to work on. (Somehow it ends up throwing an unhandled exception in Javascript land, in a way I haven't quite traced yet). But this PR will at least stop that error being thrown during E2E testing in development.

Fix "data.slice is not a function" exception

---

.github/workflows/build-and-deploy-images.yml

Multiple "run:" lines in a single step are not allowed, but you can use YAML's `|-` syntax to have the same effect. No `&&` needed at the end of each line, as the entire block is treated like a bash script.
Note that I had to make one semantic change: I eliminated the `GIT_TAG` variable and replaced it with just using `BUILD_VERSION` instead. That's because the only purpose of the `GIT_TAG` variable was to be used in setting `BUILD_VERSION`, but that wasn't working. The `$GITHUB_ENV` file is only read *between* steps. You can't write `echo FOO=bar >> $GITHUB_ENV` and then in the *same* build step, write `echo OTHER_VAR=staging-$FOO`. It won't work. If you need to define a variable and then use it, the part where you use it must be in a separate step. Here, `GIT_TAG` wasn't used elsewhere …

Fix build and push action

---

src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/share-with-others.component.ts

The intent of the Tech Support user role is that it has the same rights as a project manager, i.e. it can manage all aspects of the project. The "Share With Others" component was not giving Tech Support users the same rights as the manager: Tech Support was unable to list project members, manage their roles, and invite new users. This fixes that omission.
Fixes #1078.

Tech Support user can manage project members

---

docker/deployment/app-deployment.yaml

I could not easily figure out how to isolate this configuration to just the `/upload` (or `upload/lf-lexicon/import-zip`) path so this will apply to any requests coming into LF.
I did try the following to no avail:
```yaml
```

added k8s config allowing large file uploads

---

docker/deployment/scripts/kubeRsyncAssets.sh
docker/deployment/scripts/kubeRsyncMongo.sh
docker/deployment/scripts/kubeSetup.sh

This PR adds a script to do a mongo dump and restore via `kubectl`.
This script is intended to be run from my (Chris's) machine, but can be adapted for other machines.  It documents as a script each step of dumping production mongo data and restoring it on the running db container.
Also the kubeSetup.sh has been modified to setup both app and db containers simultaneously.

Add mongo dump and restore script for deployment

---

docker/deployment/scripts/kubeRsyncAssets.sh
docker/deployment/scripts/kubeRsyncSendReceive.sh
docker/deployment/scripts/kubeSetup.sh
docker/deployment/scripts/kubeSyncMongo.sh

These are just a few adjustments to my migration scripts after giving them more exercise.
- removed unnecessary installing SSH on mongo container in kubeSetup.sh
- added step in the 2 rsync scripts to add the the host key to the known hosts ahead of the rsync, so that rsync succeeds on new hosts

Deployment migration script tweaks

---

docker/deployment/Makefile
docker/deployment/secrets.yaml

In case the app is ever moved to a different cluster, having this script will make initialization much quicker for secrets.

added deployable secrets

---

docker/app/entrypoint.sh
docker/deployment/app-deployment.yaml
docker/docker-compose.yml

This will ensure that lfmerge logs get sent to stdout whether or not https://github.com/sillsdev/LfMerge/pull/134 is merged. Currently lfmerge runs in the lf-app container so its log messages end up mixed together with the PHP logs in `kubectl logs` output, but it's pretty easy to sort them out. If that mixing is not desired, then the entrypoint.sh changes can be reverted and `kubectl exec` can be used to run `tail -f /var/log/syslog` on the container instead.

Send lfmerge logs to stdout in lf-app container

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/send-receive-with-flex.md

I used the GitHub Issue template wizard to generate and customize these issue templates.  Most all of the lingo in these templates are stock GitHub, and they seem pretty good to me.

Add default issue templates for bug, feature and s/r issues

---

README.md
docker/docker-compose.yml

I have a new M1 machine and was running into docker build failures for `app`.  This was the result of lfmerge not having an arm64 pkg.  Creating one would be too much effort so this PR is the effort to emulate an x86 during the image build where lfmerge is used.
configuration
N/A

Emulate x86 so local dev is possible on arm64 machines

---

.gitignore
docker/Makefile

We needed to run `docker scan` against our images to understand current vulnerabilities.  These commits will both added some convenience scripts for future use as well as begin to triage the results and plans for mitigation.
Fixes #1117 
Check all that apply:
N/A

Added ability to run security scans of our images

---

test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts

Two tests rely on wording from moment.js which has changed slightly in date-fns. Specifically, a comment whose date shows up as being "in the future" (which can happen if the E2E tests are running on a fast machine) used to show up as having a date "in a few seconds", but now it shows up with the text "in less than a minute" instead. (Or that might not have anything to do with the date-fns change, and just be because my computer ran the E2E tests exceptionally fast twice in a row).
This commit allows the new date-fns wording to be matched.
I didn't create a tracking issue for this PR as it's a trivial fix.

Fix wording on E2E tests involving relative time

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss
src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.html
src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss
src/angular-app/languageforge/lexicon/editor/field/dc-rendered.component.html
src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts

Added css styles and FitTextDirective directive class to enable textarea auto sizing on the editor page. 
Fixes #1151, #1144, #1111
Check all that apply:
Please describe the manual tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Fix white space on mobile

---

docker/docker-compose.yml
package.json

`make dev` was always meant to allow developers to make changes locally and see those changes reflected in his/her running app.  However, CSS development was overlooked in the initial creation of the infrastructure, i.e., local CSS changes would not show up in the locally running app unless the dev cleaned volumes and rebuilt the ui image from scratch.
Fixes an untracked issue
- This change requires a documentation update
N/A

Fixed `make dev` for local CSS development

---

README.md
docker/docker-compose.yml
docker/ssl/Caddyfile

There are times when a dev needs to access his/her locally running app from another device on the same network.  Before these changes, this was not really feasibly with our reverse-proxy configuration.
Fixes an untracked issue
- This change requires a documentation update
N/A

Allow dev to test locally running app from any device on same network

---

src/angular-app/languageforge/lexicon/editor/field/dc-multitext.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts

When mobile users were trying to add data in the app, the device keyboard, e.g., Android keyboard, would pop up and already be in a "title-case" mode where the first letter would be capitalized but this is a bit cumbersome for users because he/she would have to go back to the word and lowercase the first letter.  So this request is made to help us give the user's browser some hints that the user's keyboard should not "autocapitalize" for given fields or perhaps the keyboard should "all caps" for other fields.  It's worth noting that this is not something the application can necessarily force upon the user's keyboard but hopefully these "hints" will be respected in many, if not all, cases.
Fixes #1113 
- UI change
Provided below …

disable initial capital for some fields

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

Added keyboard hooks, Page Up and Page Down to allow paging through the editor component.
Feature request.
- UI change
Please describe the manual tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Add page-up page-down to editor component

---

src/angular-app/bellows/core/api/json-rpc.service.ts

good description from #1162 already:
> Is your feature request related to a problem? Please describe.
> Currently our infrastructure is throwing a lot of HTTP 502 errors, which get reported to users in a yellow "Oh. RPC Error" box. But there's no action the user can take in response to a 502, and most of the time it doesn't mean there's anything wrong with their project.
> 
> Describe the solution you'd like
> We should filter out HTTP 502 errors from the pop-up notifications, and only log them in the Javascript console (which most users will never look at).
> 
> Describe alternatives you've considered
> We could also not log 502s in the JS console at all, but I think there's benefit to logging them in the console without showing a notification pop-up.
Fixes #1162 
- Bug fix (non-breaking …

Don't show 502's to end users

---

src/angular-app/languageforge/lexicon/editor/field/_dc-text.scss

This changes the textarea border from black to grey to be consistent with all other inputs
See #1172 
Unwanted black borders before this change
Grey borders after this change

remove black border on dc-text textarea

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/editor.component.html
src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts

The lexiconItemListContainer and compactEntryListContainer both contained non-optimal magic height numbers.
The new numbers provide a more consistent maximum height as well as no app surface scrollbar.
The only case where a scrollbar appears is when the search options dialog is exercised, and this is too complicated to fix without a more major CSS/HTML reshuffle.
Also remove line in FitTextDirective that fiddles with the compactListItemContainer height.  It should not.
Fixes #1179 
The current non-optimal / broken behavior on staging can be seen here:
https://user-images.githubusercontent.com/3444521/135425203-fabf0b31-7b89-4946-9871-22f7f27c7544.mp4
This PR creates a more consistent container height using magic numbers and works on all …

fix CSS magic height numbers for list containers

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

- changed the event handler registration to just $onInit instead of $viewContentLoaded.  This fixes #1178 the skipping entries problem.
- moved the unregister handler to $onDestroy, complementary to $onInit.  This is called whenever the editor component is destroyed - good enough.
- register event handler for `keydown`.  `keyup` works fine for adding events, but it appears to late for the browser default behavior of PgUp/PgDown which appears to trigger on PgDn.
- add e.preventDefault() to prevent scrolling inside the entry list and editor pane when using these keys to page entries.
Fixes #1177 #1178 
Supersedes PR #1174 (can be closed)
Hard to provide screenshots for a keyboard shortcut, so I decline.

fix PgUp and PgDn behavior in editor

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss
src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss
src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts

This removes some unnecessary complexity in the fit-text directive while completing required features of the text area resize issue #1190
This PR also optimizes a few different container height and margin values to provide a more consistent app height across viewports.  This complements the fit-text directive changes, which previously were making changes to parent containers via JS/CSS.
The change to dc-rendered now puts a maximum of two lines on the div across all viewports.
Fixes #1190 and #1172
You can watch the old behavior in #1190 here:
https://user-images.githubusercontent.com/3444521/135624012-8c70a2bc-44da-4b0d-8630-9f6136079915.mp4
See below for the new behavior:
https://user-images.githubusercontent.com/3444521/135638562-e9247 …

Simplify fit-text directive

---

src/Site/views/languageforge/container/languageforge.html.twig
src/Site/views/shared/_global.scss
src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss
src/releasenotes/languageforge.md

- This removes the footer across all views in the app.  We leave the footer in place for the brochure home page.
- Move the version string to be an image title on the logo.
- I adjusted the container height magic numbers to fill the space now available at the bottom of the view.
Fixes #1163 
- UI change
Desktop:
Mobile:

remove site footer across application

---

src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/share-with-others.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/share-with-others.modal.html
src/angular-app/languageforge/lexicon/shared/share-with-others/user-management.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/user-management.component.ts

This PR will update the UI for those users wanting to invite outsiders into a project.
Fixes #1132 
- UI change
https://user-images.githubusercontent.com/4412848/136611110-4c2de652-667b-4365-84aa-49276d7741f1.mov

Simplify "Share with others" UX

---

src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.html
src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss

Per discussion below, make the "rendered entry" on mobile scrollable with the entry editor.  The rendered-entry on desktop remains sticky at the top of the surface.
Fixes #1112 
- UI change
https://user-images.githubusercontent.com/3444521/137492485-5ec18636-be8c-4fcc-9418-2772f4e874ae.mp4
See how the desktop version keeps the rendered entry sticky with the toolbar on top.
See how the mobile version scrolls the rendered entry with the editor fields

Make rendered entry scrollable on mobile

---

src/Site/views/languageforge/theme/default/page/home/index.html.twig

This updates the YouTube video on the home page with a modified version of the 2016 LF video that does not have the beta label.
I also updated the YouTube embed code to the latest that YouTube recommends via their "share" dialog.
The new video is public on YouTube at https://www.youtube.com/watch?v=jWWZadUNi5g
Fixes #1234  (love the magic issue number on this one!)
- static content change (youtube link)

update YouTube video on home page (remove beta label)

---

src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor-list.view.html
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/editor.module.ts
src/angular-app/languageforge/lexicon/lexicon-app.module.ts

This feature will change the default search to include "diacritic-agnostic" results.  It will also add a new advanced option allowing users to narrow results based on diacritics.
Fixes #1114 
- UI change
Provided with test cases below
Project used for testing (5491 entries):  [Alex's project.zip](https://github.com/sillsdev/web-languageforge/files/7412915/Alex.s.project.zip)

Ignore diacritics by default when searching

---

.github/workflows/build-and-publish-npm-cache.yml
docker/Makefile
docker/app/Dockerfile
docker/npm-cache/Dockerfile

This PR is intended to be merged after Billy's service-worker PR.  It probably won't pass tests until it is merged.
This PR optimizes the build time of `docker-compose build app` in the following ways:
1. It utilizes an npm cache image to reduce/eliminate having to download npm packages from the internet.  As we update our dependencies, this npm cache image will slowly provide less performance value.  For now, it provides about a 50% speed increase in `npm install` time.
2. It remove unnecessary COPY lines that aren't used by webpack
3. It targets the COPY src/Site/views to only copy sass files
`docker-compose build app`
package.json file change 2:47
sass file, html file, typescript file change 0:47
PHP file change 0:03
TWIG file change 0:47
package.json file change **1:53**
sass file, …

Optimize app Dockerfile with npm cache

---

test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php

This is a regression test for one project where a custom field was renamed and its roleViews did not get updated correctly.
Fixes #1236
This PR adds two regression tests to try to prevent #1228 from happening again. It's been tested by, well, running the unit tests (`make unit-tests`). :grin:

Add two tests for renaming custom fields

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

There are a number of scenarios where the user can be left disoriented by the fact that the entry that is selected is not visible in the full list of entries on the left.  Some of the use cases are outlined in the comments of https://github.com/sillsdev/web-languageforge/issues/1133
Fixes #1133 Fixes #1130 Fixes #1014 
Video's demoing the fixes are already captured in the issue comments.

Correct scroll sync issues

---

src/Site/views/shared/container/container.html.twig

This PR removes a reference to a file that used to be our main application JS bundle.  Our webpack config changed and now this file doesn't exist anymore.
This PR resolves the console error:
Please describe the manual tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Remove broken file file reference

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

While testing #1253 , an additional use case was found to be broken when a user has a poor connection.
Demo's included with tests below
https://user-images.githubusercontent.com/4412848/144872443-28284593-6f3c-4f7d-b7ab-1adf246d8126.mov

Fixed broken scroll during poor connections

---

.github/workflows/build-and-publish-adhoc.yml

This change will allow repo members to publish a Docker image with any tag via a manual GHA
- engineering simplification
N/A
It will be once this PR is merged into `develop`

Parameterized docker image tag for ad-hoc publishing

---

.github/workflows/build-and-deploy-images.yml
.github/workflows/deployment-staging.yml
README.md
docker/Makefile
docker/deployment/Makefile
docker/docker-compose.yml

This PR will will trigger automated build, test, publish and deployment actions  for any pushes to `develop`
- Engineering
N/A

Refactored actions to include deployment to the staging environment

---

.github/workflows/unit-tests.yml

This fixes a remnant from #1268 that was overlooked and resulting in unit tests running twice when changes were pushed to `develop`
- Engineering
N/A
This will be tested once the PR is merged into `develop` and the GHA does not get triggered.

Remove duplicate unit test runs on develop

---

src/angular-app/bellows/core/offline/editor-data.service.ts

Normalize the search string to NFC since all data in LF is normalized to NFC on disk.  This allows for exact match or ignore diacritic queries to work regardless of form or language, e.g. Korean.
A note about this fix:
- All data is normalized to NFC in the database on write.  It's been this way for years.
- @longrunningprocess 's addition in #1243 normalized the query to NFD for the purposes of removing diacritics from the data and query.  This a fine approach.
- This PR could have chosen to normalize all data to NFD for comparison under all circumstances given the second point above, however I chose to stick with NFC since that is what the data is underneath.  Either way works.
Fixes #1244
Consider the single Korean character below: …

normalize search string to NFC before comparison

---

.github/workflows/build-and-publish-base-php.yml
docker/app/Dockerfile
docker/base-php/Dockerfile

I had been noticing `gd` and `mongodb` were compiling from source code every build (~12 minutes) but these things don't need to necessarily be built like that every time so I set out to create a "base" PHP image for LF with this PR.
- Engineering change to speed up development cycles

Attempting to speed up app builds

---

.github/workflows/unit-tests.yml
docker/Makefile
docker/test-php/Dockerfile
docker/test-php/run.sh

Re-architect the test-php image to be built off the base-php image for faster building and execution of unit tests.  This should get unit tests running in under 2 minutes without all the UI building happening in the full app image (not necessary for PHP unit tests)
Also, use a docker layer cache action.
Informal testing:
- before this PR: unit tests complete in 4 minutes
- this PR, without layer caching: unit tests complete in 2 minutes
- this PR, layer caching first run (create cache): 2.5 minutes
- this PR, with existing cache: 1.5 minutes 🥇 
- 

Make unit tests build faster by basing the image off base-php instead of the full app image

---

.github/workflows/e2e-tests.yml
.github/workflows/unit-tests.yml
docker/Makefile
package-lock.json
package.json
test/app/protractorConf.js

This PR adds a separate workflow for e2e test runs.  The e2e tests could have been included in the existing unit-test workflow, however I chose to split it out into a separate workflow so that it can be reported as a separate line item in the PR checks.
This PR also makes the following minor changes:
- adds a unit test reporter to display test results in a PR comment
- adds the protractor-fail-fast capability for e2e tests (stop test runner after first failure).
This is advantageous for E2E tests since they take a long time to run, and often the first failing test is where the problem lies. 
This should save time when running flaky E2E tests.  We should be able to re-run the e2e tests quicker with fail-fast turned on.
Fixes #1276
Fixes #1269 
Only keep lines below that describe this …

e2e test GHA workflow + unit test reporter

---

.github/workflows/production.yml

The job name for production workflows is wrong, see #1287 for details.
Fixes #1287 
N/A
N/A

Fix job name for production workflows

---

docker/deployment/.gitignore
docker/deployment/Makefile

Add a Makefile target that copies all Send/Receive state files to the developer's machine, and then copy projects ONHOLD into a separate folder for further inspection.
This PR is intended to commit utility code that I used to conveniently get state files onto my machine for local inspection.  It is not intended as a long-term fix or implementation.  We should instead [write an email handler for whenever a project goes on HOLD](https://github.com/sillsdev/web-languageforge/issues/1189).

chore: lfmerge-copy-state Makefile target

---

.github/workflows/tests.yml
src/angular-app/bellows/core/offline/offline-cache-utils.service.ts
src/angular-app/bellows/core/offline/offline-cache.service.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/lexicon-app.module.ts
test/app/bellows/projects.e2e-spec.ts
test/app/bellows/shared/change-password.page.ts
test/app/bellows/shared/project-settings.page.ts
test/app/bellows/shared/utils.ts
test/app/languageforge/lexicon-traversal.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-comments.e2e-spec.ts
test/app/languageforge/lexicon/editor/editor-entry.e2e-spec.ts
test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/settings/semantic-domains.e2e-spec.ts
test/app/languageforge/lexicon/shared/editor.page.ts
test/app/languageforge/lexicon/shared/project-settings.page.ts
test/app/protractorConf.js
test/app/testConstants.json

When arriving at a project in the entry editor, go to most recently-viewed entry. If there is no recently viewed entry, set it to the first entry in the list. 
100% AngularJS / Indexed DB
handle multiple projects
Loading a project always goes to the editor (avoid going to the list by default)
Load the most recently used entry if exists in the cache
If no cache is available, load the first entry
clicking on the "<-- list" button or the "list" breadcrumb explicitly still takes the user to the list
Fixes #1161 

Go to most recently viewed entry

---

.github/ISSUE_TEMPLATE/send-receive-with-flex.md
src/angular-app/languageforge/lexicon/editor/editor.component.ts

This is a follow up PR to #1252 where during QA testing @longrunningprocess discovered a bug whereby deleting an entry caused the MRU cache and URL to not be updated, thereby creating a situation where the app could go to an invalid state.
Addresses testing and comments called out in #1252 
Also contains an unrelated tweak to a GH issue template 😁 

Fix most-recently-used-entry delete bug

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

Fixes #1248.
The cause of the issue was normalization: U+0061 LATIN SMALL LETTER A followed by U+0301 COMBINING ACUTE ACCENT was in the Mongo database (for example), but what got saved into Mongo was U+00E1 LATIN SMALL LETTER A WITH ACUTE. The diff algorithm naturally compared those two as different (since it's doing a basic byte comparison on strings), and therefore a delta update was being submitted which changed á to á. Mongo was therefore writing that field's value in the database, accidentally overwriting any previous edits to that field from a different user.
The answer is to normalize the `pristineEntry` value (the value that came out of the database) before passing it to the diffing algorithm, so that it's comparing NFC to NFC. With this change, I can no longer reproduce the test …

Fix bug where simultaneous edits could lose data

---

.github/workflows/add-issues-to-project.yml

Use dhruvkb/issue-projector@0.0.7 GA to add new issues to the project board.
This is a GA experiment - I don't know if it will work, and it can't be tested until it is merged.

Automatically add new issues to project board

---

src/Site/views/languageforge/container/languageforge.html.twig
src/Site/views/languageforge/theme/default/sass/_global.scss
src/angular-app/bellows/core/navbar.controller.ts
test/app/bellows/project-settings.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-input-systems.e2e-spec.ts

Hide Share button from My Projects and other non lexicon project pages. 
Fixes #1241 
- UI change

Hide Share button from My Projects Page

---

playwright.config.ts

This allows `npx playwright test` to be run even when the E2E server is not running yet.

Make Playwright start E2E server if needed

---

test/e2e/utils/globalSetup.ts

We now skip creating the file if it already exists and has a creation date less than 1 year old (since that's the default lifetime of the "Remember Me" cookies that Silex creates). This means that the slowness of logging in five times through the UI (which takes about 20 seconds on a relatively fast developer machine) will only happen once per machine.

Optimize creation of login storage state files

---

test/e2e/change-password.spec.ts
test/e2e/pages/page-header.page.ts
test/e2e/pages/projects.page.ts
test/e2e/utils/fixtures.ts
test/e2e/utils/login.ts

The following tests have been converted to playwright
Bellows E2E Change Password app
✓ setup: login as user, go to change password page
✓ refuses to allow form submission if the confirm input does not match
✓ allows form submission if the confirm input matches
[previously commented out] should not allow a password less than 7 characters
✓ can successfully changes user's password after form submission
For details/remarks regarding converting the above tests, refer to the spreadsheet; https://docs.google.com/spreadsheets/d/1w9wjfm-02QHLhv0ObPAKKlqnDWeag379GIXwOcRU4W0/edit#gid=0
E2E test

Change password playwright tests 

---

.github/workflows/integrate-and-deploy.yml
.github/workflows/pull-request.yml
.vscode/extensions.json

This PR tweaks the `pull-request` and `integrate-and-deploy` workflows.
Tweaks in this PR:
- update VS Code workspace recommendation to reflect a package name change
- remove `--with-deps` from `npx playwright install` because it's appears unnecessary and is slower
- move to use `npm ci` since we're on CI - it seems to be the recommended thing to do
- add playwright tests to integrate-and-deploy workflow
A future TODO could be to restructure the integrate and deploy such that it is generic enough to be used in the PR workflow.  These two workflows are increasingly performing the same function.
**Note**: The changes to integrate-and-deploy won't actually be tested until this PR is merged.  If there's a problem with my change I'll either follow up with another PR or make a change directly …

Tweak workflows with respect to playwright tests

---

test/e2e/change-password.spec.ts
test/e2e/example.spec.ts
test/e2e/tsconfig.json
test/e2e/utils/TestControl.php
test/e2e/utils/testControl.ts
test/e2e/utils/testSetup.ts
test/e2e/utils/userFixtures.ts

New API entries in testSetup.ts:
* initTestProject to create new, empty project
* addCustomField to add a custom field to a project
* addLexEntry to add a lexical entry to a project
* getProjectJson for help with logging or expect()ing project config
* changePassword API moved from testControl.ts to testSetup.ts
Also added some examples in example.spec.ts showing how to use the
testSetup API. Each example is in a `test.skip` block so that they will
not actually run by default.

New TestControl API, rename testControl.ts to testSetup

---

test/e2e/site-traversal.spec.ts
test/e2e/utils/fixtures.ts

Implementing a modified design pattern: For simple tests, the same page is reused instead of requesting a new page for every single test. Thereby, the tests run much faster.
The new design pattern is implemented by a fixture. It makes a page reusable and prevents Playwright from closing the page after a test. This fixtures is a page where no user is logged in and is called `anonTab`.
Fixes # (issue) no issue created 
E2E test

improve efficiency of site-traversal tests by implementing new design pattern

---

.github/workflows/integrate-and-deploy.yml

E2E tests assume they are being run from root of repo, not from `docker` directory, so they need `working_directory: .` in the GHA workflow file.
Fixes #1369.

Run E2E tests from correct working directory

---

src/Api/Model/Shared/DeepDiff/DeepDiffDecoder.php

Should also fix the bug with other fields like list fields, as the root cause of the bug was the same.
The Part of Speech field wasn't saving properly due to an error in the DeepDiffDecoder logic. It was working when I tested it, but then I made a change to fix saving MultiText fields and failed to notice that that change would have an effect on list fields like Part of Speech. (Because both MultiText fields and list fields end with a path component called "value" in the final position, and that's what I was checking for).
Fixes #1248.
- Load a project
- Have at least two lexical entries
- Change the part of speech of entry 1
- Go to entry 2
- Go back to entry 1
- …

Fix bug where Part of Speech wasn't saving

---

src/Api/Model/Shared/DeepDiff/DeepDiffDecoder.php

Fix saving list fields and custom fields.
Fixes #1248.
- Create a new non-send/receive project (for speed)
- Load the TestLangProj.7z data into it (from the `test/common` directory)
- Add data to all the custom fields (except CustMultiPara because multi-paragraph fields are disabled in LF right now) of the first entry
- Also change the part of speech
- Click to another entry
- Click back to the first entry
- Verify that the data you added is still there
- Do a browser refresh (F5)
- Verify that the data you entered …

Fix list field saving as well as all varieties of custom fields

---

src/Api/Model/Shared/DeepDiff/DeepDiffDecoder.php

Follow-up to #1372. Fixes the one remaining bug that #1372 had missed.
Fixes #1248.
* Create a new non-send/receive project (for speed)
* Load the TestLangProj.7z data into it (from the test/common directory)
* Add data to all the custom fields (except CustMultiPara because multi-paragraph fields are disabled in LF right now) of the first entry
* Also change the part of speech
* Click to another entry
* Click back to the first entry
* Verify that the data you added is still there
* Do a browser refresh (F5)
* Verify that the data you entered is still there
* If this step fails, then the data made it into localStorage but did not actually make it into Mongo
Reviewers: …

Fix last remaining bug in custom field saving

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts

We were treating every field as an object, but the senses and example fields are actually arrays of objects. This was resulting in custom fields not being sent to the server in the right format, so the server was simply not seeing any custom field changes in senses or examples: only custom fields at the entry level were being saved.
Fixes #1375.
See #1375's repro steps.

Fix saving custom fields on senses and examples

---

src/angular-app/languageforge/lexicon/editor/editor.component.html
src/angular-app/languageforge/lexicon/editor/field/_dc-rendered.scss

Added  "dc-rendered-on-desktop" class to parent button bar div to hide it on mobile.
Fixes #1290
- UI change Hide button bar on mobile

Hide prev/next entry control on mobile

---

src/angular-app/bellows/apps/public/signup/signup-app.component.html
test/e2e/pages/signup.page.ts
test/e2e/signup.spec.ts

The following tests have been converted to playwright
Bellows E2E Signup app
✓ can verify required information filled
✓ cannot submit if email is invalid
✓ cannot submit if password is weak
✓ can submit if password not weak
✓ can submit if password is showing and not weak
✓ cannot submit if captcha not selected
✓ can submit a user registration request and captcha is invalid
✓ finds the admin user (case insensitive) already exists
✓ can prefill email address that can't be changed
✓ can prefill email address that already exists
✓ can signup a new user
✓ redirects to projects page if already logged in
For details/remarks regarding converting the above tests, refer to the spreadsheet; https://docs.google.com/spreadsheets/d/1w9wjfm-02QHLhv0ObPAKKlqnDWeag379GIXwOcRU4W0/edit#gid=0
Fixes # (no …

convert signup tests from Protractor to Playwright

---

src/Site/views/languageforge/container/languageforge.html.twig

Initiated by user feedback, this PR updates some links under the "Help" menu, now renamed to "About".  Summary of changes:
- Remove the How To / Tutorials link.  This just pointed to the community site under a sub-category called How To / Tutorials.  It's not well maintained.
- Removed the tour link (we no longer pay for HelpHero - it never worked very well)
- Add a link to YouTube videos
- Add a link to Known issues and limitations on GH wiki
- Rename "What's new in the app" to "What's New" and link to the post that @alex-larkin maintains for release summaries
- Add a link to github releases (because it's cool)
- re ordered the links a bit
- added font awesome v4 icons
Fixes # (not sure if there is an issue yet)
- UI change

Update/Add links under Help/About menu

---

.gitignore
docker/Makefile
docker/test-php/Dockerfile
docker/test-php/run.sh

This is just a small PR that: 
- adds a build step to `make unit-tests` for easier rebuilding on code changes
- adds a comment about running single PHPUnit tests
- ignores /src/vendor folder, since having the composer installed vendor libraries available to the IDE is helpful for debugging in XDebug

optimize for building and debugging PHP tests

---

docker/Makefile
docker/docker-compose.yml
src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php

`.m4a` is an increasingly common and default audio extension and file format that LF should support.
Fixes #1383 which was reported by an user.
Before this change:
After this change:

allow m4a audio uploads

---

.editorconfig

This will force Tab characters in Makefiles, reducing the amount of time we have to spend fussing with whitespace when we edit them.

Add .editorconfig entry for Makefiles

---

docker/lfmerge/Dockerfile

Pull in an LfMerge bugfix that allows it to run again. The cause of the bug was that we switched to environment variables to feed LfMerge its settings (much easier to work with in Docker/Kubernetes than a config file), and the `sudo` command strips environment variables unless you whitelist them. So we whitelisted the `LFMERGE_*` variables, and now Send/Receive works again.
Fixes #1395.
Reviewers: add/replace your name below and check the box to sign-off/attest …

Bump LfMerge version to pull in bugfix

---

docker/lfmerge/Dockerfile

This fixes the issue where lfmerge would fail to start after `make clean-volumes`.

Bump lfmerge version to 2.0.110

---

docker/deployment/Makefile
docker/deployment/app-deployment.yaml
docker/deployment/lfmerge-deployment.yaml
docker/docker-compose.yml

As a follow-up to #1389, this PR moves the lfmerge container into a separate pod, using pod affinity to ensure that it will be assigned to the same node as the main app. (Since they share a persistent volume, this is necessary so that the volume can be mounted in ReadWriteOnce mode instead of ReadWriteMany — ReadWriteMany greatly limits the number of storage backends available, while ReadWriteOnce is a lot easier for storage backends to use. (I see https://longhorn.io/blog/longhorn-v1.1.0/ from January 2021 that announces ReadWriteMany availability in Longhorn, so perhaps the pod affinity can be gotten rid of at some point).
Fixes #1406.
Please provide …

Move lfmerge container to separate pod using pod affinity

---

docker/lfmerge/Dockerfile

Found and fixed an LfMerge build issue that was causing the LfMerge build for FieldWorks 8.2 to be incorrectly pulling in the DLLs from FieldWorks 8.3. This was causing older projects, such as my test-rmunn-04 project, to fail to clone correctly.
LfMerge version 2.0.115 has the bugfix; this is the version we should deploy next time we push a Language Forge release.
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce.  Please also provide relevant test data as necessary. …

Fix bug cloning FW8 projects

---

.github/workflows/integrate-and-deploy.yml

Now that the lfmerge container is in a separate pod, we also need to tweak the GHA workflow to update the proper Kubernetes deployment when the workflow runs. Instead of setting the `lfmerge` image in the `app` deployment, the `lfmerge` deployment is now the one that will contain the `lfmerge` image.
This really should have been included in #1407, but I forgot this one step.
Cloning just one project should be enough: if there are any problems with this deployment, …

Add lfmerge deployment to GHA workflow

---

docker/lfmerge/Dockerfile

The 2.0.118 build failed to build one of the four DbVersions due to a network error while downloading dependencies. I've adjusted the LfMerge build to exit immediately if any step returns a non-zero exit code, so that sort of undetected error shouldn't happen again. The 2.0.119 build has all the DbVersions built correctly, and should replace 2.0.118.
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce.  Please also provide relevant test data as necessary.  These …

Bump LfMerge to fix build error

---

src/Api/Model/Shared/UserModel.php

This fixes an issue where a user could not login because they are accustomed to case-sensitive email addresses.  This is a simpler implementation of #1419 , given that we know that all our email addresses are already lowercase.
Fixes #1418 

Convert to lowercase before email lookup

---

.vscode/extensions.json

In https://github.com/sillsdev/web-languageforge/pull/1422 we switched away from awesome-typescript-loader to ts-loader, but our VS Code extensions recommendation is still recommending a problem matcher extension that parses the awesome-typescript-loader syntax. We should stop recommending that extension now, and instead recommend a problem-matcher extension that parses the output of ts-loader.
(Problem matchers are how VS Code takes the output of a build process and turns it into the list found in the **View → Problems** menu. They're build-tool specific as they contain regexes to extract filenames, line numbers, etc. from that specific tool's output.)
No testing …

Remove VS Code extension recommendation

---

src/angular-app/languageforge/lexicon/new-project/non-send-receive/new-project-name.controller.html

An alert was covering the buttons used to create a new project in the scenario where it was a non-S/R project and the user was on a mobile device.
Fixes #1411 
Bug demo:
https://user-images.githubusercontent.com/4412848/176743057-ed16e066-52e2-4bc1-bded-2e79b126a060.mov
Corrected:
https://user-images.githubusercontent.com/4412848/176743248-93ee5c10-6e0b-4a6e-976c-27bedad1bc1e.mov

Allow mobile users to create non-S/R projects

---

docker/deployment/app-deployment.yaml
docker/deployment/lfmerge-deployment.yaml

We learned that lfmerge's inotify will only receive messages from the kernel when the kernel is the same kernel used to write the files into place, i.e., lf-app  in this case.  Therefore, app and lfmerge must run on the same node until another mechanism can be considered that will work in a remote nfs environment.
- Bug fix (non-breaking change which fixes an issue) (introduced in #1433 )
N/A

had to ensure app and lfmerge run on same node

---

docker/Makefile

Current Docker versions use 'docker compose' syntax. In accordance with this, instances of of 'docker-compose' in docker/Makefile have been changed to 'docker compose.'
Fixes #1451
syntax update
Running commands from the Makefile

Change 'docker-compose' to 'docker compose'

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/editor-entry.view.html
src/angular-app/languageforge/lexicon/editor/editor-list.view.html

Make the search bar look more like a search bar
Fixes # (issue)
- UI change

Add Search Bar icon

---

docker/Makefile
docs/DEVELOPER.md

Over time, I've come to realize that the `clean-volumes` target wasn't really understood well and therefore unused.  I decide to simply get rid of that use case altogether.
- DX improvement
N/A

Simplified make's clean targets

---

test/e2e/pages/entries-list.page.ts

The recent PR 1446 changed the placeholder text of the search box, which broke the playwright tests. However no one noticed because the tests were turned off for PRs in 493233cab4545fec07d5f1ef940ffd3692212fc0
Before this PR, the four failing tests are:
```
4 failed
[chromium] › editor-entry.spec.ts:49:5 › Lexicon E2E Entry Editor and Entries List › Entries List › Entries list has correct number of entries 
[chromium] › editor-entry.spec.ts:53:5 › Lexicon E2E Entry Editor and Entries List › Entries List › Search function works correctly 
[chromium] › editor-entry.spec.ts:540:9 › Lexicon E2E Entry Editor and Entries List › Entry Editor › Audio › Manager › Back to browse page, create new word, check word count, modify new word, autosaves changes, new word visible in editor and list …
```

fix 2 playwright tests that broke from UI change

---

package-lock.json
package.json
playwright.config.ts

This brings us the latest version, and also fixes the remaining failing playwright tests on develop that use .filter()
In addition, I limit the workers to 1 for local runs, as our tests are not yet designed to be run in parallel (more work needed)

upgrade Playwright to 1.25.2

---

.github/workflows/integrate-and-deploy.yml
.github/workflows/pull-request.yml
docker/Makefile

When installing browsers for Playwright, only install chromium, as that is the only browser that we are currently using.  This make our build more efficient by skipping downloading browsers that we never use.
- build optimization
Before this change, we download Firefox, Webkit and Chromium as seen in the GHA build below:
After this PR, we only download Chromium (FFMPEG is always downloaded)

only install chromium for playwright

---

next-app/src/routes/projects/[project_code]/meta/+server.ts
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Service/Sf.php

The number of entries on the project dashboard were being limited to 1,000.
Fixes #1460 

Fixed bug where num of entries was being limited to 1,000 on project dashboard

---

docker/deployment/app-deployment.yaml

With some larger projects, I was finding the legacy app would not respond to `lex-stat-all` calls without shutting down the connection.  I bumped the memory and it worked fine.  This PR will make those resource configs more permanent.
- k8s config change
N/A

Legacy app needed a little more memory based on testing in staging

---

src/angular-app/languageforge/lexicon/editor/_editor.scss

Change search-bar background color to white.
Fixes # (issue)
- UI change

Changed search bar background color style to white.

---

.github/workflows/pull-request.yml
docker/Makefile
package.json
playwright.config.ts
test/e2e/utils/globalSetup.ts
tslint.json

Various minor playwright improvements:
- Cache playwright browsers in GHA (per playwright version as documented). Not a huge performance boost, but not a huge change either
- Upload the playwright results as a GitHub artifact, which is then available for download (see screenshot)
- Allow passing playwright params to make file. E.g. `make playwright-tests params="--headed"`
- Allow running make files with npm (I find it very handy for the commands to be directory independent) E.g. `npm run make playwright-tests params="--headed"`
- Wait for forgotten promise in `globalSetup.ts` and add ts-lint rule to watch for cases like this
- Close browserContexts in `globalSetup.ts`, because: (1) it's documented as best practice, (2) it doesn't break anything and (3) it eliminates a potential culprit …

Local and GitHub playwright testing improvements

---

docker/lfmerge/Dockerfile

Upgrades LfMerge to .NET6
Fixes #1297 
- Refactor
Local changes:
- Open a test project
- Make a change
- Settings -> Synchronize -> Send/Receive
Local and remote changes:
- Open a test project in LF and the same project in FieldWorks
- Change an entry in FW and S/R to Language Depot or wherever
- Change an entry in LF
- Settings -> Synchronize -> Send/Receive
- Verify both changes appear in LF

Using lfmerge .NET6

---

docker/lfmerge/Dockerfile

This should allow lfmerge to work with older FW model versions.
See https://github.com/sillsdev/LfMerge/pull/310 for details of the changes in this update.
- LFMerge update

Using latest lfmerge

---

.vscode/extensions.json
docs/DEVELOPER.md

The Playwright VS code extension is very handy and will presumably make it into the playwright "cheat sheet", so I've added it to the recommendations.
As I needed to set up the project a second time on my new laptop I got a fresh wave of inspiration to adapt the development docs according to me experience.
- New IDE feature (non-breaking change which adds functionality)
- Docs update

Add playwright extension to recommendations and overhault docs

---

test/e2e/signup.spec.ts

By using playwright's built tools for waiting for the URL we want, we can wait for exactly what we want to verify rather than wait for the network to be idle.
Fixes #1481 

Fix flaky test by waiting for specific URL

---

docker/docker-compose.yml

Fixes the GHA runtime error
```
service.platform should be part of the service.build.platforms: "linux/amd64"
make: *** [Makefile:48: unit-tests-ci] Error 1
Error: Process completed with exit code 2.
```
I admit that I don't fully understand the error message in GHA and how it relates to our docker-compose.yml platform setting (a number of services have the platform directive, but they don't fail on GHA at the moment)
Removing this line appears to get GHA running, and I'm also still able to run the `make unit-tests` locally on MacOS without a specific platform designation, so perhaps "no harm done".
Fixes #1483 

remove platform line in docker-compose.yml and get GHA running again

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/set-backlog-fields.yml

I added a new column in the backlog called "incoming".  This is different than the "triage" column in that new issues are easily visible here and are manually moved to the triage column for further processing/sorting before "accepted".
- process change
Once this is merged, I'll create a new issue and test that it does in fact go into the "incoming" column

add new issues to "incoming" column in backlog

---

.github/pull_request_template.md

This is a bit of a circular thing to fill out the PR description for a PR that modifies the PR description template #1111 
- Reworded the testing sections to make it clearer how we should test and how we assign testers
- move "Fixes issue" to top
This is in response to a [discussion over on our retrospective board](https://trello.com/c/PSOAvdJH/118-testing-cards)

PR template modifications

---

src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php

Fixes #1496
This PR corrects code in LexUploadCommands.php in uploadFile(), which converts audio files from Language Forge into WAV or MP3 format for send/receive with FLEx if needed. Previously, part of this function was inadvertently rewriting the FLEx-compatible files so that they actually contained media of the original (not compatible) recording type. Thus, they were not playable in FLEx. 
The code has been corrected and we will confirm that the files are now playable when brought into FLEx.
- [  ] I have added tests that prove my fix is effective or that my feature works
[Audio Test Upload Files.zip](https://github.com/sillsdev/web-languageforge/files/9681369/Audio.Test.Upload.Files.zip)
Testers: Check the box and put in a …

Correct the naming and storage of FLEx-compatible audio files

---

test/e2e/pages/editor.page.ts
test/e2e/semantic-domains.spec.ts
test/e2e/utils/playwright-helpers.ts

The following test has been converted to playwright
✓ should be using English Semantic Domain for manager
The other tests had to be combined to one large tests called *Can change Project default language to Thai & back and forth* as they were all dependent on each other
✓ can change Project default language to Thai
✓ should be using Thai Semantic Domain
✓ can change Project default language back to English
✓ should be using English Semantic Domain
✓ can change Project default language back to Thai
✓ should be using Thai Semantic Domain after refresh
✓ can change user interface language
✓ should still have Thai for Project default language
✓ should be using English Semantic Domain
✓ should be using English Semantic Domain after refresh
✓ should still have Thai for Project default language …

Semantic domains tests

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

Fixes #1495
Browsers indicate that a media recording stream was opened with a red circle on the recording website's tab. Here is an update that makes it so that this red circle disappears unless the user is actively recording.
- UI change
Ending media stream tracks so that this circle will not linger on the browser tab.
Testers: Check the box and put in a date/time to sign-off/attest the feature works as expected on qa.languageforge.org

removes red circle from tab after stopping recorder

---

.vscode/settings.json

The makefile extension (ms-vscode.makefile-tools) complains that it can't find the makefile entrypoint, because our makefile is not in the root of the project. This minor change will prevent it from showing the warning.
Open VS code. No more "makefile entrypoint not found" popups. (They've potentially already been explicitly suppressed).

Tell CS Code make extension where the makefile is

---

src/angular-app/bellows/shared/sound-player.component.ts

Fixes #1512 
With our AngularJS bindings, the duration of an audio file is not displayed unless it has been loaded. Previously, the DOM was not being updated immediately upon the duration becoming available. This PR tells the $scope to apply its changes to the DOM once the "durationchange" event has occurred on the HTML audio element.
Because it takes a small amount of time for the duration to become available, there is still visible movement; there is a split second from when the entry is clicked on and the duration is not there, to when the duration appears.
- UI change
Before, I was able to reproduce Chris's bug video in issue #1512, for me on Windows 10 with Google Chrome. Now I am seeing this:
https://user-images.githubusercontent.com/56163492/194026070-6acebb2e-ce3f-45e3-968c-6f66995 …

Apply audio durations to scope immediately upon their availability

---

docker/ssl/Caddyfile
docs/DEVELOPER.md

We can use ngrok to create a URL that accesses what's in localhost from another device. This allows us to test local branches' functionality on mobile devices. This PR adds instructions about how to do this to Developer.md.
Also, we disable HTTPS redirects in Caddy to facilitate easy ngrok usage
Fixes #1478
-Expanding developer instructions
N/A
- [N/A ] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have added tests that prove my fix is effective or that my feature works

Instructions for mobile device testing on a branch

---

docker/deployment/db-deployment.yaml
docker/docker-compose.yml

Fixes #1173 
There is a desire to utilize aggregation pipelines and take advantage of possible perf improvements.
- infrastructure upgrade
N/A
Testers: Check the box and put in a date/time to sign-off/attest the feature works as expected on qa.languageforge.org

upgrade mongo to 4.2

---

src/Site/views/languageforge/theme/default/page/home/index.html.twig

Fixes #1522 
Guests were not able to see additional resources like youtube videos, the online community, latest features, etc.
Testers: Check the box and put in a date/time to sign-off/attest the feature works as expected on qa.languageforge.org

Add more public facing links to additional resources

---

src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php
src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts

Fixes #1507 
Recently, it seems that the Geckofx .NET wrapper in FLEx has been updated to allow WEBM files. (Please see this issue for discussion of past difficulties with WEBM audio in FLEx: [](https://jira.sil.org/browse/LT-20864).)
So, instead of converting recordings and uploads to MP3 or WAV format, we can now keep recordings in WEBM and convert formats like OGG, FLAC, and M4A to WEBM for use with FLEx. With WEBM in opus codec, we can maintain higher audio quality and smaller file sizes for audio than with MP3. 
Note: although in one commit, I tested with aflt codec, we are going to continue to use opus codec.
(This is really a change to the audio …

Keep WEBMs and convert to WEBM

---

.devcontainer/devcontainer.json
.github/workflows/build-and-publish-next.yml
.github/workflows/integrate-and-deploy.yml
.github/workflows/pull-request.yml
.vscode/settings.json
.vscode/tasks.json
Makefile
docker-compose.yml
docs/DEVELOPER.md
next-app/README.md
package-lock.json
package.json
playwright.config.ts
test/e2e/playwright_guide/playwright_cheatsheet.md

Fixes #1511
Makefiles as well as docker-compose.yml are expected to be in the project root, so this PR moves them both there.
- Repo restructure

Move Makefile and docker-compose.yml to repo root

---

src/Site/views/languageforge/container/languageforge.html.twig
src/angular-app/bellows/apps/projects/projects-app.component.html

Fixes #1540 
Workaround for  #1536 
This PR is directly against the master branch, intended to be shipped quickly.  Unfortunately, develop branch would not build for me on mac (see Slack channel for details).
Based upon my workshop this morning and observing multiple projects experiencing 500 errors in the dashboard, some consistently, this commit reverts the project page links to go directly to the lexicon app, instead of the dashboard.
This can be reverted back to the dashboard once we have more confidence that dashboard is stable and does not block users from getting to the app.
- Temporary (emergency) workaround for blocked users, intended to be reverted at a later date
.  The (dashboard) link goes to the dashboard.  In this way users are not blocked for projects that are currently …

Temporarily revert project links to avoid dashboard

---

.github/workflows/pull-request.yml

Fixes #1533
Explicitly give the `unit-tests` job write permissions for checks & pull-requests. Writer permissions are required, but dependabot PRs only get read permissions by default.
- Automation improvement

Chore: Explicitly define & provide permissions for unit-tests workflow job

---

.github/workflows/pull-request.yml
Makefile
docker-compose.yml
docs/DEVELOPER.md
package.json
playwright.config.ts

Fixes #1511
This is the implementation of @longrunningprocess's [suggestions on my first PR](https://github.com/sillsdev/web-languageforge/pull/1531#pullrequestreview-1145847654).

Simplify docker-compose.yml and it's usage

---

Makefile

This seems cleaner than having a target for a single command.
`$(MAKE)` is the recommended way rather than simply `make`
This change will result in `make playwright-tests-ci` running `npm ci` and then also `npm install`, but I think that's harmless and is simpler than introducing more make targets or make variables with shell `if`s.

Rework Makefile to remove npm-ci target

---

src/Site/views/languageforge/container/languageforge.html.twig
src/angular-app/bellows/apps/projects/projects-app.component.html
test/e2e/pages/projects.page.ts

This PR duplicates the hotfix to master PR #1544 , but this time as a proper PR against develop.
In this PR I need to fix up the playwright tests to suit after changing the project board links, since playwright tests are failing with this change.
The description below is a copy of the PR #1544 description and details.
Fixes #1540 
Workaround for  #1536 
This PR is directly against the master branch, intended to be shipped quickly.  Unfortunately, develop branch would not build for me on mac (see Slack channel for details).
Based upon my workshop this morning and observing multiple projects experiencing 500 errors in the dashboard, some consistently, this commit reverts the project page links to go directly to the lexicon app, instead of the dashboard.
This can be reverted back to the …

Temporarily revert project list links to avoid dashboard 500 errors and unblock users

---

src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php

Fixes #1518 
I previously used the wrong ffmpeg option for setting the codec for the output file of conversion to WEBM. As a result, the converted files had an incompatible codec and container. This PR uses the right option, and files are successfully converted from OGG, FLAC, or M4A formats to WEBM format. I have verified the fix by playing back the files on Language Forge, as well as downloading them and inspecting them with ffprobe. Once this PR is staged, I will verify that the converted files work in FLEx.
Here is a folder of test files:
[Audio Test Upload Files.zip](https://github.com/sillsdev/web-languageforge/files/9730261/Audio.Test.Upload.Files.zip) …

Correct the syntax for codec selection

---

src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html
src/angular-app/languageforge/lexicon/settings/configuration/configuration-input-systems.component.html
src/angular-app/languageforge/lexicon/settings/configuration/configuration-input-systems.component.ts
test/app/languageforge/lexicon-traversal.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-fields.e2e-spec.ts
test/app/languageforge/lexicon/settings/config-input-systems.e2e-spec.ts
test/app/languageforge/lexicon/shared/configuration.page.ts

Fixes #1553
Input systems should not be edited in Language Forge, only in FLEx.
In this PR:
-Got rid of the 'three dots menu' that allowed adding input systems, on the "Input Systems" tab in Configuration
-Kept selectors for RTL language, language abbreviation, and font name
-Other settings for writing systems are displayed but not editable (special, purpose, variant, region), with a message to that effect
-Got rid of "+ New" buttons in the input systems tab and under "Input Systems" in the base configuration page
-Got rid of the modal for adding a new writing system, formerly attached to these buttons
Before:
After:
Before:
After:
- [N/A] I have commented my code, …

Disable editing input systems

---

docker-compose.yml
docker/deployment/db-deployment.yaml

Fixes #1520 
There is a desire to utilize aggregation pipelines and take advantage of possible perf improvements.
- infrastructure upgrade
N/A
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.
- A general smoke test in addition to successful automated tests should be enough to move forward with this one.  [upgrade mongo to 4.2](https://github.com/sillsdev/web-languageforge/pull/1519#top) is a good reference as well.
Testers: Check the box and put in a date/time to sign-off/attest the feature works as expected on qa.languageforge.org

upgrade mongodb to 4.4

---

src/Site/views/languageforge/container/languageforge.html.twig

Fixes #1539 
This PR provides some vertical scroll behavior to the "My Projects" dropdown just in the current user has more projects than VH.
see issue for reference
- Log in with an account that has some/many projects on it (or make your window small enough to trigger the scroll) and open the "My Projects" dropdown in the header.  You should see the scroll behavior.

add scroll behavior to my projects dropdown

---

src/angular-app/languageforge/lexicon/lexicon-app.component.ts

Fixes #1571 
This PR seeks to quiet down the LF notification system when detecting online/offline status.
Without the notifications:
https://user-images.githubusercontent.com/4412848/199065248-c961cd81-b506-46e1-b8b5-3975da0c94bf.mov
- Go offline (via your wifi or dev tools->Network->Offline) and ensure the top app bar changes colors and the header title shows "Offline"

eliminate notifications for offline/online status

---

src/angular-app/bellows/shared/pick-list-editor.component.html
src/angular-app/bellows/shared/pick-list-editor.module.ts
src/angular-app/languageforge/lexicon/settings/configuration/configuration-option-lists.component.html

Fixes #1552 
Because options added or deleted in Language Forge are not being received into FLEx properly, we want to disable adding (deletion is already disabled) them in Language Forge. Because we may wish to restore this functionality in the future, with a better architecture to ensure synchronization, this PR takes out as little code as possible while preventing users from making these edits for the time being.
Before:
After:
General smoke test, and:
Navigate to the Options List tab of Configuration. Ensure that the text input and '+ Add to List' button are removed and a message at the top of each options list node reads "To add or remove items from this …

Disable adding to options lists

---

next-app/src/routes/projects/[project_code]/meta/+server.ts
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Service/Sf.php

The LFNext app is trying remain stateless while continuing to utilize the legacy app's backend which is very session-based so this PR will serve to establish the legacy app's needed session state.
- Bug fix (see #1536 for initial sighting)
N/A
- Visit the editor, then return to the project list and go straight to the dashboard
- Delete a project and then go to a dashboard from the project list

refactored session mgmt between legacy and next apps

---

Makefile

The base-php image is updated every once in a while.  It is normally build locally by a dev and then manually pushed to Dockerhub via GHA.  This PR provides a make target to build base-php locally.
- chore
- run `make build-base-php` locally and confirm that it works

add Makefile target for building base-php

---

next-app/src/lib/stats/Stat.svelte
next-app/src/routes/projects/[project_code]/+page.svelte

Fixes #1525 
The PR will make stat cards on the project dashboard clickable now.  I could not determine a deep link for the Users card so I left that one alone for now.
N/A
Head to the dashboard for a project
- Ensure the users card is not clickable
- Ensure any cards with 0 value are not clickable
- Ensure any cards, other than Users, that have values, are clickable
- Ensure when a card is clickable, the cursor changes to a pointer finger when hovering over the card
- Ensure clicking on the cards goes to the correct page

made stats clickable under the right circumstances

---

.github/workflows/integrate-and-deploy.yml
.github/workflows/staging.yml
docker/app/Dockerfile

Fixes #1582 
This PR seeks to simplify the legacy app's version stamping process
N/A
- Once deployed, pop open devtools and ensure the cache-buster on UI assets looks correct for that environment.

simplified version stamping

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-example.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html
test/e2e/editor-entry.spec.ts
test/e2e/pages/editor.page.ts

Fixes #1537 
This PR changes the UI in accordance with some developer observations of users struggling with how to perform some activities on their dictionary entries.
- UI change
https://user-images.githubusercontent.com/4412848/200657385-8f6fcc8b-527f-41e7-9bea-0a8c76dec26c.mov
looks good but I do demonstrate the widely-known issue of hover behavior on mobile devices... we can either live with it, consider bringing popper or some other 3rd-party lib in, remove the tooltips entirely or utilize more javascript to isolate hovers to appropriate devices.
https://user-images.githubusercontent.com/4412848/200659475-dff5cb87-8371-4e8a-9d11-3fd6ea6a634c.mov
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as …

improved delete and move UX on entry, meaning and examples

---

docker/deployment/scripts/kubeSyncMongo.sh

This is an untested script to facilitate copying prod data to qa - which is basically executable documentation.  We may never use this, but I recently updated this file before I realized that @longrunningprocess would work with LTOps to copy prod data to qa, and that seems to have worked fine.

refactor kubeSyncMongo executable documentation

---

next-app/src/routes/projects/[project_code]/activities/+server.ts
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Service/Sf.php

Fixes #1576 
This PR extends the convention of keeping the stateless calls into the LFNext portions of the app in sync with the stateful requirements of the legacy app.
N/A
- Simply hitting the project dashboard on a project with activity and ensuring there are no failures is a good test.
- While on the dashboard for a project, ensure the "Show all" works as well
- Also ensure clicking on "work on this project" and coming back to the dashboard retains correct project

refactor activity call into consistent convention

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts

Fixes #1596 
This PR adds missing punctuation found in testing recently.
- UI change
N/A
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.
- Attempt to delete an entry and ensure there is a question mark in the chicken page
- Attempt to delete an audio file and ensure there is a question mark in the chicken page
- Attempt to delete a meaning and ensure there is a question mark in the chicken page
- Attempt to delete a picture and ensure there is a question mark in the chicken page
- Attempt to delete an example and ensure there is a question mark in the chicken page
Testers should add his/her findings to end of the PR in a comment and …

added missing punctuation

---

src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-example.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html

Fixes #1595 
Althought HTML's `title=` is a bit unreliable across browsers and ill-advised for a11y reasons, we've decided to go ahead with them for sake of those users who will benefit from them as toottips.
- UI change
https://user-images.githubusercontent.com/4412848/202000515-68d32195-3ea7-405b-972f-fce5bac11c50.mov
- Create an entry and hover over the trash can icon and ensure you see a tooltip.
- Create enough meanings to hover over the trash can, up and down arrow keys to see each of the tooltips and ensure they are correct.
- Create enough examples to hover over the trash can, up and down arrow keys to see each of the tooltips and ensure they are correct.

utilize HTML `title` for tooltips

---

.github/workflows/pull-request.yml
.gitignore
Makefile
test/e2e/semantic-domains.spec.ts
test/e2e/utils/fixtures.ts
test/e2e/utils/login.ts
test/e2e/utils/user-tools.ts

In #1557 I moved the playwright.config.ts file to the playwright test folder. But I overlooked a few things:
1) That affected where test results get stored
2) It affects where storageState.json files get created when running tests via VS-Code extension
So, I've fixed and standardized those things.

Fix moving playwright.config.ts

---

.github/pull_request_template.md

As far as I can tell, only the title of a PR is used in the PR's commit message.

Clarify use of title & description in merge commits and add auto-merge reminder

---

src/angular-app/languageforge/lexicon/editor/editor-list.view.html

Fixes #1605 
This allows the message "Looks like there are no entries yet." to appear for any member of the project (including commenters), and the two buttons to appear for any member of the project who can edit. Previously, with empty projects, these items only displayed if the member was a manager (to include owners and admins, but not editors or commenters).
- UI change
This is what we were seeing before, for anyone with permissions less than a manager's:
Now viewers and commenters will see this:
and editors, managers, and above will see this:
1.Create an empty project and share it with another user, giving them only the (default) "can edit" permissions. Sign in …

make empty projects display correctly for non-managers

---

.vscode/extensions.json
.vscode/tasks.json

- removed outdated tasks
- fixed up npm install task to work on MacOS and prevent task error in VSCode.
- removed unused workspace extension recommendations
Ref: https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

slim down vscode tasks.json

---

.github/workflows/pull-request.yml

When a dev pushes new commits to a PR, it is possible that GHA is still running a current build and test workflow.  This change enables a concurrency policy that will cancel stale GHA workflows.  This is considered an efficiency improvement as otherwise GHA continues to build and test outdated code.
References:
[GHA Concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
[Stack Overflow - How to cance GHA PR runs when you push a new commit](https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898)
- infrastructure change
This is a GHA workflow change, and the new feature can be tested by pushing a commit to a PR branch while there is a current build …

use GHA concurrency for PR builds and testing

---

src/Api/Model/Shared/Dto/UserProfileEncoder.php
src/Api/Model/Shared/ProjectListModel.php
src/Api/Model/Shared/ProjectList_UserModel.php
src/angular-app/bellows/apps/siteadmin/site-admin-users.component.html
src/angular-app/bellows/core/navbar.controller.ts
test/php/model/shared/UserModelTest.php

This removes the siteName from the ProjectList_UserModel query so that all projects for the user show up regardless of sitename encoded in the database.
It also removes a few unused references from the front-end.
This is a follow up PR to #1592 to allow projects to show in the project list regardless of the siteName data in mongo.
After this PR, QA should show all projects appropriately in the project list.
Additionally, the site admin user list contains links to projects for each user.  These links should still work.  click on one to verify it works.

remove siteName from project list query

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.html

Fixes #1622
Fixes the alignment of the image caption comment bubbles that were offset.
Before:
After:

Fix alignment of image caption comment bubbles

---

src/angular-app/languageforge/lexicon/editor/comment/comments-right-panel.component.html
src/angular-app/languageforge/lexicon/editor/comment/comments-right-panel.component.ts
src/angular-app/languageforge/lexicon/editor/comment/dc-comment.component.ts

Fixes #1620
Stop closing/hiding "new comment" field when opening/closing replies.
The "New converstion thread" is now always visible:
Please describe how to test and/or verify your changes. Provide instructions so we can reproduce. Please also provide relevant test data as necessary. These instructions will be used for QA testing below.
- Create 2 comments on 1 field
- Click "comments" (i.e. replies) on 1st comment
- Observe: new comment field is still visible
- Click "comments" on 2nd comment
- Observe: All 3 fields are now visible

Don't toggle new comment field when opening/closing replies

---

Makefile
src/Api/Model/Shared/Command/ProjectCommands.php
src/Api/Model/Shared/Dto/RightsHelper.php
src/Api/Service/Sf.php
src/angular-app/bellows/apps/projects/projects-app.component.html
src/angular-app/bellows/apps/projects/projects-app.component.ts
src/angular-app/bellows/apps/usermanagement/members.component.ts
src/angular-app/bellows/core/api/project.service.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/role-dropdown.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/role-dropdown.component.ts
src/angular-app/languageforge/lexicon/shared/share-with-others/user-management.component.html
src/angular-app/languageforge/lexicon/shared/share-with-others/user-management.component.ts
test/e2e/pages/projects.page.ts
test/e2e/projects.spec.ts
test/php/model/shared/commands/ProjectCommandsTest.php

Fixes #1541
Fixes #1613
Now, in the projects list, admins can remove themselves from projects that they have been tech support for. 
I also added a notice to "remove" in the role dropdown of the user management component. 
Additionally, tech supports now have their own icons in the role-dropdowns in the user management component, and the "add tech support" button in the projects list now redirects to the project page immediately after the tech support adds him/herself.
- UI change
Button to leave project in a tech support's project list:
Tech support icons + dropdowns
1. Sign in as an admin. Make a project and then transfer ownership of that project to someone else. Go back to the projects list and click "Leave this project". …

Remove self (a tech support) from project

---

src/angular-app/languageforge/lexicon/shared/share-with-others/invite-member-form.component.ts

While QAing #1611 I bumped into this. `angular.element()` supports [very little if jQuery is not included](https://code.angularjs.org/1.8.2/docs/error/jqLite/nosel). So, it didn't like this selector anymore.

Refactor jQuery-dependant selector

---

.github/workflows/pull-request.yml

The new label check GHA is problematic in that it currently only respects the labels on the PR at creation time. By adding the token we implicitly tell/enable it to access the "live" labels.
I noticed it here: https://github.com/sillsdev/web-languageforge/pull/1637
The [documenation](https://github.com/marketplace/actions/require-labels) is a bit confusing to me:
But I tested it [in my fork](https://github.com/myieye/web-languageforge/pull/17). In that PR I last did it backwards: first suceed and then fail.

Make label check use current labels

---

.github/pull_request_template.md

Without this reminder, I think we 'll be manually retriggering the label check quite a bit.

Add PR label reminder to template

---

.github/workflows/integrate-and-deploy.yml
.github/workflows/staging.yml
docker-compose.yml

We noticed during the last release that the cache buster for assets was messed up.  It turns out to be a problem with the timing in which (and how) the E2E tests were being run.  This PR fixes that.
- ensure the `v=` on assets in the devtools is not `9.9.9`.

fixed asset versioning

---

next-app/src/lib/auth/index.ts
next-app/src/lib/data/user.ts
next-app/src/lib/fetch/client.ts
next-app/src/lib/fetch/server.ts
next-app/src/routes/password/+server.ts
next-app/src/routes/projects/[project_code]/+page.server.ts
next-app/src/routes/projects/[project_code]/+page.svelte
next-app/src/routes/projects/[project_code]/activities/+server.ts
next-app/src/routes/projects/[project_code]/meta/+server.ts

Fixes #1579 
This PR establishes some authorization around the visibility of comments to the appropriate project members.
view of project dashboard when logged in as a project member with the "observer" role:
view of the dashboard for all other roles:
- View the project dashboard as an observer and ensure "unresolved comments" and the "Activity" section are not shown
- View the project dashboard as an observer (with comments) and ensure "unresolved comments" is shown and the "Activity" section is not shown
- View the project dashboard as any other role and ensure "unresolved comments" and "Activity" section is shown

hide comments and activity from project "observers"

---

src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts

Fixes #1645 
This PR removes code related to an old feature that is not used anymore.  The logic was causing a runtime error while trying to save profile settings.
N/A
- Update profile settings and ensure they are saved.

removed old project-specific settings feature

---

.github/workflows/integrate-and-deploy.yml
.github/workflows/pull-request.yml

I removed this `if` in #1636, because I thought it was unnecessary  (of course I only tested the success case in that PR).
It's actually pretty crucial 😆, because without it our results don't get saved when there's a test failure. Oops.
- Testing Bug fix

Upload playwright results when workflow fails

---

src/angular-app/bellows/shared/sound-player.component.html
src/angular-app/bellows/shared/sound-player.component.ts
test/e2e/editor-entry.spec.ts
test/e2e/pages/editor.page.ts

Fixes #1644 
This PR brings changes to the initialization of the slider input (we are no longer using jquery for that). This ensures that the audio element's current time updates as seeking and playing events occur. By changing the audio element's play/pause logic so that its current time is not reset to 0, we allow for seeking and starting playback in the middle of an audio clip.
Current time changes with seeking & play
Go to a project with audio available in entries, e.g., test-chris-02 in staging.
Move the slider and verify that the current time changes with it.
Click play and verify that the audio starts from the updated time.
Testers should add his/her …

Repair audio seeking

---

.github/workflows/set-backlog-fields.yml

There were some `set-output` deprecation warnings showing up in our workflows and it turned out to be in some of our third-party actions.  This PR will simply upgrade those to a version where the author has migrated away from `set-output`
One of the deps is currently working on a fix, keep an eye on https://github.com/mheap/github-action-required-labels/issues/42 to determine whether a change is needed in our `pull-request.yml -> require-label` step or not.
- CI/CD update
- Ensure PR and `staging` workflows no longer have deprecation warnings.

eliminate GHA deprecation warnings

---

docker-compose.yml

This change addresses an issue seen on Apple Silicon/ARM only, whereby the most recent Docker version on MacOS is more strict when it encounters images not built for arm64.
Switching to mariadb from mysql fixes the issue as mariadb provides both amd64 and arm64 images.  mysql does not, or the package metadata is corrupt in some way that Docker is not expecting.
MariaDB is understood to be a drop-in replacement for MySQL.
This PR resolves the error I have seen on my machine:
```
[+] Running 1/2
⠿ ld-db Pulled                                                            2.5s
⠋ d410f4167eea Exists                                                   0.0s
⠋ 6306f106a056 Exists                                                   0.0s
⠋ bd0fb5a175fc Exists …
```

switch to using mariadb for ld-db

---

.prettierignore
docker/ui-builder/Dockerfile

This COPY line should have been removed as part of #1669
This PR fixes a local dev error when running ui-builder e.g. `make dev` or `make e2e-tests`
- Fix broken build
This is the error a dev will encounter before this PR is merged
`make e2e-tests` should build and run locally without error

remove obsolete COPY line in ui-builder

---

docker/base-php/Dockerfile

The [PHP GD extension](https://www.php.net/manual/en/book.image.php) is, as far as I can tell, no longer used in our PHP code.  It no doubt was used in the past but I cannot find any reference to methods it provides in our current PHP code, and I have personally run all unit and e2e tests locally without the extension and they all pass.
This feels like a safe removal.  This will also speed up build times for the base-php image, especial for PHP >= 7.4
- Remove unused dependency
This is considered tested with unit and e2e tests all passing

remove GD PHP extension from base-php

---

.github/workflows/build-and-publish-base-php.yml

fixes #1398
This changes the base-php build to use buildx for multi-arch builds for both linux/amd64 and linux/arm64
Both images are published to https://hub.docker.com/r/sillsdev/web-languageforge/tags
The base-php image is now being built with this method, [as seen here (manual trigger)](https://github.com/sillsdev/web-languageforge/actions/runs/3852970907/jobs/6565532643): 
- engineering
Doing a multi-architecture build using buildx and qemu on a x86 GHA runner (that is all that is available) is extremely slow due to arm64 emulation.  GHA may launch an arm runner, but until they do, there is an option to pay for an arm runner if you don't want to host your own (which we could).  See https://buildjet.com/for-github-actions/pricing
Passing unit and E2E tests are sufficient testing for …

build multi-arch arm64/amd64 base-php image

---

docker-compose.yml

Now that base-php is available for arm64 and amd64, we can remove the platform=linux/amd64 requirement for the lf-app and e2e app.
We have a working LF app running on ARM!
- Docker
Local dev on Apple Silicon can see that the app is now running natively and not under amd64 emulation:
Local dev on Apple Silicon can verify that lf-app is running natively and not under emulation (see screenshot above from Docker desktop)

allow lf-app to run on ARM for Apple Silicon

---

Makefile
docker-compose.yml
docker/composer-dev/Dockerfile
src/composer.json
src/composer.lock

Removes these PHP dependencies:
- phpunit/php-code-coverage
- squizlabs/php_codesniffer
- twig/extensions
Updates a few small dependencies to the latest possible under PHP 7.3:
- PHPUnit
- Twig
- SwiftMailer
- Symfony
- Silex
Also introduces a new docker service/container called `composer-dev`
It is used for running composer commands in the environment (PHP w/ dependencies) of our application.
Run `make composer-dev` and you will be put into a running container with composer files volume mapped for easy editing/committing
- PHP dependency upgrades
Considered tested if PHP and E2E tests are passing

Update PHP dependencies / add composer-dev container

---

docker-compose.yml
src/composer.json
src/composer.lock
test/php/library/shared/communicate/CommunicateTest.php
test/php/model/languageforge/lexicon/Import/LiftImportTest.php
test/php/model/languageforge/lexicon/Import/LiftImportZipTest.php
test/php/model/languageforge/lexicon/LexProjectModelTest.php
test/php/model/languageforge/lexicon/command/LexUploadCommandsTest.php
test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php
test/php/model/shared/commands/UserCommandsTest.php
test/php/phpunit.xml

- Upgrade PHPUnit to v9.5
- prefix composer-dev image name with `lf-`
- fix PHPUnit method names that have been deprecated
- migrated PHPUnit config file to latest schema
- PHP dependency upgrade
This is considered tested when PHP unit tests are passing

upgrade PHPUnit to version 9.5 (latest version)

---

docker-compose.yml
docker/test-php/Dockerfile
docs/DEVELOPER.md

While this might make our tests run slightly slower when we don't want to debug, it simplifies the process for the developer - they always know that they can set a breakpoint and debug PHP tests
- chore
PHP unit tests pass

enable xdebug for PHP tests

---

docker/lfmerge/Dockerfile
src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.ts

Fixes #1679
Makes use of the new 10MB file size limit in LfMerge/Chorus.
Adapts the file-szie warnings accordingly.
- New feature
Updated warning:
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
1)
Add these images:
- [5 MB](https://user-images.githubusercontent.com/12587509/212048566-544053bf-5f2f-47fd-b13e-79caa8564597.jpg)
- [8.7 MB](https://user-images.githubusercontent.com/12587509/212048963-3ac31cf3-fa5e-493c-85e9-afca1e193053.jpg)
- [10+ MB](https://sample-videos.com/img/Sample-jpg-image-10mb.jpg)
And this audio file (just if you're curious, it's an mp3, but GitHub doesn't like that file extension):
- [5 MB](https://user-images.githubusercontent.com/12587509/212052285-68d596b7-d79f-4d78-9348-73c09f12fedb.webm)
...to an entry.
2) Sync the project …

Use new LfMerge version with 10MB file size limit

---

docker/lfmerge/Dockerfile

fixes 
Upgrade LFMerge to v2.0.133
Incorporates changes in https://github.com/sillsdev/LfMerge/pull/320
This resolves a C# Exception that users have encountered in production
Before the PR is merged, project `orm-ec-flex` will not sync due to the exception documented in #317
Link to project on QA: https://qa.languageforge.org/app/lexicon/63c500b8ec96807d4b056722/#!/sync
After this PR is merged, we should be able to remove the HOLD status on the project, and then re-sync and see that it is successful.  The project was cloned today, so it should be safe to sync.
- Project orm-ec-flex can successfully sync with FLEx

update LFMerge to 2.0.133

---

docker-compose.yml
docker/app/Dockerfile
docker/test-php/Dockerfile
src/Api/Library/Shared/Communicate/Email.php
src/Api/Library/Shared/LanguageData.php
src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
src/Api/Model/Languageforge/Lexicon/Command/LexEntryDecoder.php
src/Api/Model/Languageforge/Lexicon/Command/LexProjectCommands.php
src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php
src/Api/Model/Languageforge/Lexicon/Config/LexRoleViewConfig.php
src/Api/Model/Languageforge/Lexicon/Dto/LexDbeDto.php
src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexMultiText.php
src/Api/Model/Languageforge/Lexicon/LexProjectModel.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
src/Api/Model/Shared/Command/SessionCommands.php
src/Api/Model/Shared/Dto/ActivityListDto.php
src/Api/Model/Shared/Mapper/JsonDecoder.php
src/Api/Model/Shared/Mapper/JsonEncoder.php
src/Api/Model/Shared/Mapper/MapOf.php
src/Api/Model/Shared/Mapper/MongoEncoder.php
src/Api/Model/Shared/ProjectModel.php
src/composer.json
src/composer.lock

Upgrade our codebase and composer dependencies to run on PHP 7.4
This was a marathon requiring intense concentration to debug errors in our PHP tests and application, especially related to changed behavior from PHP 7.3 -> 7.4 for the `array_key_exists()` and `get_object_vars()` functions.
There is no section in our PR template for HOURS SPENT 😭 
My [commits are fairly well organized](https://github.com/sillsdev/web-languageforge/pull/1696/commits), so here's the summary of what's changed:
Unit tests and E2E tests passing are sufficient evidence that this PR is acceptable.

Upgrade to PHP 7.4

---

src/angular-app/bellows/apps/userprofile/user-profile-app.component.html

Previously, any modifications in the user profile component would generate a notice: 'Profile updated successfully.' But now, for account deletion, we only display 'Your account was permanently deleted' and not the 'Profile updated successfully' notice that other modifications generate.
Before:
After:
- Under 'My Profile' > 'My Account', make changes to your avatar (color, animal). Click 'Save'. Verify that the 'Profile updated successfully' notice is given.
- Under 'My Profile' > 'About Me', make changes to your personal information. Click …

No 'Profile updated successfully' notice on delete

---

src/Api/Service/Sf.php

Customizes the info message on the login screen after deleting your own account.
@laineyhm This is something small that I figured was sort of missing when I QA'd https://github.com/sillsdev/web-languageforge/issues/1697.
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
1) Delete own account
2) Observe Message in screenshot above

Show 'Account deleted' message on login screen

---

src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php

Fixes #1679  
Now that Language Forge allows for Send/Receiving files up to 10 MB in size, we can base our audio conversion settings on the 10 MB limit rather than the old 1 MB limit.
This PR affects this setting: Settings > Project Settings > Convert Uploaded Audio to OPUS/WEBM...
For Send/Receive, we can now just convert audio files that are larger than 10 MB (and/or don't have MP3, WAV, or WEBM file extensions, like before).
Here are two test files, zipped up to accommodate the file extensions: 
[Two audio test files.zip](https://github.com/sillsdev/web-languageforge/files/10455258/Two.audio.test.files.zip)
1. In …

Boost SR limit to 10MB for audio conversion settings

---

src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php

OAuth was broken, because our implementation didn't match [the signature of our dependency](https://github.com/thephpleague/oauth2-google/search?q=getAuthorizationParameters). So, (based on my limited knowledge of PHP, I guess this was due to the [upgrade to PHP 7.4](https://github.com/sillsdev/web-languageforge/pull/1696), rather than the [upgrade of our OAuth lib](https://github.com/sillsdev/web-languageforge/pull/1707).
With this change I get the expected error locally:
- ~I have commented my code, particularly in hard-to-understand areas~
- ~I have added tests that prove my fix is effective or that my feature works~ I want to do this, but I'll do it in a follow up PR. It's acting a bit goofy
Testers, use the following instructions on …

Fix OAuth by adding missing return type

---

docker-compose.yml
src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php
test/e2e/pages/base-page.ts
test/e2e/pages/editor.page.ts
test/e2e/pages/index.ts
test/e2e/pages/oauth-facebook.page.ts
test/e2e/pages/oauth-google.page.ts
test/e2e/pages/project-settings.page.ts
test/e2e/pages/projects.page.ts
test/e2e/pages/signup.page.ts
test/e2e/pages/tabbed-page.ts
test/e2e/tests/oauth.spec.ts

Adds tests that make sure OAuth pages for Google and Facebook load without an exception.
Let 'em rip 🔥

Add E2E tests for OAuth pages

---

next-app/src/lib/forms/Form.svelte
next-app/src/lib/forms/Input.svelte
next-app/src/routes/+page.svelte
next-app/src/routes/password/change/+page.server.ts
next-app/src/routes/password/change/+page.svelte
next-app/src/routes/password/change/+page.ts

This PR migrates the change password functionality toward a newer SvelteKit feature called [Actions](https://kit.svelte.dev/docs/form-actions).
- ensure passwords are required
- ensure the passwords match
- ensure password is actually updated to a new password

migrate to sveltekit action

---

Makefile
src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
src/Api/Model/Languageforge/Lexicon/LexSense.php
test/php/model/languageforge/lexicon/Import/LiftImportFlexTest.php
test/php/model/languageforge/lexicon/LexSenseModelTest.php

The **LexEntryModel->entryImportResidue** and **LexSense->status** fields throw exceptions when they're updated, because they're not configured correctly in PHP.
- ~I have commented my code, particularly in hard-to-understand areas~
- ~I have added tests that prove my fix is effective or that my feature works~
- Update the mentioned fields
- Wait 5s and confirm no error is displayed

Fix broken fields

---

next-app/src/lib/debounce.ts
next-app/src/lib/forms/Button.svelte
next-app/src/lib/forms/Input.svelte
next-app/src/routes/password/change/+page.server.ts
next-app/src/routes/password/change/+page.svelte

This is a follow-through on PR feedback from #1716 
- While trying to change your password, ensure you cannot submit the form unless you've provided a password
- While trying to change your password, ensure you cannot submit the form unless you've provided a confirmation password
- While trying to change your password, ensure you cannot submit the form unless you've provided a confirmation password that matches the new password
- While trying to change your password, ensure you can submit the form and your password has actually changed.

refactor password checks to client-side

---

src/Site/views/shared/_global.scss
src/Site/views/shared/container/container.html.twig

Show a warning on QA, so that people realize they're not working in a production environment.
It's not pretty, but it's not supposed to be 🤷.
This is the poor man solution 😉. A clickable link would be nice. I'll let the reviewers decide if it's worth adding HTML (in 2 places: the logged in and not logged in headers) for that.
- ~I have added tests that prove my fix is effective or that my feature works~
Make sure the layout isn't broken, nothing is covered up in an unusable way and the message appears on all screens.

Show warning message/bar in QA

---

src/Api/Model/Shared/UserModel.php
src/Site/Controller/App.php
src/Site/Controller/Redirect.php
src/Site/Handler/AuthenticationSuccessHandler.php

Ensure that deleted projects are removed from users entirely (including `lastProjectUsed`. Also change many redirects from `/logout` to `/projects`. Ultimately this is a bit overkill, but will hopefully minimize similar hassles in the future. Invalid project-IDs in URLs now land on the projects page.
We commonly redirect to /logout when an unexpected Exception occurs. The thinking is presumably: we'll clear the session and maybe it will work next time. But, I think it often makes just as much sense to assume that the problem is project-specific, so going to the projects page removes the hassle of having to log in again. The user is authenticated, so there's no security issue to worry about. Worst case is that the projects page doesn't work and the user lands in an infinite redirect loop. …

Redirect to projects and clear session project on project exceptions

---

src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php
src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
src/Api/Model/Languageforge/Lexicon/LexCommentFieldReference.php
src/angular-app/bellows/apps/activity/activity-container.component.ts
src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts
src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html
test/e2e/tests/editor/editor.audio.spec.ts
test/e2e/tests/editor/editor.comments.spec.ts
test/e2e/tests/editor/editor.configuration.spec.ts
test/e2e/tests/editor/editor.entries.spec.ts
test/e2e/tests/editor/editor.pictures.spec.ts
test/e2e/tests/entry-list.spec.ts
test/e2e/tests/lexicon-new-project.spec.ts
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
test/php/model/languageforge/lexicon/command/LexOptionListCommandsTest.php
test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php
test/php/model/languageforge/lexicon/dto/LexBaseViewDtoTest.php

| LF labels | FLEx labels |
| --------- | ----------- |
| Word       | Lexeme Form |
| Meaning | Sense              |
| Part of Speech | Grammatical Category |
| Type | Sense Type |
- Ensure field names referenced in table above have changed to the correct label
- Ensure there are no more old field name references in the project configuration area

Update field names to be consistent with FLEx

---

src/Site/views/languageforge/theme/default/page/home/index.html.twig

Add's a privacy policy link to the bottom of the homepage, in order to comply with FB request.
_Describe how to verify your changes and provide any necessary test data._
- Test A

add privacy policy link to home page

---

src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php
src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
src/Api/Model/Languageforge/Lexicon/LexCommentFieldReference.php
src/angular-app/bellows/apps/activity/activity-container.component.ts
src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html
src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts
src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html
test/e2e/tests/editor/editor.audio.spec.ts
test/e2e/tests/editor/editor.comments.spec.ts
test/e2e/tests/editor/editor.configuration.spec.ts
test/e2e/tests/editor/editor.entries.spec.ts
test/e2e/tests/editor/editor.pictures.spec.ts
test/e2e/tests/entry-list.spec.ts
test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
test/php/model/languageforge/lexicon/command/LexOptionListCommandsTest.php
test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php
test/php/model/languageforge/lexicon/dto/LexBaseViewDtoTest.php

This reverts commit 3927735a1779516f65c003d8f7d8f2f72c42f344.
We came to a realization about the significance of the field names and the fact that some were stored in the database that led us to need to back this change out until a later time.
CI tests should be sufficient.

Revert "Update field names to be consistent with FLEx (#1731)"

---

src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/field/field-control.model.ts

See issue
~I have added tests that prove my fix is effective or that my feature works~
Steps to reproduce the original error:
- Go to the Editor
- Click on '+' (Create new entry). Note: an entry only actually gets created when some data is added to it.
- Quickly click on "Add meaning" and then "Add example"
- See ~error~

Bug: multiple changes in quick succession on new entry cause exception

---

next-app/src/lib/forms/Button.svelte
next-app/src/routes/projects/[project_code]/+page.svelte
next-app/src/routes/projects/[project_code]/Activity.svelte
next-app/src/routes/projects/[project_code]/activities/+server.ts
src/Api/Model/Shared/Dto/ActivityListDto.php

The culprit of the Internal Error was PHP's `uasort`, which we were using to sort activity _leaving indices in place_. Leaving indices in places potentially makes the array incompatible of being serialized as a JSON array. We don't care about the indices, so they can be tossed using `usort` instead.
Additionally:
- Now display date **and time** and moved it to the far right (because that seemed more intuitive to me)
- Found something meaningful to put in the "Fields" column as it seemed to be broken,
- Fixed the partially broken sorting  (it was comparing user objects (which are never the same) instead of user names)
- Added a loading indicator, because loading all activity can take a while
_Almost_ removed the sorting by username before time functionality, but...maybe it's useful and I …

Bug: Project activity on dashboard sometimes triggers internal error

---

src/angular-app/languageforge/lexicon/editor/_editor.scss
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.scss
src/angular-app/languageforge/lexicon/editor/editor.component.ts

Embarassingly while switching to async/await syntax in my [previous PR](https://github.com/sillsdev/web-languageforge/pull/1758) I lost a valuable change. So, here it is.
This PR also makes so minor styling/sizing improvements.

Bug: multiple changes in quick succession on new entry cause exception (part 2)

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/editor.module.ts
src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts
src/angular-app/languageforge/lexicon/editor/recording-state.service.ts

See #1762 
1) Make various changes to entries while recording, while uploading or anywhere in between and make sure the recording never gets lost.

Prevent UI updates when there is an unresolved recording in progress

---

src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts

Multi-texts were changed to `textarea` elements at some point, in order to support line wrapping. However, that also allows them to support line-breaks. There seemed to be some logic for values that are supposed to be single-line, but line breaks were not being removed, so this fixes that.
Additionally, I've added a simple log to see what the sample rate is for recordings on my phone. For some reason, I can't record audio when I access the app on my laptop from my phone, but I can when I access it on languageforge.org 🤷.

Bug: remove new lines from multitext

---

docker/lfmerge/Dockerfile

projects previously couldn't sync when they were using the shared xml backend, this updates the lfmerge version to resolve that issue
Remove a project on hold for a sync failure with a not supported exception

resolve a sync request for projects using the shared xml backend

---

src/robots.txt

It appears that one of the reasons languageforge.org does not show up in google search results is the absence of a robots.txt file (who knew?)
From google search console:
This PR needs to be merged and testing can really only be done once the robots.txt has shipped to production.

add basic permissive robots.txt

---

next-app/src/routes/projects/[project_code]/+page.svelte
next-app/src/routes/projects/[project_code]/meta/+server.ts
src/Api/Model/Languageforge/Lexicon/Dto/LexStatsDto.php
src/Api/Model/Shared/Mapper/MongoQueries.php
src/Api/Service/Sf.php

Large projects were returning an HTTP 500 on the project dashboard, because PHP was running out of memory trying to return every entry for stats to be calculated client-side. This changes the stats to be calculated server-side instead. We get rid of the "number of entries with audio" stat because it's not possible to calculate in a simple Mongo query and would require serializing the entire entry database server-side, causing the very memory error we're trying to get rid of.
Fixes #1773.
Fixes #1775.
- Load a large project (via Send/Receive) into Language Forge
- In that project, click on the project name in "My Projects -> (project name)" in the upper left
If the bug is not fixed, you'll get a 500 Internal Server Error page. If the bug is fixed, you'll get the dashboard.

Fix 500 server error on project dashboard

---

docker/deployment/db-deployment.yaml

This will allow k8s to reboot the pod if MongoDB becomes unresponsive.

Add liveness probe for MongoDB container

---

src/angular-app/bellows/core/offline/comments-offline-cache.service.ts
src/angular-app/bellows/core/offline/editor-offline-cache.service.ts
src/angular-app/bellows/core/offline/offline-cache.service.ts
src/angular-app/languageforge/lexicon/settings/configuration/configuration-advanced-options.component.html
src/angular-app/languageforge/lexicon/settings/configuration/configuration-advanced-options.component.ts

Add a button to reset the browser storage cache, in case users need to (e.g., an interrupted download of the project dictionary).
- Go to a project's Configuration options
- Go to the advanced configuration tab
- Open Developer Tools, look at Local Storage in Application tab
- Verify there are entries and comments
- Click the red "Reset browser storage" button
- Verify the entries and comments are gone from local storage

Add reset cache button to advanced project configuration tab

---

docker/app/Dockerfile
package-lock.json
package.json

Node 22 just came out, so we want to upgrade off of Node 16 which is going end-of-life today (end of April 2024). This PR moves
straight to Node 22.
This requires upgrading webpack, as webpack 5.27.1 used a feature of older Node versions that is deprecated in Node 18 and above. No other NPM package upgrades have been *required* yet; once we're running a modern version of Node, I'll upgrade more NPM packages.
N/A
- Run `make`, make sure site still loads. That's about it.

Bump node.js version to 22

---

package-lock.json
tsconfig.json

Updated NPM packages by running `npm up`. This did not update all packages, because in some cases we've put fixed version numbers into package.json rather than versions like `^1.2` which would pull any 1.x package. But this is a start.
Also had to add one line to tsconfig.json, because our `suppressImplicitAnyIndexErrors` config is deprecated since Typescript 5.0 and will go away in Typescript 5.5. But this PR updates to Typescript 5.4.5, so we don't (yet) have to go through and add individual `@ts-ignore` comments before each occurrence of implicit "any" types. That's coming soon, though.
No behavioral changes.
- Run `make`, make sure site still loads.

Update npm packages

---

docker/lfmerge/Dockerfile

LfMerge has been on Mercurial 3 for a long time, and we've had constant trouble with HTTPS certificates because our Mercurial version was too old to support SNI. Moving to Mercurial 6 (and Python 3) will fix that.
_Demonstrate any UI / behavioral changes with screenshots or animations._
_Describe how to verify your changes and provide any necessary test data._
- Do multiple Send/Receives (a clone, a pull, a push, and at least one merge where the project is edited in FLEx and in Language Forge at the same time), and make sure they all succeed.

Update LfMerge to use Mercurial 6 and .NET 8

---

docker-compose.yml

Language Forge port changed to port 8080 so that port 80 can belong to local LexBox.
Add appropriate environment variables to docker-compose.yml so that Language Forge can be run alongside a locally-installed copy of LexBox.
To run:
- Check out [LexBox](https://github.com/sillsdev/languageforge-lexbox/) and run `task up`
- Check out [Language Forge](https://github.com/sillsdev/web-languageforge/) and run `make`
To verify:
- Go to `http://localhost:8080` to run Language Forge
- Click on "Get Project from Language Depot"
- Type in username `manager` and password `pass`
- Note the Sena-3 project is available
- Run `docker logs -f lfmerge` to watch the clone process
- Clone Sena-3
- Go to My Projects and click on Sena-3
- Check that all the entries are there

Set up to run LexBox alongside LF in dev mode

---

src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts

The "Clone new project" page was setting a locationChange event handler to cancel the clone-status timer. However, since the clone-status page counts as a different locaiton, the event was firing as soon as the user pressed the "Get Started" button, cancelling the clone-status timer too soon so the "cloning new project" page was never detecting that the clone completed.
By simply removing the locationChange event handler, we can let the clone status proceed. It changes from "Getting initial data" to "syncing" pretty soon, but that's fine. Once the status goes to idle, the existing code already cancels the timer and loads the project page, so there's no need for any further changes.
Testers, use the following instructions against our staging environment. Post your findings as a comment and …

After cloning new project, go to project when done

---

docker-compose.yml
docs/DEVELOPER.md

Updates documentation to reflect that we no longer encourage WSL development.  Updated references to Node 22 and PHP 7.4
Removed the docker compose version from the yml file because that was causing a warning message.

chore: tiny documentation updates and fix docker compose version warning

---

test/e2e/tests/editor/editor.entries.spec.ts
test/e2e/tests/editor/editor.pictures.spec.ts

We currently have two E2E tests that fail on Firefox while they pass on Chrome.
One of them appears to be caused by `reload()` not triggering our page autosave when it happens immediately after a `locator.fill()`. I suspect that the `reload()` isn't triggering the `blur` event which would allow our autosave to trigger, but only on Firefox (for reasons that would take so long to determine that I figure it's not worth spending the time). I solved this one by clicking on another entry before running the `reload()`, which forces the just-entered data to autosave and thus the rest of the test passes as it should.
The other test appears to be running into [a Playwright bug with `locator.fill()` on Firefox](https://www.github.com/microsoft/playwright/issues/29614), where the locator thinks the …

Fix one failing E2E test on Firefox, skip the other one

---

src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts
test/e2e/utils/project-utils.ts

The default sort uses the first lexeme form (if no citation form is present) which is a problem if the first analysis writing system is an audio writing system. Then the entries are sorted by the filename, which results in a meaningless sort. This pr prevents '-audio' citation forms and lexeme forms from being used.
_Describe how to verify your changes and provide any necessary test data._
- Test A

Prevent sorting by '-audio' citation and lexeme forms

---

.github/workflows/build-and-publish-base-php.yml
docker/app/Dockerfile
docker/base-php/Dockerfile
docker/composer-dev/Dockerfile
docker/test-php/Dockerfile

This is a PR to update the base-php image to 7.4.  We will not update to future PHP versions, so it makes sense to just name this base-php
We also add the mongodb-org-tools apt package to the base-php image for use in the backup/restore planned task.
Once this is merged, I can manually create a new base-php image via GHA.
TODO:
PHP tests complete successfully on my local machine, but will fail in this PR build since base-php hasn't been built properly until this is merged.

Base php 7.4

---

docker-compose.yml
docker/deployment/base/app-deployment.yaml
docker/deployment/base/lfmerge-deployment.yaml
docker/deployment/base/secrets.yaml
docker/lfmerge/Dockerfile
scripts/scriptsConfig.php
src/Api/Model/Shared/Mapper/MongoStore.php
src/config.php
test/php/TestConfig.php

Add env vars `MONGODB_USER` and `MONGODB_PASS` to optionally specify authentication when connecting to MongoDB. Some manual setup on the MongoDB server(s) should be done before this is deployed; see https://github.com/sillsdev/web-languageforge/issues/1787#issuecomment-2119674540 for details. Once the appropriate admin user has been created and Kubernetes secrets set, this PR can then be deployed to staging and production.
Note that https://github.com/sillsdev/LfMerge/pull/336 will need to be merged first, and a new LfMerge version built. The version number in `lfmerge/Dockerfile` can then be bumped as part of this PR.
None
- Log in
- …

Require username and password for mongodb

---

src/angular-app/bellows/apps/activity/activity-container.component.ts
src/angular-app/bellows/core/breadcrumbs/breadcrumb.service.ts
src/angular-app/bellows/core/offline/editor-data.service.ts
src/angular-app/bellows/core/session.service.ts
src/angular-app/bellows/shared/tabset.module.ts
src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.component.ts
src/angular-app/languageforge/lexicon/editor/editor.component.ts
src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts
src/angular-app/languageforge/lexicon/lexicon-app.component.ts
src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts
tsconfig.json

We currently have `suppressImplicitAnyIndexErrors` in our tsconfig.json since we have a lot of implicit `any` types scattered throughout our code. That option [will be going away in Typescript 5.5](https://www.github.com/microsoft/TypeScript/issues/51909), so we need to fix them now so that we can continue to upgrade Typescript in the future (5.5 is currently in beta).
No behavioral changes.
- Run `make`, make sure site still loads.
- Check that there aren't more Typescript errors showing up in VS Code.

Fix "implicit any" Typescript errors to prepare for Typescript 5.5

---

.github/workflows/build-and-publish-base-php.yml
.github/workflows/e2e-tests.yml
.github/workflows/integrate-and-deploy.yml
.github/workflows/pull-request.yml
.github/workflows/set-backlog-fields.yml

This updates outdated workflow versions to ones that use Node 20, silencing the warnings from GHA about workflows using Node 16. Also, the actions/checkout@v3 workflows are deprecated and must be moved to v4 by the end of 2024.
Finally, in the case of a couple of small third-party workflows, I switched to SHA references as recommended in GHA workflow best practices.

Update outdated GHA workflow versions

---

.github/workflows/integrate-and-deploy.yml
docker-compose.production.yml

This will allow the default docker-compose.yml file to build the development build, but allow passing an extra `-f` flag to docker compose in order to build the production build instead. (This is the Docker Compose equivalent of kustomize, though a little easier to use and understand than kustomize).
_Demonstrate any UI / behavioral changes with screenshots or animations._
_Describe how to verify your changes and provide any necessary test data._
- Check PR, make sure tests still pass
- Edit your Makefile and change the `docker compose build` steps to include `-f docker-compose.yml -f docker-compose.production.yml` and make sure running …

Add docker-compose merge file for production build

---

docker/lfmerge/Dockerfile

The release version is identical to the alpha version that was being used previously, except for the version number marking it as tested.
No issue number since this is a trivial one-line change that makes no changes to actual behavior (LfMerge release 2.0.139 is built from the same Git commit as 2.0.139-alpha.43, so it's almost literally no change).

Use release version of LfMerge

---

docker/deployment/base/db-deployment.yaml

This is a followup to https://github.com/sillsdev/web-languageforge/pull/1813.
The `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` variables, if they exist when the MongoDB container is started up, will be used to tell MongoDB to start in auth-required mode. If there is an existing database then the value of these env vars doesn't matter and the usernames and passwords from the existing database will be used instead, but if the database is empty then these two env vars are used to set up an initial administrator account that can access and change anything, and the DB setup scripts are then expected to create any other required users. Since we now have authentication defined in Mongo, we can turn this on by default and everything will continue to work.
This has already been …

Kubernetes deployment now requires Mongo auth

---

src/Api/Model/Shared/Command/UserCommands.php

This fixes a bug where a tech support user cannot add/invite another user
Looks like the tech support role was left off the list of allowed roles to send an invite.
Verify that the repro steps in the bug report show no error message

add tech support role to allowed roles when sending an invite

---

docker/lfmerge/Dockerfile

This pulls in the bugfix for the CommentConversionError class from https://github.com/sillsdev/LfMerge/pull/350.

Update LfMerge version to 2.0.140

---

backup.mjs

It looks like we added MongoDB auth right after the backup script was created, so it was missing this.

Make project backup script auth-aware

---

docker-compose.yml
docker/app/Dockerfile
docker/lfmerge/Dockerfile
docker/next-app/Dockerfile.next-app
docker/next-app/dev/Dockerfile
docker/ui-builder/Dockerfile

We'll start using `chg` for LfMerge in local LF development; once we know that it works, we'll add the relevant environment variable to the k8s deployment so that staging and then prod also start getting the same Send/Receive speedups.
- Run some Send/Receives on local LF and make sure everything still works.

Use chg in LfMerge, only in local dev LF for now

---

README.md
src/Site/views/languageforge/container/languageforge.html.twig
src/Site/views/languageforge/theme/default/page/home/index.html.twig
src/angular-app/languageforge/lexicon/new-project/send-receive/new-project-credentials.component.html

Language Forge is now in maintenance mode.  This PR adds appropriate messaging about maintenance mode and promotes FWLite as a viable alternative to LF.
Specific changes:
- Header prominently displays "maintenance mode"
- About menu includes link to FWLite and maintenance mode doc
- New project wizard includes message and discourages users from creating new projects
- Front page includes the maintenance mode message
[Language Forge is no longer developed and is in maintenance mode](https://community.software.sil.org/t/language-forge-in-maintenance-mode/10514).  We will continue to support existing Language Forge projects and we encourage all users to try [FieldWorks Lite](https://lexbox.org/fw-lite).

Add maintenance mode messages across the application
